/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export type PaymentMethodToken =
  | PaymentMethodToken.PaymentCard
  | PaymentMethodToken.PaypalBillingAgreement
  | PaymentMethodToken.GocardlessMandate
  | PaymentMethodToken.KlarnaCustomerToken
  | PaymentMethodToken.ApayaCustomerToken
  | PaymentMethodToken._Unknown;

export declare namespace PaymentMethodToken {
  interface PaymentCard extends PrimerApi.paymentMethod.PaymentCardTokenSchemaPaymentMethodsAPI, _Utils {
    paymentMethodType: "PAYMENT_CARD";
  }

  interface PaypalBillingAgreement extends PrimerApi.payments.PayPalBillingAgreementSchema, _Utils {
    paymentMethodType: "PAYPAL_BILLING_AGREEMENT";
  }

  interface GocardlessMandate extends PrimerApi.payments.GoCardlessMandateSchema, _Utils {
    paymentMethodType: "GOCARDLESS_MANDATE";
  }

  interface KlarnaCustomerToken extends PrimerApi.payments.KlarnaCustomerTokenSchema, _Utils {
    paymentMethodType: "KLARNA_CUSTOMER_TOKEN";
  }

  interface ApayaCustomerToken extends PrimerApi.payments.ApayaCustomerTokenSchema, _Utils {
    paymentMethodType: "APAYA_CUSTOMER_TOKEN";
  }

  interface _Unknown extends _Utils {
    paymentMethodType: void;
  }

  interface _Utils {
    _visit: <Result>(visitor: PaymentMethodToken._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    paymentCard: (value: PrimerApi.paymentMethod.PaymentCardTokenSchemaPaymentMethodsAPI) => Result;
    paypalBillingAgreement: (value: PrimerApi.payments.PayPalBillingAgreementSchema) => Result;
    gocardlessMandate: (value: PrimerApi.payments.GoCardlessMandateSchema) => Result;
    klarnaCustomerToken: (value: PrimerApi.payments.KlarnaCustomerTokenSchema) => Result;
    apayaCustomerToken: (value: PrimerApi.payments.ApayaCustomerTokenSchema) => Result;
    _other: (value: { paymentMethodType: string }) => Result;
  }
}

export const PaymentMethodToken = {
  paymentCard: (
    value: PrimerApi.paymentMethod.PaymentCardTokenSchemaPaymentMethodsAPI
  ): PaymentMethodToken.PaymentCard => {
    const valueWithoutVisit: Omit<PaymentMethodToken.PaymentCard, "_visit"> = {
      ...value,
      paymentMethodType: "PAYMENT_CARD",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as PaymentMethodToken.PaymentCard;
    castedValue._visit = (visitor) => visitor.paymentCard(value);
    return castedValue;
  },

  paypalBillingAgreement: (
    value: PrimerApi.payments.PayPalBillingAgreementSchema
  ): PaymentMethodToken.PaypalBillingAgreement => {
    const valueWithoutVisit: Omit<PaymentMethodToken.PaypalBillingAgreement, "_visit"> = {
      ...value,
      paymentMethodType: "PAYPAL_BILLING_AGREEMENT",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as PaymentMethodToken.PaypalBillingAgreement;
    castedValue._visit = (visitor) => visitor.paypalBillingAgreement(value);
    return castedValue;
  },

  gocardlessMandate: (value: PrimerApi.payments.GoCardlessMandateSchema): PaymentMethodToken.GocardlessMandate => {
    const valueWithoutVisit: Omit<PaymentMethodToken.GocardlessMandate, "_visit"> = {
      ...value,
      paymentMethodType: "GOCARDLESS_MANDATE",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as PaymentMethodToken.GocardlessMandate;
    castedValue._visit = (visitor) => visitor.gocardlessMandate(value);
    return castedValue;
  },

  klarnaCustomerToken: (
    value: PrimerApi.payments.KlarnaCustomerTokenSchema
  ): PaymentMethodToken.KlarnaCustomerToken => {
    const valueWithoutVisit: Omit<PaymentMethodToken.KlarnaCustomerToken, "_visit"> = {
      ...value,
      paymentMethodType: "KLARNA_CUSTOMER_TOKEN",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as PaymentMethodToken.KlarnaCustomerToken;
    castedValue._visit = (visitor) => visitor.klarnaCustomerToken(value);
    return castedValue;
  },

  apayaCustomerToken: (value: PrimerApi.payments.ApayaCustomerTokenSchema): PaymentMethodToken.ApayaCustomerToken => {
    const valueWithoutVisit: Omit<PaymentMethodToken.ApayaCustomerToken, "_visit"> = {
      ...value,
      paymentMethodType: "APAYA_CUSTOMER_TOKEN",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as PaymentMethodToken.ApayaCustomerToken;
    castedValue._visit = (visitor) => visitor.apayaCustomerToken(value);
    return castedValue;
  },
} as const;
