/**
 * This file auto-generated by Fern from our API Definition.
 */

/**
 * Supported currencies.
 */
export interface CurrencyCode<RawValue extends CurrencyCode.RawValue = CurrencyCode.RawValue> {
  value: RawValue;
  visit: <Result>(visitor: CurrencyCode._Visitor<Result>) => Result;
}

const _Aed: CurrencyCode<"AED"> = {
  value: "AED",
  visit: (visitor) => visitor.aed(),
};
const _Afn: CurrencyCode<"AFN"> = {
  value: "AFN",
  visit: (visitor) => visitor.afn(),
};
const _All: CurrencyCode<"ALL"> = {
  value: "ALL",
  visit: (visitor) => visitor.all(),
};
const _Amd: CurrencyCode<"AMD"> = {
  value: "AMD",
  visit: (visitor) => visitor.amd(),
};
const _Ang: CurrencyCode<"ANG"> = {
  value: "ANG",
  visit: (visitor) => visitor.ang(),
};
const _Aoa: CurrencyCode<"AOA"> = {
  value: "AOA",
  visit: (visitor) => visitor.aoa(),
};
const _Ars: CurrencyCode<"ARS"> = {
  value: "ARS",
  visit: (visitor) => visitor.ars(),
};
const _Aud: CurrencyCode<"AUD"> = {
  value: "AUD",
  visit: (visitor) => visitor.aud(),
};
const _Awg: CurrencyCode<"AWG"> = {
  value: "AWG",
  visit: (visitor) => visitor.awg(),
};
const _Azn: CurrencyCode<"AZN"> = {
  value: "AZN",
  visit: (visitor) => visitor.azn(),
};
const _Bam: CurrencyCode<"BAM"> = {
  value: "BAM",
  visit: (visitor) => visitor.bam(),
};
const _Bbd: CurrencyCode<"BBD"> = {
  value: "BBD",
  visit: (visitor) => visitor.bbd(),
};
const _Bdt: CurrencyCode<"BDT"> = {
  value: "BDT",
  visit: (visitor) => visitor.bdt(),
};
const _Bgn: CurrencyCode<"BGN"> = {
  value: "BGN",
  visit: (visitor) => visitor.bgn(),
};
const _Bhd: CurrencyCode<"BHD"> = {
  value: "BHD",
  visit: (visitor) => visitor.bhd(),
};
const _Bif: CurrencyCode<"BIF"> = {
  value: "BIF",
  visit: (visitor) => visitor.bif(),
};
const _Bmd: CurrencyCode<"BMD"> = {
  value: "BMD",
  visit: (visitor) => visitor.bmd(),
};
const _Bnd: CurrencyCode<"BND"> = {
  value: "BND",
  visit: (visitor) => visitor.bnd(),
};
const _Bob: CurrencyCode<"BOB"> = {
  value: "BOB",
  visit: (visitor) => visitor.bob(),
};
const _Bov: CurrencyCode<"BOV"> = {
  value: "BOV",
  visit: (visitor) => visitor.bov(),
};
const _Brl: CurrencyCode<"BRL"> = {
  value: "BRL",
  visit: (visitor) => visitor.brl(),
};
const _Bsd: CurrencyCode<"BSD"> = {
  value: "BSD",
  visit: (visitor) => visitor.bsd(),
};
const _Btn: CurrencyCode<"BTN"> = {
  value: "BTN",
  visit: (visitor) => visitor.btn(),
};
const _Bwp: CurrencyCode<"BWP"> = {
  value: "BWP",
  visit: (visitor) => visitor.bwp(),
};
const _Byr: CurrencyCode<"BYR"> = {
  value: "BYR",
  visit: (visitor) => visitor.byr(),
};
const _Byn: CurrencyCode<"BYN"> = {
  value: "BYN",
  visit: (visitor) => visitor.byn(),
};
const _Bzd: CurrencyCode<"BZD"> = {
  value: "BZD",
  visit: (visitor) => visitor.bzd(),
};
const _Cad: CurrencyCode<"CAD"> = {
  value: "CAD",
  visit: (visitor) => visitor.cad(),
};
const _Cdf: CurrencyCode<"CDF"> = {
  value: "CDF",
  visit: (visitor) => visitor.cdf(),
};
const _Che: CurrencyCode<"CHE"> = {
  value: "CHE",
  visit: (visitor) => visitor.che(),
};
const _Chf: CurrencyCode<"CHF"> = {
  value: "CHF",
  visit: (visitor) => visitor.chf(),
};
const _Chw: CurrencyCode<"CHW"> = {
  value: "CHW",
  visit: (visitor) => visitor.chw(),
};
const _Clf: CurrencyCode<"CLF"> = {
  value: "CLF",
  visit: (visitor) => visitor.clf(),
};
const _Clp: CurrencyCode<"CLP"> = {
  value: "CLP",
  visit: (visitor) => visitor.clp(),
};
const _Cny: CurrencyCode<"CNY"> = {
  value: "CNY",
  visit: (visitor) => visitor.cny(),
};
const _Cop: CurrencyCode<"COP"> = {
  value: "COP",
  visit: (visitor) => visitor.cop(),
};
const _Cou: CurrencyCode<"COU"> = {
  value: "COU",
  visit: (visitor) => visitor.cou(),
};
const _Crc: CurrencyCode<"CRC"> = {
  value: "CRC",
  visit: (visitor) => visitor.crc(),
};
const _Cuc: CurrencyCode<"CUC"> = {
  value: "CUC",
  visit: (visitor) => visitor.cuc(),
};
const _Cup: CurrencyCode<"CUP"> = {
  value: "CUP",
  visit: (visitor) => visitor.cup(),
};
const _Cve: CurrencyCode<"CVE"> = {
  value: "CVE",
  visit: (visitor) => visitor.cve(),
};
const _Czk: CurrencyCode<"CZK"> = {
  value: "CZK",
  visit: (visitor) => visitor.czk(),
};
const _Djf: CurrencyCode<"DJF"> = {
  value: "DJF",
  visit: (visitor) => visitor.djf(),
};
const _Dkk: CurrencyCode<"DKK"> = {
  value: "DKK",
  visit: (visitor) => visitor.dkk(),
};
const _Dop: CurrencyCode<"DOP"> = {
  value: "DOP",
  visit: (visitor) => visitor.dop(),
};
const _Dzd: CurrencyCode<"DZD"> = {
  value: "DZD",
  visit: (visitor) => visitor.dzd(),
};
const _Egp: CurrencyCode<"EGP"> = {
  value: "EGP",
  visit: (visitor) => visitor.egp(),
};
const _Ern: CurrencyCode<"ERN"> = {
  value: "ERN",
  visit: (visitor) => visitor.ern(),
};
const _Etb: CurrencyCode<"ETB"> = {
  value: "ETB",
  visit: (visitor) => visitor.etb(),
};
const _Eur: CurrencyCode<"EUR"> = {
  value: "EUR",
  visit: (visitor) => visitor.eur(),
};
const _Fjd: CurrencyCode<"FJD"> = {
  value: "FJD",
  visit: (visitor) => visitor.fjd(),
};
const _Fkp: CurrencyCode<"FKP"> = {
  value: "FKP",
  visit: (visitor) => visitor.fkp(),
};
const _Gbp: CurrencyCode<"GBP"> = {
  value: "GBP",
  visit: (visitor) => visitor.gbp(),
};
const _Gel: CurrencyCode<"GEL"> = {
  value: "GEL",
  visit: (visitor) => visitor.gel(),
};
const _Ghs: CurrencyCode<"GHS"> = {
  value: "GHS",
  visit: (visitor) => visitor.ghs(),
};
const _Gip: CurrencyCode<"GIP"> = {
  value: "GIP",
  visit: (visitor) => visitor.gip(),
};
const _Gmd: CurrencyCode<"GMD"> = {
  value: "GMD",
  visit: (visitor) => visitor.gmd(),
};
const _Gnf: CurrencyCode<"GNF"> = {
  value: "GNF",
  visit: (visitor) => visitor.gnf(),
};
const _Gtq: CurrencyCode<"GTQ"> = {
  value: "GTQ",
  visit: (visitor) => visitor.gtq(),
};
const _Gyd: CurrencyCode<"GYD"> = {
  value: "GYD",
  visit: (visitor) => visitor.gyd(),
};
const _Hkd: CurrencyCode<"HKD"> = {
  value: "HKD",
  visit: (visitor) => visitor.hkd(),
};
const _Hnl: CurrencyCode<"HNL"> = {
  value: "HNL",
  visit: (visitor) => visitor.hnl(),
};
const _Hrk: CurrencyCode<"HRK"> = {
  value: "HRK",
  visit: (visitor) => visitor.hrk(),
};
const _Htg: CurrencyCode<"HTG"> = {
  value: "HTG",
  visit: (visitor) => visitor.htg(),
};
const _Huf: CurrencyCode<"HUF"> = {
  value: "HUF",
  visit: (visitor) => visitor.huf(),
};
const _Idr: CurrencyCode<"IDR"> = {
  value: "IDR",
  visit: (visitor) => visitor.idr(),
};
const _Ils: CurrencyCode<"ILS"> = {
  value: "ILS",
  visit: (visitor) => visitor.ils(),
};
const _Inr: CurrencyCode<"INR"> = {
  value: "INR",
  visit: (visitor) => visitor.inr(),
};
const _Iqd: CurrencyCode<"IQD"> = {
  value: "IQD",
  visit: (visitor) => visitor.iqd(),
};
const _Irr: CurrencyCode<"IRR"> = {
  value: "IRR",
  visit: (visitor) => visitor.irr(),
};
const _Isk: CurrencyCode<"ISK"> = {
  value: "ISK",
  visit: (visitor) => visitor.isk(),
};
const _Jmd: CurrencyCode<"JMD"> = {
  value: "JMD",
  visit: (visitor) => visitor.jmd(),
};
const _Jod: CurrencyCode<"JOD"> = {
  value: "JOD",
  visit: (visitor) => visitor.jod(),
};
const _Jpy: CurrencyCode<"JPY"> = {
  value: "JPY",
  visit: (visitor) => visitor.jpy(),
};
const _Kes: CurrencyCode<"KES"> = {
  value: "KES",
  visit: (visitor) => visitor.kes(),
};
const _Kgs: CurrencyCode<"KGS"> = {
  value: "KGS",
  visit: (visitor) => visitor.kgs(),
};
const _Khr: CurrencyCode<"KHR"> = {
  value: "KHR",
  visit: (visitor) => visitor.khr(),
};
const _Kmf: CurrencyCode<"KMF"> = {
  value: "KMF",
  visit: (visitor) => visitor.kmf(),
};
const _Kpw: CurrencyCode<"KPW"> = {
  value: "KPW",
  visit: (visitor) => visitor.kpw(),
};
const _Krw: CurrencyCode<"KRW"> = {
  value: "KRW",
  visit: (visitor) => visitor.krw(),
};
const _Kwd: CurrencyCode<"KWD"> = {
  value: "KWD",
  visit: (visitor) => visitor.kwd(),
};
const _Kyd: CurrencyCode<"KYD"> = {
  value: "KYD",
  visit: (visitor) => visitor.kyd(),
};
const _Kzt: CurrencyCode<"KZT"> = {
  value: "KZT",
  visit: (visitor) => visitor.kzt(),
};
const _Lak: CurrencyCode<"LAK"> = {
  value: "LAK",
  visit: (visitor) => visitor.lak(),
};
const _Lbp: CurrencyCode<"LBP"> = {
  value: "LBP",
  visit: (visitor) => visitor.lbp(),
};
const _Lkr: CurrencyCode<"LKR"> = {
  value: "LKR",
  visit: (visitor) => visitor.lkr(),
};
const _Lrd: CurrencyCode<"LRD"> = {
  value: "LRD",
  visit: (visitor) => visitor.lrd(),
};
const _Lsl: CurrencyCode<"LSL"> = {
  value: "LSL",
  visit: (visitor) => visitor.lsl(),
};
const _Ltl: CurrencyCode<"LTL"> = {
  value: "LTL",
  visit: (visitor) => visitor.ltl(),
};
const _Lvl: CurrencyCode<"LVL"> = {
  value: "LVL",
  visit: (visitor) => visitor.lvl(),
};
const _Lyd: CurrencyCode<"LYD"> = {
  value: "LYD",
  visit: (visitor) => visitor.lyd(),
};
const _Mad: CurrencyCode<"MAD"> = {
  value: "MAD",
  visit: (visitor) => visitor.mad(),
};
const _Mdl: CurrencyCode<"MDL"> = {
  value: "MDL",
  visit: (visitor) => visitor.mdl(),
};
const _Mga: CurrencyCode<"MGA"> = {
  value: "MGA",
  visit: (visitor) => visitor.mga(),
};
const _Mkd: CurrencyCode<"MKD"> = {
  value: "MKD",
  visit: (visitor) => visitor.mkd(),
};
const _Mmk: CurrencyCode<"MMK"> = {
  value: "MMK",
  visit: (visitor) => visitor.mmk(),
};
const _Mnt: CurrencyCode<"MNT"> = {
  value: "MNT",
  visit: (visitor) => visitor.mnt(),
};
const _Mop: CurrencyCode<"MOP"> = {
  value: "MOP",
  visit: (visitor) => visitor.mop(),
};
const _Mro: CurrencyCode<"MRO"> = {
  value: "MRO",
  visit: (visitor) => visitor.mro(),
};
const _Mur: CurrencyCode<"MUR"> = {
  value: "MUR",
  visit: (visitor) => visitor.mur(),
};
const _Mvr: CurrencyCode<"MVR"> = {
  value: "MVR",
  visit: (visitor) => visitor.mvr(),
};
const _Mwk: CurrencyCode<"MWK"> = {
  value: "MWK",
  visit: (visitor) => visitor.mwk(),
};
const _Mxn: CurrencyCode<"MXN"> = {
  value: "MXN",
  visit: (visitor) => visitor.mxn(),
};
const _Mxv: CurrencyCode<"MXV"> = {
  value: "MXV",
  visit: (visitor) => visitor.mxv(),
};
const _Myr: CurrencyCode<"MYR"> = {
  value: "MYR",
  visit: (visitor) => visitor.myr(),
};
const _Mzn: CurrencyCode<"MZN"> = {
  value: "MZN",
  visit: (visitor) => visitor.mzn(),
};
const _Nad: CurrencyCode<"NAD"> = {
  value: "NAD",
  visit: (visitor) => visitor.nad(),
};
const _Ngn: CurrencyCode<"NGN"> = {
  value: "NGN",
  visit: (visitor) => visitor.ngn(),
};
const _Nio: CurrencyCode<"NIO"> = {
  value: "NIO",
  visit: (visitor) => visitor.nio(),
};
const _Nok: CurrencyCode<"NOK"> = {
  value: "NOK",
  visit: (visitor) => visitor.nok(),
};
const _Npr: CurrencyCode<"NPR"> = {
  value: "NPR",
  visit: (visitor) => visitor.npr(),
};
const _Nzd: CurrencyCode<"NZD"> = {
  value: "NZD",
  visit: (visitor) => visitor.nzd(),
};
const _Omr: CurrencyCode<"OMR"> = {
  value: "OMR",
  visit: (visitor) => visitor.omr(),
};
const _Pab: CurrencyCode<"PAB"> = {
  value: "PAB",
  visit: (visitor) => visitor.pab(),
};
const _Pen: CurrencyCode<"PEN"> = {
  value: "PEN",
  visit: (visitor) => visitor.pen(),
};
const _Pgk: CurrencyCode<"PGK"> = {
  value: "PGK",
  visit: (visitor) => visitor.pgk(),
};
const _Php: CurrencyCode<"PHP"> = {
  value: "PHP",
  visit: (visitor) => visitor.php(),
};
const _Pkr: CurrencyCode<"PKR"> = {
  value: "PKR",
  visit: (visitor) => visitor.pkr(),
};
const _Pln: CurrencyCode<"PLN"> = {
  value: "PLN",
  visit: (visitor) => visitor.pln(),
};
const _Pyg: CurrencyCode<"PYG"> = {
  value: "PYG",
  visit: (visitor) => visitor.pyg(),
};
const _Qar: CurrencyCode<"QAR"> = {
  value: "QAR",
  visit: (visitor) => visitor.qar(),
};
const _Ron: CurrencyCode<"RON"> = {
  value: "RON",
  visit: (visitor) => visitor.ron(),
};
const _Rsd: CurrencyCode<"RSD"> = {
  value: "RSD",
  visit: (visitor) => visitor.rsd(),
};
const _Rub: CurrencyCode<"RUB"> = {
  value: "RUB",
  visit: (visitor) => visitor.rub(),
};
const _Rwf: CurrencyCode<"RWF"> = {
  value: "RWF",
  visit: (visitor) => visitor.rwf(),
};
const _Sar: CurrencyCode<"SAR"> = {
  value: "SAR",
  visit: (visitor) => visitor.sar(),
};
const _Sbd: CurrencyCode<"SBD"> = {
  value: "SBD",
  visit: (visitor) => visitor.sbd(),
};
const _Scr: CurrencyCode<"SCR"> = {
  value: "SCR",
  visit: (visitor) => visitor.scr(),
};
const _Sdg: CurrencyCode<"SDG"> = {
  value: "SDG",
  visit: (visitor) => visitor.sdg(),
};
const _Sek: CurrencyCode<"SEK"> = {
  value: "SEK",
  visit: (visitor) => visitor.sek(),
};
const _Sgd: CurrencyCode<"SGD"> = {
  value: "SGD",
  visit: (visitor) => visitor.sgd(),
};
const _Shp: CurrencyCode<"SHP"> = {
  value: "SHP",
  visit: (visitor) => visitor.shp(),
};
const _Sll: CurrencyCode<"SLL"> = {
  value: "SLL",
  visit: (visitor) => visitor.sll(),
};
const _Sos: CurrencyCode<"SOS"> = {
  value: "SOS",
  visit: (visitor) => visitor.sos(),
};
const _Srd: CurrencyCode<"SRD"> = {
  value: "SRD",
  visit: (visitor) => visitor.srd(),
};
const _Ssp: CurrencyCode<"SSP"> = {
  value: "SSP",
  visit: (visitor) => visitor.ssp(),
};
const _Std: CurrencyCode<"STD"> = {
  value: "STD",
  visit: (visitor) => visitor.std(),
};
const _Svc: CurrencyCode<"SVC"> = {
  value: "SVC",
  visit: (visitor) => visitor.svc(),
};
const _Syp: CurrencyCode<"SYP"> = {
  value: "SYP",
  visit: (visitor) => visitor.syp(),
};
const _Szl: CurrencyCode<"SZL"> = {
  value: "SZL",
  visit: (visitor) => visitor.szl(),
};
const _Thb: CurrencyCode<"THB"> = {
  value: "THB",
  visit: (visitor) => visitor.thb(),
};
const _Tjs: CurrencyCode<"TJS"> = {
  value: "TJS",
  visit: (visitor) => visitor.tjs(),
};
const _Tmt: CurrencyCode<"TMT"> = {
  value: "TMT",
  visit: (visitor) => visitor.tmt(),
};
const _Tnd: CurrencyCode<"TND"> = {
  value: "TND",
  visit: (visitor) => visitor.tnd(),
};
const _Top: CurrencyCode<"TOP"> = {
  value: "TOP",
  visit: (visitor) => visitor.top(),
};
const _Try: CurrencyCode<"TRY"> = {
  value: "TRY",
  visit: (visitor) => visitor.try(),
};
const _Ttd: CurrencyCode<"TTD"> = {
  value: "TTD",
  visit: (visitor) => visitor.ttd(),
};
const _Twd: CurrencyCode<"TWD"> = {
  value: "TWD",
  visit: (visitor) => visitor.twd(),
};
const _Tzs: CurrencyCode<"TZS"> = {
  value: "TZS",
  visit: (visitor) => visitor.tzs(),
};
const _Uah: CurrencyCode<"UAH"> = {
  value: "UAH",
  visit: (visitor) => visitor.uah(),
};
const _Ugx: CurrencyCode<"UGX"> = {
  value: "UGX",
  visit: (visitor) => visitor.ugx(),
};
const _Usd: CurrencyCode<"USD"> = {
  value: "USD",
  visit: (visitor) => visitor.usd(),
};
const _Usn: CurrencyCode<"USN"> = {
  value: "USN",
  visit: (visitor) => visitor.usn(),
};
const _Uss: CurrencyCode<"USS"> = {
  value: "USS",
  visit: (visitor) => visitor.uss(),
};
const _Uyi: CurrencyCode<"UYI"> = {
  value: "UYI",
  visit: (visitor) => visitor.uyi(),
};
const _Uyu: CurrencyCode<"UYU"> = {
  value: "UYU",
  visit: (visitor) => visitor.uyu(),
};
const _Uzs: CurrencyCode<"UZS"> = {
  value: "UZS",
  visit: (visitor) => visitor.uzs(),
};
const _Vef: CurrencyCode<"VEF"> = {
  value: "VEF",
  visit: (visitor) => visitor.vef(),
};
const _Vnd: CurrencyCode<"VND"> = {
  value: "VND",
  visit: (visitor) => visitor.vnd(),
};
const _Vuv: CurrencyCode<"VUV"> = {
  value: "VUV",
  visit: (visitor) => visitor.vuv(),
};
const _Wst: CurrencyCode<"WST"> = {
  value: "WST",
  visit: (visitor) => visitor.wst(),
};
const _Xaf: CurrencyCode<"XAF"> = {
  value: "XAF",
  visit: (visitor) => visitor.xaf(),
};
const _Xag: CurrencyCode<"XAG"> = {
  value: "XAG",
  visit: (visitor) => visitor.xag(),
};
const _Xau: CurrencyCode<"XAU"> = {
  value: "XAU",
  visit: (visitor) => visitor.xau(),
};
const _Xba: CurrencyCode<"XBA"> = {
  value: "XBA",
  visit: (visitor) => visitor.xba(),
};
const _Xbb: CurrencyCode<"XBB"> = {
  value: "XBB",
  visit: (visitor) => visitor.xbb(),
};
const _Xbc: CurrencyCode<"XBC"> = {
  value: "XBC",
  visit: (visitor) => visitor.xbc(),
};
const _Xbd: CurrencyCode<"XBD"> = {
  value: "XBD",
  visit: (visitor) => visitor.xbd(),
};
const _Xcd: CurrencyCode<"XCD"> = {
  value: "XCD",
  visit: (visitor) => visitor.xcd(),
};
const _Xdr: CurrencyCode<"XDR"> = {
  value: "XDR",
  visit: (visitor) => visitor.xdr(),
};
const _Xfu: CurrencyCode<"XFU"> = {
  value: "XFU",
  visit: (visitor) => visitor.xfu(),
};
const _Xof: CurrencyCode<"XOF"> = {
  value: "XOF",
  visit: (visitor) => visitor.xof(),
};
const _Xpd: CurrencyCode<"XPD"> = {
  value: "XPD",
  visit: (visitor) => visitor.xpd(),
};
const _Xpf: CurrencyCode<"XPF"> = {
  value: "XPF",
  visit: (visitor) => visitor.xpf(),
};
const _Xpt: CurrencyCode<"XPT"> = {
  value: "XPT",
  visit: (visitor) => visitor.xpt(),
};
const _Xsu: CurrencyCode<"XSU"> = {
  value: "XSU",
  visit: (visitor) => visitor.xsu(),
};
const _Xts: CurrencyCode<"XTS"> = {
  value: "XTS",
  visit: (visitor) => visitor.xts(),
};
const _Xua: CurrencyCode<"XUA"> = {
  value: "XUA",
  visit: (visitor) => visitor.xua(),
};
const _Yer: CurrencyCode<"YER"> = {
  value: "YER",
  visit: (visitor) => visitor.yer(),
};
const _Zar: CurrencyCode<"ZAR"> = {
  value: "ZAR",
  visit: (visitor) => visitor.zar(),
};
const _Zmw: CurrencyCode<"ZMW"> = {
  value: "ZMW",
  visit: (visitor) => visitor.zmw(),
};
const _Zwl: CurrencyCode<"ZWL"> = {
  value: "ZWL",
  visit: (visitor) => visitor.zwl(),
};
export const CurrencyCode = {
  Aed: _Aed,
  Afn: _Afn,
  All: _All,
  Amd: _Amd,
  Ang: _Ang,
  Aoa: _Aoa,
  Ars: _Ars,
  Aud: _Aud,
  Awg: _Awg,
  Azn: _Azn,
  Bam: _Bam,
  Bbd: _Bbd,
  Bdt: _Bdt,
  Bgn: _Bgn,
  Bhd: _Bhd,
  Bif: _Bif,
  Bmd: _Bmd,
  Bnd: _Bnd,
  Bob: _Bob,
  Bov: _Bov,
  Brl: _Brl,
  Bsd: _Bsd,
  Btn: _Btn,
  Bwp: _Bwp,
  Byr: _Byr,
  Byn: _Byn,
  Bzd: _Bzd,
  Cad: _Cad,
  Cdf: _Cdf,
  Che: _Che,
  Chf: _Chf,
  Chw: _Chw,
  Clf: _Clf,
  Clp: _Clp,
  Cny: _Cny,
  Cop: _Cop,
  Cou: _Cou,
  Crc: _Crc,
  Cuc: _Cuc,
  Cup: _Cup,
  Cve: _Cve,
  Czk: _Czk,
  Djf: _Djf,
  Dkk: _Dkk,
  Dop: _Dop,
  Dzd: _Dzd,
  Egp: _Egp,
  Ern: _Ern,
  Etb: _Etb,
  Eur: _Eur,
  Fjd: _Fjd,
  Fkp: _Fkp,
  Gbp: _Gbp,
  Gel: _Gel,
  Ghs: _Ghs,
  Gip: _Gip,
  Gmd: _Gmd,
  Gnf: _Gnf,
  Gtq: _Gtq,
  Gyd: _Gyd,
  Hkd: _Hkd,
  Hnl: _Hnl,
  Hrk: _Hrk,
  Htg: _Htg,
  Huf: _Huf,
  Idr: _Idr,
  Ils: _Ils,
  Inr: _Inr,
  Iqd: _Iqd,
  Irr: _Irr,
  Isk: _Isk,
  Jmd: _Jmd,
  Jod: _Jod,
  Jpy: _Jpy,
  Kes: _Kes,
  Kgs: _Kgs,
  Khr: _Khr,
  Kmf: _Kmf,
  Kpw: _Kpw,
  Krw: _Krw,
  Kwd: _Kwd,
  Kyd: _Kyd,
  Kzt: _Kzt,
  Lak: _Lak,
  Lbp: _Lbp,
  Lkr: _Lkr,
  Lrd: _Lrd,
  Lsl: _Lsl,
  Ltl: _Ltl,
  Lvl: _Lvl,
  Lyd: _Lyd,
  Mad: _Mad,
  Mdl: _Mdl,
  Mga: _Mga,
  Mkd: _Mkd,
  Mmk: _Mmk,
  Mnt: _Mnt,
  Mop: _Mop,
  Mro: _Mro,
  Mur: _Mur,
  Mvr: _Mvr,
  Mwk: _Mwk,
  Mxn: _Mxn,
  Mxv: _Mxv,
  Myr: _Myr,
  Mzn: _Mzn,
  Nad: _Nad,
  Ngn: _Ngn,
  Nio: _Nio,
  Nok: _Nok,
  Npr: _Npr,
  Nzd: _Nzd,
  Omr: _Omr,
  Pab: _Pab,
  Pen: _Pen,
  Pgk: _Pgk,
  Php: _Php,
  Pkr: _Pkr,
  Pln: _Pln,
  Pyg: _Pyg,
  Qar: _Qar,
  Ron: _Ron,
  Rsd: _Rsd,
  Rub: _Rub,
  Rwf: _Rwf,
  Sar: _Sar,
  Sbd: _Sbd,
  Scr: _Scr,
  Sdg: _Sdg,
  Sek: _Sek,
  Sgd: _Sgd,
  Shp: _Shp,
  Sll: _Sll,
  Sos: _Sos,
  Srd: _Srd,
  Ssp: _Ssp,
  Std: _Std,
  Svc: _Svc,
  Syp: _Syp,
  Szl: _Szl,
  Thb: _Thb,
  Tjs: _Tjs,
  Tmt: _Tmt,
  Tnd: _Tnd,
  Top: _Top,
  Try: _Try,
  Ttd: _Ttd,
  Twd: _Twd,
  Tzs: _Tzs,
  Uah: _Uah,
  Ugx: _Ugx,
  Usd: _Usd,
  Usn: _Usn,
  Uss: _Uss,
  Uyi: _Uyi,
  Uyu: _Uyu,
  Uzs: _Uzs,
  Vef: _Vef,
  Vnd: _Vnd,
  Vuv: _Vuv,
  Wst: _Wst,
  Xaf: _Xaf,
  Xag: _Xag,
  Xau: _Xau,
  Xba: _Xba,
  Xbb: _Xbb,
  Xbc: _Xbc,
  Xbd: _Xbd,
  Xcd: _Xcd,
  Xdr: _Xdr,
  Xfu: _Xfu,
  Xof: _Xof,
  Xpd: _Xpd,
  Xpf: _Xpf,
  Xpt: _Xpt,
  Xsu: _Xsu,
  Xts: _Xts,
  Xua: _Xua,
  Yer: _Yer,
  Zar: _Zar,
  Zmw: _Zmw,
  Zwl: _Zwl,
} as const;

export declare namespace CurrencyCode {
  type RawValue =
    | "AED"
    | "AFN"
    | "ALL"
    | "AMD"
    | "ANG"
    | "AOA"
    | "ARS"
    | "AUD"
    | "AWG"
    | "AZN"
    | "BAM"
    | "BBD"
    | "BDT"
    | "BGN"
    | "BHD"
    | "BIF"
    | "BMD"
    | "BND"
    | "BOB"
    | "BOV"
    | "BRL"
    | "BSD"
    | "BTN"
    | "BWP"
    | "BYR"
    | "BYN"
    | "BZD"
    | "CAD"
    | "CDF"
    | "CHE"
    | "CHF"
    | "CHW"
    | "CLF"
    | "CLP"
    | "CNY"
    | "COP"
    | "COU"
    | "CRC"
    | "CUC"
    | "CUP"
    | "CVE"
    | "CZK"
    | "DJF"
    | "DKK"
    | "DOP"
    | "DZD"
    | "EGP"
    | "ERN"
    | "ETB"
    | "EUR"
    | "FJD"
    | "FKP"
    | "GBP"
    | "GEL"
    | "GHS"
    | "GIP"
    | "GMD"
    | "GNF"
    | "GTQ"
    | "GYD"
    | "HKD"
    | "HNL"
    | "HRK"
    | "HTG"
    | "HUF"
    | "IDR"
    | "ILS"
    | "INR"
    | "IQD"
    | "IRR"
    | "ISK"
    | "JMD"
    | "JOD"
    | "JPY"
    | "KES"
    | "KGS"
    | "KHR"
    | "KMF"
    | "KPW"
    | "KRW"
    | "KWD"
    | "KYD"
    | "KZT"
    | "LAK"
    | "LBP"
    | "LKR"
    | "LRD"
    | "LSL"
    | "LTL"
    | "LVL"
    | "LYD"
    | "MAD"
    | "MDL"
    | "MGA"
    | "MKD"
    | "MMK"
    | "MNT"
    | "MOP"
    | "MRO"
    | "MUR"
    | "MVR"
    | "MWK"
    | "MXN"
    | "MXV"
    | "MYR"
    | "MZN"
    | "NAD"
    | "NGN"
    | "NIO"
    | "NOK"
    | "NPR"
    | "NZD"
    | "OMR"
    | "PAB"
    | "PEN"
    | "PGK"
    | "PHP"
    | "PKR"
    | "PLN"
    | "PYG"
    | "QAR"
    | "RON"
    | "RSD"
    | "RUB"
    | "RWF"
    | "SAR"
    | "SBD"
    | "SCR"
    | "SDG"
    | "SEK"
    | "SGD"
    | "SHP"
    | "SLL"
    | "SOS"
    | "SRD"
    | "SSP"
    | "STD"
    | "SVC"
    | "SYP"
    | "SZL"
    | "THB"
    | "TJS"
    | "TMT"
    | "TND"
    | "TOP"
    | "TRY"
    | "TTD"
    | "TWD"
    | "TZS"
    | "UAH"
    | "UGX"
    | "USD"
    | "USN"
    | "USS"
    | "UYI"
    | "UYU"
    | "UZS"
    | "VEF"
    | "VND"
    | "VUV"
    | "WST"
    | "XAF"
    | "XAG"
    | "XAU"
    | "XBA"
    | "XBB"
    | "XBC"
    | "XBD"
    | "XCD"
    | "XDR"
    | "XFU"
    | "XOF"
    | "XPD"
    | "XPF"
    | "XPT"
    | "XSU"
    | "XTS"
    | "XUA"
    | "YER"
    | "ZAR"
    | "ZMW"
    | "ZWL"
    | string;

  interface _Visitor<Result> {
    aed: () => Result;
    afn: () => Result;
    all: () => Result;
    amd: () => Result;
    ang: () => Result;
    aoa: () => Result;
    ars: () => Result;
    aud: () => Result;
    awg: () => Result;
    azn: () => Result;
    bam: () => Result;
    bbd: () => Result;
    bdt: () => Result;
    bgn: () => Result;
    bhd: () => Result;
    bif: () => Result;
    bmd: () => Result;
    bnd: () => Result;
    bob: () => Result;
    bov: () => Result;
    brl: () => Result;
    bsd: () => Result;
    btn: () => Result;
    bwp: () => Result;
    byr: () => Result;
    byn: () => Result;
    bzd: () => Result;
    cad: () => Result;
    cdf: () => Result;
    che: () => Result;
    chf: () => Result;
    chw: () => Result;
    clf: () => Result;
    clp: () => Result;
    cny: () => Result;
    cop: () => Result;
    cou: () => Result;
    crc: () => Result;
    cuc: () => Result;
    cup: () => Result;
    cve: () => Result;
    czk: () => Result;
    djf: () => Result;
    dkk: () => Result;
    dop: () => Result;
    dzd: () => Result;
    egp: () => Result;
    ern: () => Result;
    etb: () => Result;
    eur: () => Result;
    fjd: () => Result;
    fkp: () => Result;
    gbp: () => Result;
    gel: () => Result;
    ghs: () => Result;
    gip: () => Result;
    gmd: () => Result;
    gnf: () => Result;
    gtq: () => Result;
    gyd: () => Result;
    hkd: () => Result;
    hnl: () => Result;
    hrk: () => Result;
    htg: () => Result;
    huf: () => Result;
    idr: () => Result;
    ils: () => Result;
    inr: () => Result;
    iqd: () => Result;
    irr: () => Result;
    isk: () => Result;
    jmd: () => Result;
    jod: () => Result;
    jpy: () => Result;
    kes: () => Result;
    kgs: () => Result;
    khr: () => Result;
    kmf: () => Result;
    kpw: () => Result;
    krw: () => Result;
    kwd: () => Result;
    kyd: () => Result;
    kzt: () => Result;
    lak: () => Result;
    lbp: () => Result;
    lkr: () => Result;
    lrd: () => Result;
    lsl: () => Result;
    ltl: () => Result;
    lvl: () => Result;
    lyd: () => Result;
    mad: () => Result;
    mdl: () => Result;
    mga: () => Result;
    mkd: () => Result;
    mmk: () => Result;
    mnt: () => Result;
    mop: () => Result;
    mro: () => Result;
    mur: () => Result;
    mvr: () => Result;
    mwk: () => Result;
    mxn: () => Result;
    mxv: () => Result;
    myr: () => Result;
    mzn: () => Result;
    nad: () => Result;
    ngn: () => Result;
    nio: () => Result;
    nok: () => Result;
    npr: () => Result;
    nzd: () => Result;
    omr: () => Result;
    pab: () => Result;
    pen: () => Result;
    pgk: () => Result;
    php: () => Result;
    pkr: () => Result;
    pln: () => Result;
    pyg: () => Result;
    qar: () => Result;
    ron: () => Result;
    rsd: () => Result;
    rub: () => Result;
    rwf: () => Result;
    sar: () => Result;
    sbd: () => Result;
    scr: () => Result;
    sdg: () => Result;
    sek: () => Result;
    sgd: () => Result;
    shp: () => Result;
    sll: () => Result;
    sos: () => Result;
    srd: () => Result;
    ssp: () => Result;
    std: () => Result;
    svc: () => Result;
    syp: () => Result;
    szl: () => Result;
    thb: () => Result;
    tjs: () => Result;
    tmt: () => Result;
    tnd: () => Result;
    top: () => Result;
    try: () => Result;
    ttd: () => Result;
    twd: () => Result;
    tzs: () => Result;
    uah: () => Result;
    ugx: () => Result;
    usd: () => Result;
    usn: () => Result;
    uss: () => Result;
    uyi: () => Result;
    uyu: () => Result;
    uzs: () => Result;
    vef: () => Result;
    vnd: () => Result;
    vuv: () => Result;
    wst: () => Result;
    xaf: () => Result;
    xag: () => Result;
    xau: () => Result;
    xba: () => Result;
    xbb: () => Result;
    xbc: () => Result;
    xbd: () => Result;
    xcd: () => Result;
    xdr: () => Result;
    xfu: () => Result;
    xof: () => Result;
    xpd: () => Result;
    xpf: () => Result;
    xpt: () => Result;
    xsu: () => Result;
    xts: () => Result;
    xua: () => Result;
    yer: () => Result;
    zar: () => Result;
    zmw: () => Result;
    zwl: () => Result;
    _other: (value: string) => Result;
  }
}
