/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const CardNetworkType: core.schemas.Schema<CardNetworkType.Raw, PrimerApi.commons.CardNetworkType> = core.schemas
  .string()
  .transform<PrimerApi.commons.CardNetworkType>({
    parse: (value) => PrimerApi.commons.CardNetworkType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace CardNetworkType {
  type Raw = string;
}
