/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const CountryCode: core.schemas.Schema<CountryCode.Raw, PrimerApi.commons.CountryCode> = core.schemas
  .string()
  .transform<PrimerApi.commons.CountryCode>({
    parse: (value) => {
      switch (value) {
        case "AW": {
          return PrimerApi.commons.CountryCode.Aw;
        }
        case "AF": {
          return PrimerApi.commons.CountryCode.Af;
        }
        case "AO": {
          return PrimerApi.commons.CountryCode.Ao;
        }
        case "AI": {
          return PrimerApi.commons.CountryCode.Ai;
        }
        case "AX": {
          return PrimerApi.commons.CountryCode.Ax;
        }
        case "AL": {
          return PrimerApi.commons.CountryCode.Al;
        }
        case "AD": {
          return PrimerApi.commons.CountryCode.Ad;
        }
        case "AE": {
          return PrimerApi.commons.CountryCode.Ae;
        }
        case "AR": {
          return PrimerApi.commons.CountryCode.Ar;
        }
        case "AM": {
          return PrimerApi.commons.CountryCode.Am;
        }
        case "AS": {
          return PrimerApi.commons.CountryCode.As;
        }
        case "AQ": {
          return PrimerApi.commons.CountryCode.Aq;
        }
        case "TF": {
          return PrimerApi.commons.CountryCode.Tf;
        }
        case "AG": {
          return PrimerApi.commons.CountryCode.Ag;
        }
        case "AU": {
          return PrimerApi.commons.CountryCode.Au;
        }
        case "AT": {
          return PrimerApi.commons.CountryCode.At;
        }
        case "AZ": {
          return PrimerApi.commons.CountryCode.Az;
        }
        case "BI": {
          return PrimerApi.commons.CountryCode.Bi;
        }
        case "BE": {
          return PrimerApi.commons.CountryCode.Be;
        }
        case "BJ": {
          return PrimerApi.commons.CountryCode.Bj;
        }
        case "BQ": {
          return PrimerApi.commons.CountryCode.Bq;
        }
        case "BF": {
          return PrimerApi.commons.CountryCode.Bf;
        }
        case "BD": {
          return PrimerApi.commons.CountryCode.Bd;
        }
        case "BG": {
          return PrimerApi.commons.CountryCode.Bg;
        }
        case "BH": {
          return PrimerApi.commons.CountryCode.Bh;
        }
        case "BS": {
          return PrimerApi.commons.CountryCode.Bs;
        }
        case "BA": {
          return PrimerApi.commons.CountryCode.Ba;
        }
        case "BL": {
          return PrimerApi.commons.CountryCode.Bl;
        }
        case "BY": {
          return PrimerApi.commons.CountryCode.By;
        }
        case "BZ": {
          return PrimerApi.commons.CountryCode.Bz;
        }
        case "BM": {
          return PrimerApi.commons.CountryCode.Bm;
        }
        case "BO": {
          return PrimerApi.commons.CountryCode.Bo;
        }
        case "BR": {
          return PrimerApi.commons.CountryCode.Br;
        }
        case "BB": {
          return PrimerApi.commons.CountryCode.Bb;
        }
        case "BN": {
          return PrimerApi.commons.CountryCode.Bn;
        }
        case "BT": {
          return PrimerApi.commons.CountryCode.Bt;
        }
        case "BV": {
          return PrimerApi.commons.CountryCode.Bv;
        }
        case "BW": {
          return PrimerApi.commons.CountryCode.Bw;
        }
        case "CF": {
          return PrimerApi.commons.CountryCode.Cf;
        }
        case "CA": {
          return PrimerApi.commons.CountryCode.Ca;
        }
        case "CC": {
          return PrimerApi.commons.CountryCode.Cc;
        }
        case "CH": {
          return PrimerApi.commons.CountryCode.Ch;
        }
        case "CL": {
          return PrimerApi.commons.CountryCode.Cl;
        }
        case "CN": {
          return PrimerApi.commons.CountryCode.Cn;
        }
        case "CI": {
          return PrimerApi.commons.CountryCode.Ci;
        }
        case "CM": {
          return PrimerApi.commons.CountryCode.Cm;
        }
        case "CD": {
          return PrimerApi.commons.CountryCode.Cd;
        }
        case "CG": {
          return PrimerApi.commons.CountryCode.Cg;
        }
        case "CK": {
          return PrimerApi.commons.CountryCode.Ck;
        }
        case "CO": {
          return PrimerApi.commons.CountryCode.Co;
        }
        case "KM": {
          return PrimerApi.commons.CountryCode.Km;
        }
        case "CV": {
          return PrimerApi.commons.CountryCode.Cv;
        }
        case "CR": {
          return PrimerApi.commons.CountryCode.Cr;
        }
        case "CU": {
          return PrimerApi.commons.CountryCode.Cu;
        }
        case "CW": {
          return PrimerApi.commons.CountryCode.Cw;
        }
        case "CX": {
          return PrimerApi.commons.CountryCode.Cx;
        }
        case "KY": {
          return PrimerApi.commons.CountryCode.Ky;
        }
        case "CY": {
          return PrimerApi.commons.CountryCode.Cy;
        }
        case "CZ": {
          return PrimerApi.commons.CountryCode.Cz;
        }
        case "DE": {
          return PrimerApi.commons.CountryCode.De;
        }
        case "DJ": {
          return PrimerApi.commons.CountryCode.Dj;
        }
        case "DM": {
          return PrimerApi.commons.CountryCode.Dm;
        }
        case "DK": {
          return PrimerApi.commons.CountryCode.Dk;
        }
        case "DO": {
          return PrimerApi.commons.CountryCode.Do;
        }
        case "DZ": {
          return PrimerApi.commons.CountryCode.Dz;
        }
        case "EC": {
          return PrimerApi.commons.CountryCode.Ec;
        }
        case "EG": {
          return PrimerApi.commons.CountryCode.Eg;
        }
        case "ER": {
          return PrimerApi.commons.CountryCode.Er;
        }
        case "EH": {
          return PrimerApi.commons.CountryCode.Eh;
        }
        case "ES": {
          return PrimerApi.commons.CountryCode.Es;
        }
        case "EE": {
          return PrimerApi.commons.CountryCode.Ee;
        }
        case "ET": {
          return PrimerApi.commons.CountryCode.Et;
        }
        case "FI": {
          return PrimerApi.commons.CountryCode.Fi;
        }
        case "FJ": {
          return PrimerApi.commons.CountryCode.Fj;
        }
        case "FK": {
          return PrimerApi.commons.CountryCode.Fk;
        }
        case "FR": {
          return PrimerApi.commons.CountryCode.Fr;
        }
        case "FO": {
          return PrimerApi.commons.CountryCode.Fo;
        }
        case "FM": {
          return PrimerApi.commons.CountryCode.Fm;
        }
        case "GA": {
          return PrimerApi.commons.CountryCode.Ga;
        }
        case "GB": {
          return PrimerApi.commons.CountryCode.Gb;
        }
        case "GE": {
          return PrimerApi.commons.CountryCode.Ge;
        }
        case "GG": {
          return PrimerApi.commons.CountryCode.Gg;
        }
        case "GH": {
          return PrimerApi.commons.CountryCode.Gh;
        }
        case "GI": {
          return PrimerApi.commons.CountryCode.Gi;
        }
        case "GN": {
          return PrimerApi.commons.CountryCode.Gn;
        }
        case "GP": {
          return PrimerApi.commons.CountryCode.Gp;
        }
        case "GM": {
          return PrimerApi.commons.CountryCode.Gm;
        }
        case "GW": {
          return PrimerApi.commons.CountryCode.Gw;
        }
        case "GQ": {
          return PrimerApi.commons.CountryCode.Gq;
        }
        case "GR": {
          return PrimerApi.commons.CountryCode.Gr;
        }
        case "GD": {
          return PrimerApi.commons.CountryCode.Gd;
        }
        case "GL": {
          return PrimerApi.commons.CountryCode.Gl;
        }
        case "GT": {
          return PrimerApi.commons.CountryCode.Gt;
        }
        case "GF": {
          return PrimerApi.commons.CountryCode.Gf;
        }
        case "GU": {
          return PrimerApi.commons.CountryCode.Gu;
        }
        case "GY": {
          return PrimerApi.commons.CountryCode.Gy;
        }
        case "HK": {
          return PrimerApi.commons.CountryCode.Hk;
        }
        case "HM": {
          return PrimerApi.commons.CountryCode.Hm;
        }
        case "HN": {
          return PrimerApi.commons.CountryCode.Hn;
        }
        case "HR": {
          return PrimerApi.commons.CountryCode.Hr;
        }
        case "HT": {
          return PrimerApi.commons.CountryCode.Ht;
        }
        case "HU": {
          return PrimerApi.commons.CountryCode.Hu;
        }
        case "ID": {
          return PrimerApi.commons.CountryCode.Id;
        }
        case "IM": {
          return PrimerApi.commons.CountryCode.Im;
        }
        case "IN": {
          return PrimerApi.commons.CountryCode.In;
        }
        case "IO": {
          return PrimerApi.commons.CountryCode.Io;
        }
        case "IE": {
          return PrimerApi.commons.CountryCode.Ie;
        }
        case "IR": {
          return PrimerApi.commons.CountryCode.Ir;
        }
        case "IQ": {
          return PrimerApi.commons.CountryCode.Iq;
        }
        case "IS": {
          return PrimerApi.commons.CountryCode.Is;
        }
        case "IL": {
          return PrimerApi.commons.CountryCode.Il;
        }
        case "IT": {
          return PrimerApi.commons.CountryCode.It;
        }
        case "JM": {
          return PrimerApi.commons.CountryCode.Jm;
        }
        case "JE": {
          return PrimerApi.commons.CountryCode.Je;
        }
        case "JO": {
          return PrimerApi.commons.CountryCode.Jo;
        }
        case "JP": {
          return PrimerApi.commons.CountryCode.Jp;
        }
        case "KZ": {
          return PrimerApi.commons.CountryCode.Kz;
        }
        case "KE": {
          return PrimerApi.commons.CountryCode.Ke;
        }
        case "KG": {
          return PrimerApi.commons.CountryCode.Kg;
        }
        case "KH": {
          return PrimerApi.commons.CountryCode.Kh;
        }
        case "KI": {
          return PrimerApi.commons.CountryCode.Ki;
        }
        case "KN": {
          return PrimerApi.commons.CountryCode.Kn;
        }
        case "KR": {
          return PrimerApi.commons.CountryCode.Kr;
        }
        case "KW": {
          return PrimerApi.commons.CountryCode.Kw;
        }
        case "LA": {
          return PrimerApi.commons.CountryCode.La;
        }
        case "LB": {
          return PrimerApi.commons.CountryCode.Lb;
        }
        case "LR": {
          return PrimerApi.commons.CountryCode.Lr;
        }
        case "LY": {
          return PrimerApi.commons.CountryCode.Ly;
        }
        case "LC": {
          return PrimerApi.commons.CountryCode.Lc;
        }
        case "LI": {
          return PrimerApi.commons.CountryCode.Li;
        }
        case "LK": {
          return PrimerApi.commons.CountryCode.Lk;
        }
        case "LS": {
          return PrimerApi.commons.CountryCode.Ls;
        }
        case "LT": {
          return PrimerApi.commons.CountryCode.Lt;
        }
        case "LU": {
          return PrimerApi.commons.CountryCode.Lu;
        }
        case "LV": {
          return PrimerApi.commons.CountryCode.Lv;
        }
        case "MO": {
          return PrimerApi.commons.CountryCode.Mo;
        }
        case "MF": {
          return PrimerApi.commons.CountryCode.Mf;
        }
        case "MA": {
          return PrimerApi.commons.CountryCode.Ma;
        }
        case "MC": {
          return PrimerApi.commons.CountryCode.Mc;
        }
        case "MD": {
          return PrimerApi.commons.CountryCode.Md;
        }
        case "MG": {
          return PrimerApi.commons.CountryCode.Mg;
        }
        case "MV": {
          return PrimerApi.commons.CountryCode.Mv;
        }
        case "MX": {
          return PrimerApi.commons.CountryCode.Mx;
        }
        case "MH": {
          return PrimerApi.commons.CountryCode.Mh;
        }
        case "MK": {
          return PrimerApi.commons.CountryCode.Mk;
        }
        case "ML": {
          return PrimerApi.commons.CountryCode.Ml;
        }
        case "MT": {
          return PrimerApi.commons.CountryCode.Mt;
        }
        case "MM": {
          return PrimerApi.commons.CountryCode.Mm;
        }
        case "ME": {
          return PrimerApi.commons.CountryCode.Me;
        }
        case "MN": {
          return PrimerApi.commons.CountryCode.Mn;
        }
        case "MP": {
          return PrimerApi.commons.CountryCode.Mp;
        }
        case "MZ": {
          return PrimerApi.commons.CountryCode.Mz;
        }
        case "MR": {
          return PrimerApi.commons.CountryCode.Mr;
        }
        case "MS": {
          return PrimerApi.commons.CountryCode.Ms;
        }
        case "MQ": {
          return PrimerApi.commons.CountryCode.Mq;
        }
        case "MU": {
          return PrimerApi.commons.CountryCode.Mu;
        }
        case "MW": {
          return PrimerApi.commons.CountryCode.Mw;
        }
        case "MY": {
          return PrimerApi.commons.CountryCode.My;
        }
        case "YT": {
          return PrimerApi.commons.CountryCode.Yt;
        }
        case "NA": {
          return PrimerApi.commons.CountryCode.Na;
        }
        case "NC": {
          return PrimerApi.commons.CountryCode.Nc;
        }
        case "NE": {
          return PrimerApi.commons.CountryCode.Ne;
        }
        case "NF": {
          return PrimerApi.commons.CountryCode.Nf;
        }
        case "NG": {
          return PrimerApi.commons.CountryCode.Ng;
        }
        case "NI": {
          return PrimerApi.commons.CountryCode.Ni;
        }
        case "NU": {
          return PrimerApi.commons.CountryCode.Nu;
        }
        case "NL": {
          return PrimerApi.commons.CountryCode.Nl;
        }
        case "NO": {
          return PrimerApi.commons.CountryCode.No;
        }
        case "NP": {
          return PrimerApi.commons.CountryCode.Np;
        }
        case "NR": {
          return PrimerApi.commons.CountryCode.Nr;
        }
        case "NZ": {
          return PrimerApi.commons.CountryCode.Nz;
        }
        case "OM": {
          return PrimerApi.commons.CountryCode.Om;
        }
        case "PK": {
          return PrimerApi.commons.CountryCode.Pk;
        }
        case "PA": {
          return PrimerApi.commons.CountryCode.Pa;
        }
        case "PN": {
          return PrimerApi.commons.CountryCode.Pn;
        }
        case "PE": {
          return PrimerApi.commons.CountryCode.Pe;
        }
        case "PH": {
          return PrimerApi.commons.CountryCode.Ph;
        }
        case "PW": {
          return PrimerApi.commons.CountryCode.Pw;
        }
        case "PG": {
          return PrimerApi.commons.CountryCode.Pg;
        }
        case "PL": {
          return PrimerApi.commons.CountryCode.Pl;
        }
        case "PR": {
          return PrimerApi.commons.CountryCode.Pr;
        }
        case "KP": {
          return PrimerApi.commons.CountryCode.Kp;
        }
        case "PT": {
          return PrimerApi.commons.CountryCode.Pt;
        }
        case "PY": {
          return PrimerApi.commons.CountryCode.Py;
        }
        case "PS": {
          return PrimerApi.commons.CountryCode.Ps;
        }
        case "PF": {
          return PrimerApi.commons.CountryCode.Pf;
        }
        case "QA": {
          return PrimerApi.commons.CountryCode.Qa;
        }
        case "RE": {
          return PrimerApi.commons.CountryCode.Re;
        }
        case "RO": {
          return PrimerApi.commons.CountryCode.Ro;
        }
        case "RU": {
          return PrimerApi.commons.CountryCode.Ru;
        }
        case "RW": {
          return PrimerApi.commons.CountryCode.Rw;
        }
        case "SA": {
          return PrimerApi.commons.CountryCode.Sa;
        }
        case "SD": {
          return PrimerApi.commons.CountryCode.Sd;
        }
        case "SN": {
          return PrimerApi.commons.CountryCode.Sn;
        }
        case "SG": {
          return PrimerApi.commons.CountryCode.Sg;
        }
        case "GS": {
          return PrimerApi.commons.CountryCode.Gs;
        }
        case "SH": {
          return PrimerApi.commons.CountryCode.Sh;
        }
        case "SJ": {
          return PrimerApi.commons.CountryCode.Sj;
        }
        case "SB": {
          return PrimerApi.commons.CountryCode.Sb;
        }
        case "SL": {
          return PrimerApi.commons.CountryCode.Sl;
        }
        case "SV": {
          return PrimerApi.commons.CountryCode.Sv;
        }
        case "SM": {
          return PrimerApi.commons.CountryCode.Sm;
        }
        case "SO": {
          return PrimerApi.commons.CountryCode.So;
        }
        case "PM": {
          return PrimerApi.commons.CountryCode.Pm;
        }
        case "RS": {
          return PrimerApi.commons.CountryCode.Rs;
        }
        case "SS": {
          return PrimerApi.commons.CountryCode.Ss;
        }
        case "ST": {
          return PrimerApi.commons.CountryCode.St;
        }
        case "SR": {
          return PrimerApi.commons.CountryCode.Sr;
        }
        case "SK": {
          return PrimerApi.commons.CountryCode.Sk;
        }
        case "SI": {
          return PrimerApi.commons.CountryCode.Si;
        }
        case "SE": {
          return PrimerApi.commons.CountryCode.Se;
        }
        case "SZ": {
          return PrimerApi.commons.CountryCode.Sz;
        }
        case "SX": {
          return PrimerApi.commons.CountryCode.Sx;
        }
        case "SC": {
          return PrimerApi.commons.CountryCode.Sc;
        }
        case "SY": {
          return PrimerApi.commons.CountryCode.Sy;
        }
        case "TC": {
          return PrimerApi.commons.CountryCode.Tc;
        }
        case "TD": {
          return PrimerApi.commons.CountryCode.Td;
        }
        case "TG": {
          return PrimerApi.commons.CountryCode.Tg;
        }
        case "TH": {
          return PrimerApi.commons.CountryCode.Th;
        }
        case "TJ": {
          return PrimerApi.commons.CountryCode.Tj;
        }
        case "TK": {
          return PrimerApi.commons.CountryCode.Tk;
        }
        case "TM": {
          return PrimerApi.commons.CountryCode.Tm;
        }
        case "TL": {
          return PrimerApi.commons.CountryCode.Tl;
        }
        case "TO": {
          return PrimerApi.commons.CountryCode.To;
        }
        case "TT": {
          return PrimerApi.commons.CountryCode.Tt;
        }
        case "TN": {
          return PrimerApi.commons.CountryCode.Tn;
        }
        case "TR": {
          return PrimerApi.commons.CountryCode.Tr;
        }
        case "TV": {
          return PrimerApi.commons.CountryCode.Tv;
        }
        case "TW": {
          return PrimerApi.commons.CountryCode.Tw;
        }
        case "TZ": {
          return PrimerApi.commons.CountryCode.Tz;
        }
        case "UG": {
          return PrimerApi.commons.CountryCode.Ug;
        }
        case "UA": {
          return PrimerApi.commons.CountryCode.Ua;
        }
        case "UM": {
          return PrimerApi.commons.CountryCode.Um;
        }
        case "UY": {
          return PrimerApi.commons.CountryCode.Uy;
        }
        case "US": {
          return PrimerApi.commons.CountryCode.Us;
        }
        case "UZ": {
          return PrimerApi.commons.CountryCode.Uz;
        }
        case "VA": {
          return PrimerApi.commons.CountryCode.Va;
        }
        case "VC": {
          return PrimerApi.commons.CountryCode.Vc;
        }
        case "VE": {
          return PrimerApi.commons.CountryCode.Ve;
        }
        case "VG": {
          return PrimerApi.commons.CountryCode.Vg;
        }
        case "VI": {
          return PrimerApi.commons.CountryCode.Vi;
        }
        case "VN": {
          return PrimerApi.commons.CountryCode.Vn;
        }
        case "VU": {
          return PrimerApi.commons.CountryCode.Vu;
        }
        case "WF": {
          return PrimerApi.commons.CountryCode.Wf;
        }
        case "WS": {
          return PrimerApi.commons.CountryCode.Ws;
        }
        case "YE": {
          return PrimerApi.commons.CountryCode.Ye;
        }
        case "ZA": {
          return PrimerApi.commons.CountryCode.Za;
        }
        case "ZM": {
          return PrimerApi.commons.CountryCode.Zm;
        }
        case "ZW": {
          return PrimerApi.commons.CountryCode.Zw;
        }
        default: {
          return {
            value: value,
            visit: (visitor) => visitor._other(value),
          };
        }
      }
    },
    json: (value) => value.value,
  });

export declare namespace CountryCode {
  type Raw = string;
}
