/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const CustomerId: core.schemas.Schema<CustomerId.Raw, PrimerApi.commons.CustomerId> = core.schemas.string();

export declare namespace CustomerId {
  type Raw = string;
}
