/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";

export interface BaseErrorBody {
  /** An error ID */
  errorId: PrimerPrimerApi.ErrorId;
  /** A human description of the error */
  description: string;
  /**
   * An ID that you can quote when contacting the support team
   * (support@primer.io).
   *
   */
  diagnosticsId: PrimerPrimerApi.DiagnosticsId;
}
