/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface CountryCode<RawValue extends CountryCode.RawValue = CountryCode.RawValue> {
  value: RawValue;
  visit: <Result>(visitor: CountryCode._Visitor<Result>) => Result;
}

const _Aw: CountryCode<"AW"> = {
  value: "AW",
  visit: (visitor) => visitor.aw(),
};
const _Af: CountryCode<"AF"> = {
  value: "AF",
  visit: (visitor) => visitor.af(),
};
const _Ao: CountryCode<"AO"> = {
  value: "AO",
  visit: (visitor) => visitor.ao(),
};
const _Ai: CountryCode<"AI"> = {
  value: "AI",
  visit: (visitor) => visitor.ai(),
};
const _Ax: CountryCode<"AX"> = {
  value: "AX",
  visit: (visitor) => visitor.ax(),
};
const _Al: CountryCode<"AL"> = {
  value: "AL",
  visit: (visitor) => visitor.al(),
};
const _Ad: CountryCode<"AD"> = {
  value: "AD",
  visit: (visitor) => visitor.ad(),
};
const _Ae: CountryCode<"AE"> = {
  value: "AE",
  visit: (visitor) => visitor.ae(),
};
const _Ar: CountryCode<"AR"> = {
  value: "AR",
  visit: (visitor) => visitor.ar(),
};
const _Am: CountryCode<"AM"> = {
  value: "AM",
  visit: (visitor) => visitor.am(),
};
const _As: CountryCode<"AS"> = {
  value: "AS",
  visit: (visitor) => visitor.as(),
};
const _Aq: CountryCode<"AQ"> = {
  value: "AQ",
  visit: (visitor) => visitor.aq(),
};
const _Tf: CountryCode<"TF"> = {
  value: "TF",
  visit: (visitor) => visitor.tf(),
};
const _Ag: CountryCode<"AG"> = {
  value: "AG",
  visit: (visitor) => visitor.ag(),
};
const _Au: CountryCode<"AU"> = {
  value: "AU",
  visit: (visitor) => visitor.au(),
};
const _At: CountryCode<"AT"> = {
  value: "AT",
  visit: (visitor) => visitor.at(),
};
const _Az: CountryCode<"AZ"> = {
  value: "AZ",
  visit: (visitor) => visitor.az(),
};
const _Bi: CountryCode<"BI"> = {
  value: "BI",
  visit: (visitor) => visitor.bi(),
};
const _Be: CountryCode<"BE"> = {
  value: "BE",
  visit: (visitor) => visitor.be(),
};
const _Bj: CountryCode<"BJ"> = {
  value: "BJ",
  visit: (visitor) => visitor.bj(),
};
const _Bq: CountryCode<"BQ"> = {
  value: "BQ",
  visit: (visitor) => visitor.bq(),
};
const _Bf: CountryCode<"BF"> = {
  value: "BF",
  visit: (visitor) => visitor.bf(),
};
const _Bd: CountryCode<"BD"> = {
  value: "BD",
  visit: (visitor) => visitor.bd(),
};
const _Bg: CountryCode<"BG"> = {
  value: "BG",
  visit: (visitor) => visitor.bg(),
};
const _Bh: CountryCode<"BH"> = {
  value: "BH",
  visit: (visitor) => visitor.bh(),
};
const _Bs: CountryCode<"BS"> = {
  value: "BS",
  visit: (visitor) => visitor.bs(),
};
const _Ba: CountryCode<"BA"> = {
  value: "BA",
  visit: (visitor) => visitor.ba(),
};
const _Bl: CountryCode<"BL"> = {
  value: "BL",
  visit: (visitor) => visitor.bl(),
};
const _By: CountryCode<"BY"> = {
  value: "BY",
  visit: (visitor) => visitor.by(),
};
const _Bz: CountryCode<"BZ"> = {
  value: "BZ",
  visit: (visitor) => visitor.bz(),
};
const _Bm: CountryCode<"BM"> = {
  value: "BM",
  visit: (visitor) => visitor.bm(),
};
const _Bo: CountryCode<"BO"> = {
  value: "BO",
  visit: (visitor) => visitor.bo(),
};
const _Br: CountryCode<"BR"> = {
  value: "BR",
  visit: (visitor) => visitor.br(),
};
const _Bb: CountryCode<"BB"> = {
  value: "BB",
  visit: (visitor) => visitor.bb(),
};
const _Bn: CountryCode<"BN"> = {
  value: "BN",
  visit: (visitor) => visitor.bn(),
};
const _Bt: CountryCode<"BT"> = {
  value: "BT",
  visit: (visitor) => visitor.bt(),
};
const _Bv: CountryCode<"BV"> = {
  value: "BV",
  visit: (visitor) => visitor.bv(),
};
const _Bw: CountryCode<"BW"> = {
  value: "BW",
  visit: (visitor) => visitor.bw(),
};
const _Cf: CountryCode<"CF"> = {
  value: "CF",
  visit: (visitor) => visitor.cf(),
};
const _Ca: CountryCode<"CA"> = {
  value: "CA",
  visit: (visitor) => visitor.ca(),
};
const _Cc: CountryCode<"CC"> = {
  value: "CC",
  visit: (visitor) => visitor.cc(),
};
const _Ch: CountryCode<"CH"> = {
  value: "CH",
  visit: (visitor) => visitor.ch(),
};
const _Cl: CountryCode<"CL"> = {
  value: "CL",
  visit: (visitor) => visitor.cl(),
};
const _Cn: CountryCode<"CN"> = {
  value: "CN",
  visit: (visitor) => visitor.cn(),
};
const _Ci: CountryCode<"CI"> = {
  value: "CI",
  visit: (visitor) => visitor.ci(),
};
const _Cm: CountryCode<"CM"> = {
  value: "CM",
  visit: (visitor) => visitor.cm(),
};
const _Cd: CountryCode<"CD"> = {
  value: "CD",
  visit: (visitor) => visitor.cd(),
};
const _Cg: CountryCode<"CG"> = {
  value: "CG",
  visit: (visitor) => visitor.cg(),
};
const _Ck: CountryCode<"CK"> = {
  value: "CK",
  visit: (visitor) => visitor.ck(),
};
const _Co: CountryCode<"CO"> = {
  value: "CO",
  visit: (visitor) => visitor.co(),
};
const _Km: CountryCode<"KM"> = {
  value: "KM",
  visit: (visitor) => visitor.km(),
};
const _Cv: CountryCode<"CV"> = {
  value: "CV",
  visit: (visitor) => visitor.cv(),
};
const _Cr: CountryCode<"CR"> = {
  value: "CR",
  visit: (visitor) => visitor.cr(),
};
const _Cu: CountryCode<"CU"> = {
  value: "CU",
  visit: (visitor) => visitor.cu(),
};
const _Cw: CountryCode<"CW"> = {
  value: "CW",
  visit: (visitor) => visitor.cw(),
};
const _Cx: CountryCode<"CX"> = {
  value: "CX",
  visit: (visitor) => visitor.cx(),
};
const _Ky: CountryCode<"KY"> = {
  value: "KY",
  visit: (visitor) => visitor.ky(),
};
const _Cy: CountryCode<"CY"> = {
  value: "CY",
  visit: (visitor) => visitor.cy(),
};
const _Cz: CountryCode<"CZ"> = {
  value: "CZ",
  visit: (visitor) => visitor.cz(),
};
const _De: CountryCode<"DE"> = {
  value: "DE",
  visit: (visitor) => visitor.de(),
};
const _Dj: CountryCode<"DJ"> = {
  value: "DJ",
  visit: (visitor) => visitor.dj(),
};
const _Dm: CountryCode<"DM"> = {
  value: "DM",
  visit: (visitor) => visitor.dm(),
};
const _Dk: CountryCode<"DK"> = {
  value: "DK",
  visit: (visitor) => visitor.dk(),
};
const _Do: CountryCode<"DO"> = {
  value: "DO",
  visit: (visitor) => visitor.do(),
};
const _Dz: CountryCode<"DZ"> = {
  value: "DZ",
  visit: (visitor) => visitor.dz(),
};
const _Ec: CountryCode<"EC"> = {
  value: "EC",
  visit: (visitor) => visitor.ec(),
};
const _Eg: CountryCode<"EG"> = {
  value: "EG",
  visit: (visitor) => visitor.eg(),
};
const _Er: CountryCode<"ER"> = {
  value: "ER",
  visit: (visitor) => visitor.er(),
};
const _Eh: CountryCode<"EH"> = {
  value: "EH",
  visit: (visitor) => visitor.eh(),
};
const _Es: CountryCode<"ES"> = {
  value: "ES",
  visit: (visitor) => visitor.es(),
};
const _Ee: CountryCode<"EE"> = {
  value: "EE",
  visit: (visitor) => visitor.ee(),
};
const _Et: CountryCode<"ET"> = {
  value: "ET",
  visit: (visitor) => visitor.et(),
};
const _Fi: CountryCode<"FI"> = {
  value: "FI",
  visit: (visitor) => visitor.fi(),
};
const _Fj: CountryCode<"FJ"> = {
  value: "FJ",
  visit: (visitor) => visitor.fj(),
};
const _Fk: CountryCode<"FK"> = {
  value: "FK",
  visit: (visitor) => visitor.fk(),
};
const _Fr: CountryCode<"FR"> = {
  value: "FR",
  visit: (visitor) => visitor.fr(),
};
const _Fo: CountryCode<"FO"> = {
  value: "FO",
  visit: (visitor) => visitor.fo(),
};
const _Fm: CountryCode<"FM"> = {
  value: "FM",
  visit: (visitor) => visitor.fm(),
};
const _Ga: CountryCode<"GA"> = {
  value: "GA",
  visit: (visitor) => visitor.ga(),
};
const _Gb: CountryCode<"GB"> = {
  value: "GB",
  visit: (visitor) => visitor.gb(),
};
const _Ge: CountryCode<"GE"> = {
  value: "GE",
  visit: (visitor) => visitor.ge(),
};
const _Gg: CountryCode<"GG"> = {
  value: "GG",
  visit: (visitor) => visitor.gg(),
};
const _Gh: CountryCode<"GH"> = {
  value: "GH",
  visit: (visitor) => visitor.gh(),
};
const _Gi: CountryCode<"GI"> = {
  value: "GI",
  visit: (visitor) => visitor.gi(),
};
const _Gn: CountryCode<"GN"> = {
  value: "GN",
  visit: (visitor) => visitor.gn(),
};
const _Gp: CountryCode<"GP"> = {
  value: "GP",
  visit: (visitor) => visitor.gp(),
};
const _Gm: CountryCode<"GM"> = {
  value: "GM",
  visit: (visitor) => visitor.gm(),
};
const _Gw: CountryCode<"GW"> = {
  value: "GW",
  visit: (visitor) => visitor.gw(),
};
const _Gq: CountryCode<"GQ"> = {
  value: "GQ",
  visit: (visitor) => visitor.gq(),
};
const _Gr: CountryCode<"GR"> = {
  value: "GR",
  visit: (visitor) => visitor.gr(),
};
const _Gd: CountryCode<"GD"> = {
  value: "GD",
  visit: (visitor) => visitor.gd(),
};
const _Gl: CountryCode<"GL"> = {
  value: "GL",
  visit: (visitor) => visitor.gl(),
};
const _Gt: CountryCode<"GT"> = {
  value: "GT",
  visit: (visitor) => visitor.gt(),
};
const _Gf: CountryCode<"GF"> = {
  value: "GF",
  visit: (visitor) => visitor.gf(),
};
const _Gu: CountryCode<"GU"> = {
  value: "GU",
  visit: (visitor) => visitor.gu(),
};
const _Gy: CountryCode<"GY"> = {
  value: "GY",
  visit: (visitor) => visitor.gy(),
};
const _Hk: CountryCode<"HK"> = {
  value: "HK",
  visit: (visitor) => visitor.hk(),
};
const _Hm: CountryCode<"HM"> = {
  value: "HM",
  visit: (visitor) => visitor.hm(),
};
const _Hn: CountryCode<"HN"> = {
  value: "HN",
  visit: (visitor) => visitor.hn(),
};
const _Hr: CountryCode<"HR"> = {
  value: "HR",
  visit: (visitor) => visitor.hr(),
};
const _Ht: CountryCode<"HT"> = {
  value: "HT",
  visit: (visitor) => visitor.ht(),
};
const _Hu: CountryCode<"HU"> = {
  value: "HU",
  visit: (visitor) => visitor.hu(),
};
const _Id: CountryCode<"ID"> = {
  value: "ID",
  visit: (visitor) => visitor.id(),
};
const _Im: CountryCode<"IM"> = {
  value: "IM",
  visit: (visitor) => visitor.im(),
};
const _In: CountryCode<"IN"> = {
  value: "IN",
  visit: (visitor) => visitor.in(),
};
const _Io: CountryCode<"IO"> = {
  value: "IO",
  visit: (visitor) => visitor.io(),
};
const _Ie: CountryCode<"IE"> = {
  value: "IE",
  visit: (visitor) => visitor.ie(),
};
const _Ir: CountryCode<"IR"> = {
  value: "IR",
  visit: (visitor) => visitor.ir(),
};
const _Iq: CountryCode<"IQ"> = {
  value: "IQ",
  visit: (visitor) => visitor.iq(),
};
const _Is: CountryCode<"IS"> = {
  value: "IS",
  visit: (visitor) => visitor.is(),
};
const _Il: CountryCode<"IL"> = {
  value: "IL",
  visit: (visitor) => visitor.il(),
};
const _It: CountryCode<"IT"> = {
  value: "IT",
  visit: (visitor) => visitor.it(),
};
const _Jm: CountryCode<"JM"> = {
  value: "JM",
  visit: (visitor) => visitor.jm(),
};
const _Je: CountryCode<"JE"> = {
  value: "JE",
  visit: (visitor) => visitor.je(),
};
const _Jo: CountryCode<"JO"> = {
  value: "JO",
  visit: (visitor) => visitor.jo(),
};
const _Jp: CountryCode<"JP"> = {
  value: "JP",
  visit: (visitor) => visitor.jp(),
};
const _Kz: CountryCode<"KZ"> = {
  value: "KZ",
  visit: (visitor) => visitor.kz(),
};
const _Ke: CountryCode<"KE"> = {
  value: "KE",
  visit: (visitor) => visitor.ke(),
};
const _Kg: CountryCode<"KG"> = {
  value: "KG",
  visit: (visitor) => visitor.kg(),
};
const _Kh: CountryCode<"KH"> = {
  value: "KH",
  visit: (visitor) => visitor.kh(),
};
const _Ki: CountryCode<"KI"> = {
  value: "KI",
  visit: (visitor) => visitor.ki(),
};
const _Kn: CountryCode<"KN"> = {
  value: "KN",
  visit: (visitor) => visitor.kn(),
};
const _Kr: CountryCode<"KR"> = {
  value: "KR",
  visit: (visitor) => visitor.kr(),
};
const _Kw: CountryCode<"KW"> = {
  value: "KW",
  visit: (visitor) => visitor.kw(),
};
const _La: CountryCode<"LA"> = {
  value: "LA",
  visit: (visitor) => visitor.la(),
};
const _Lb: CountryCode<"LB"> = {
  value: "LB",
  visit: (visitor) => visitor.lb(),
};
const _Lr: CountryCode<"LR"> = {
  value: "LR",
  visit: (visitor) => visitor.lr(),
};
const _Ly: CountryCode<"LY"> = {
  value: "LY",
  visit: (visitor) => visitor.ly(),
};
const _Lc: CountryCode<"LC"> = {
  value: "LC",
  visit: (visitor) => visitor.lc(),
};
const _Li: CountryCode<"LI"> = {
  value: "LI",
  visit: (visitor) => visitor.li(),
};
const _Lk: CountryCode<"LK"> = {
  value: "LK",
  visit: (visitor) => visitor.lk(),
};
const _Ls: CountryCode<"LS"> = {
  value: "LS",
  visit: (visitor) => visitor.ls(),
};
const _Lt: CountryCode<"LT"> = {
  value: "LT",
  visit: (visitor) => visitor.lt(),
};
const _Lu: CountryCode<"LU"> = {
  value: "LU",
  visit: (visitor) => visitor.lu(),
};
const _Lv: CountryCode<"LV"> = {
  value: "LV",
  visit: (visitor) => visitor.lv(),
};
const _Mo: CountryCode<"MO"> = {
  value: "MO",
  visit: (visitor) => visitor.mo(),
};
const _Mf: CountryCode<"MF"> = {
  value: "MF",
  visit: (visitor) => visitor.mf(),
};
const _Ma: CountryCode<"MA"> = {
  value: "MA",
  visit: (visitor) => visitor.ma(),
};
const _Mc: CountryCode<"MC"> = {
  value: "MC",
  visit: (visitor) => visitor.mc(),
};
const _Md: CountryCode<"MD"> = {
  value: "MD",
  visit: (visitor) => visitor.md(),
};
const _Mg: CountryCode<"MG"> = {
  value: "MG",
  visit: (visitor) => visitor.mg(),
};
const _Mv: CountryCode<"MV"> = {
  value: "MV",
  visit: (visitor) => visitor.mv(),
};
const _Mx: CountryCode<"MX"> = {
  value: "MX",
  visit: (visitor) => visitor.mx(),
};
const _Mh: CountryCode<"MH"> = {
  value: "MH",
  visit: (visitor) => visitor.mh(),
};
const _Mk: CountryCode<"MK"> = {
  value: "MK",
  visit: (visitor) => visitor.mk(),
};
const _Ml: CountryCode<"ML"> = {
  value: "ML",
  visit: (visitor) => visitor.ml(),
};
const _Mt: CountryCode<"MT"> = {
  value: "MT",
  visit: (visitor) => visitor.mt(),
};
const _Mm: CountryCode<"MM"> = {
  value: "MM",
  visit: (visitor) => visitor.mm(),
};
const _Me: CountryCode<"ME"> = {
  value: "ME",
  visit: (visitor) => visitor.me(),
};
const _Mn: CountryCode<"MN"> = {
  value: "MN",
  visit: (visitor) => visitor.mn(),
};
const _Mp: CountryCode<"MP"> = {
  value: "MP",
  visit: (visitor) => visitor.mp(),
};
const _Mz: CountryCode<"MZ"> = {
  value: "MZ",
  visit: (visitor) => visitor.mz(),
};
const _Mr: CountryCode<"MR"> = {
  value: "MR",
  visit: (visitor) => visitor.mr(),
};
const _Ms: CountryCode<"MS"> = {
  value: "MS",
  visit: (visitor) => visitor.ms(),
};
const _Mq: CountryCode<"MQ"> = {
  value: "MQ",
  visit: (visitor) => visitor.mq(),
};
const _Mu: CountryCode<"MU"> = {
  value: "MU",
  visit: (visitor) => visitor.mu(),
};
const _Mw: CountryCode<"MW"> = {
  value: "MW",
  visit: (visitor) => visitor.mw(),
};
const _My: CountryCode<"MY"> = {
  value: "MY",
  visit: (visitor) => visitor.my(),
};
const _Yt: CountryCode<"YT"> = {
  value: "YT",
  visit: (visitor) => visitor.yt(),
};
const _Na: CountryCode<"NA"> = {
  value: "NA",
  visit: (visitor) => visitor.na(),
};
const _Nc: CountryCode<"NC"> = {
  value: "NC",
  visit: (visitor) => visitor.nc(),
};
const _Ne: CountryCode<"NE"> = {
  value: "NE",
  visit: (visitor) => visitor.ne(),
};
const _Nf: CountryCode<"NF"> = {
  value: "NF",
  visit: (visitor) => visitor.nf(),
};
const _Ng: CountryCode<"NG"> = {
  value: "NG",
  visit: (visitor) => visitor.ng(),
};
const _Ni: CountryCode<"NI"> = {
  value: "NI",
  visit: (visitor) => visitor.ni(),
};
const _Nu: CountryCode<"NU"> = {
  value: "NU",
  visit: (visitor) => visitor.nu(),
};
const _Nl: CountryCode<"NL"> = {
  value: "NL",
  visit: (visitor) => visitor.nl(),
};
const _No: CountryCode<"NO"> = {
  value: "NO",
  visit: (visitor) => visitor.no(),
};
const _Np: CountryCode<"NP"> = {
  value: "NP",
  visit: (visitor) => visitor.np(),
};
const _Nr: CountryCode<"NR"> = {
  value: "NR",
  visit: (visitor) => visitor.nr(),
};
const _Nz: CountryCode<"NZ"> = {
  value: "NZ",
  visit: (visitor) => visitor.nz(),
};
const _Om: CountryCode<"OM"> = {
  value: "OM",
  visit: (visitor) => visitor.om(),
};
const _Pk: CountryCode<"PK"> = {
  value: "PK",
  visit: (visitor) => visitor.pk(),
};
const _Pa: CountryCode<"PA"> = {
  value: "PA",
  visit: (visitor) => visitor.pa(),
};
const _Pn: CountryCode<"PN"> = {
  value: "PN",
  visit: (visitor) => visitor.pn(),
};
const _Pe: CountryCode<"PE"> = {
  value: "PE",
  visit: (visitor) => visitor.pe(),
};
const _Ph: CountryCode<"PH"> = {
  value: "PH",
  visit: (visitor) => visitor.ph(),
};
const _Pw: CountryCode<"PW"> = {
  value: "PW",
  visit: (visitor) => visitor.pw(),
};
const _Pg: CountryCode<"PG"> = {
  value: "PG",
  visit: (visitor) => visitor.pg(),
};
const _Pl: CountryCode<"PL"> = {
  value: "PL",
  visit: (visitor) => visitor.pl(),
};
const _Pr: CountryCode<"PR"> = {
  value: "PR",
  visit: (visitor) => visitor.pr(),
};
const _Kp: CountryCode<"KP"> = {
  value: "KP",
  visit: (visitor) => visitor.kp(),
};
const _Pt: CountryCode<"PT"> = {
  value: "PT",
  visit: (visitor) => visitor.pt(),
};
const _Py: CountryCode<"PY"> = {
  value: "PY",
  visit: (visitor) => visitor.py(),
};
const _Ps: CountryCode<"PS"> = {
  value: "PS",
  visit: (visitor) => visitor.ps(),
};
const _Pf: CountryCode<"PF"> = {
  value: "PF",
  visit: (visitor) => visitor.pf(),
};
const _Qa: CountryCode<"QA"> = {
  value: "QA",
  visit: (visitor) => visitor.qa(),
};
const _Re: CountryCode<"RE"> = {
  value: "RE",
  visit: (visitor) => visitor.re(),
};
const _Ro: CountryCode<"RO"> = {
  value: "RO",
  visit: (visitor) => visitor.ro(),
};
const _Ru: CountryCode<"RU"> = {
  value: "RU",
  visit: (visitor) => visitor.ru(),
};
const _Rw: CountryCode<"RW"> = {
  value: "RW",
  visit: (visitor) => visitor.rw(),
};
const _Sa: CountryCode<"SA"> = {
  value: "SA",
  visit: (visitor) => visitor.sa(),
};
const _Sd: CountryCode<"SD"> = {
  value: "SD",
  visit: (visitor) => visitor.sd(),
};
const _Sn: CountryCode<"SN"> = {
  value: "SN",
  visit: (visitor) => visitor.sn(),
};
const _Sg: CountryCode<"SG"> = {
  value: "SG",
  visit: (visitor) => visitor.sg(),
};
const _Gs: CountryCode<"GS"> = {
  value: "GS",
  visit: (visitor) => visitor.gs(),
};
const _Sh: CountryCode<"SH"> = {
  value: "SH",
  visit: (visitor) => visitor.sh(),
};
const _Sj: CountryCode<"SJ"> = {
  value: "SJ",
  visit: (visitor) => visitor.sj(),
};
const _Sb: CountryCode<"SB"> = {
  value: "SB",
  visit: (visitor) => visitor.sb(),
};
const _Sl: CountryCode<"SL"> = {
  value: "SL",
  visit: (visitor) => visitor.sl(),
};
const _Sv: CountryCode<"SV"> = {
  value: "SV",
  visit: (visitor) => visitor.sv(),
};
const _Sm: CountryCode<"SM"> = {
  value: "SM",
  visit: (visitor) => visitor.sm(),
};
const _So: CountryCode<"SO"> = {
  value: "SO",
  visit: (visitor) => visitor.so(),
};
const _Pm: CountryCode<"PM"> = {
  value: "PM",
  visit: (visitor) => visitor.pm(),
};
const _Rs: CountryCode<"RS"> = {
  value: "RS",
  visit: (visitor) => visitor.rs(),
};
const _Ss: CountryCode<"SS"> = {
  value: "SS",
  visit: (visitor) => visitor.ss(),
};
const _St: CountryCode<"ST"> = {
  value: "ST",
  visit: (visitor) => visitor.st(),
};
const _Sr: CountryCode<"SR"> = {
  value: "SR",
  visit: (visitor) => visitor.sr(),
};
const _Sk: CountryCode<"SK"> = {
  value: "SK",
  visit: (visitor) => visitor.sk(),
};
const _Si: CountryCode<"SI"> = {
  value: "SI",
  visit: (visitor) => visitor.si(),
};
const _Se: CountryCode<"SE"> = {
  value: "SE",
  visit: (visitor) => visitor.se(),
};
const _Sz: CountryCode<"SZ"> = {
  value: "SZ",
  visit: (visitor) => visitor.sz(),
};
const _Sx: CountryCode<"SX"> = {
  value: "SX",
  visit: (visitor) => visitor.sx(),
};
const _Sc: CountryCode<"SC"> = {
  value: "SC",
  visit: (visitor) => visitor.sc(),
};
const _Sy: CountryCode<"SY"> = {
  value: "SY",
  visit: (visitor) => visitor.sy(),
};
const _Tc: CountryCode<"TC"> = {
  value: "TC",
  visit: (visitor) => visitor.tc(),
};
const _Td: CountryCode<"TD"> = {
  value: "TD",
  visit: (visitor) => visitor.td(),
};
const _Tg: CountryCode<"TG"> = {
  value: "TG",
  visit: (visitor) => visitor.tg(),
};
const _Th: CountryCode<"TH"> = {
  value: "TH",
  visit: (visitor) => visitor.th(),
};
const _Tj: CountryCode<"TJ"> = {
  value: "TJ",
  visit: (visitor) => visitor.tj(),
};
const _Tk: CountryCode<"TK"> = {
  value: "TK",
  visit: (visitor) => visitor.tk(),
};
const _Tm: CountryCode<"TM"> = {
  value: "TM",
  visit: (visitor) => visitor.tm(),
};
const _Tl: CountryCode<"TL"> = {
  value: "TL",
  visit: (visitor) => visitor.tl(),
};
const _To: CountryCode<"TO"> = {
  value: "TO",
  visit: (visitor) => visitor.to(),
};
const _Tt: CountryCode<"TT"> = {
  value: "TT",
  visit: (visitor) => visitor.tt(),
};
const _Tn: CountryCode<"TN"> = {
  value: "TN",
  visit: (visitor) => visitor.tn(),
};
const _Tr: CountryCode<"TR"> = {
  value: "TR",
  visit: (visitor) => visitor.tr(),
};
const _Tv: CountryCode<"TV"> = {
  value: "TV",
  visit: (visitor) => visitor.tv(),
};
const _Tw: CountryCode<"TW"> = {
  value: "TW",
  visit: (visitor) => visitor.tw(),
};
const _Tz: CountryCode<"TZ"> = {
  value: "TZ",
  visit: (visitor) => visitor.tz(),
};
const _Ug: CountryCode<"UG"> = {
  value: "UG",
  visit: (visitor) => visitor.ug(),
};
const _Ua: CountryCode<"UA"> = {
  value: "UA",
  visit: (visitor) => visitor.ua(),
};
const _Um: CountryCode<"UM"> = {
  value: "UM",
  visit: (visitor) => visitor.um(),
};
const _Uy: CountryCode<"UY"> = {
  value: "UY",
  visit: (visitor) => visitor.uy(),
};
const _Us: CountryCode<"US"> = {
  value: "US",
  visit: (visitor) => visitor.us(),
};
const _Uz: CountryCode<"UZ"> = {
  value: "UZ",
  visit: (visitor) => visitor.uz(),
};
const _Va: CountryCode<"VA"> = {
  value: "VA",
  visit: (visitor) => visitor.va(),
};
const _Vc: CountryCode<"VC"> = {
  value: "VC",
  visit: (visitor) => visitor.vc(),
};
const _Ve: CountryCode<"VE"> = {
  value: "VE",
  visit: (visitor) => visitor.ve(),
};
const _Vg: CountryCode<"VG"> = {
  value: "VG",
  visit: (visitor) => visitor.vg(),
};
const _Vi: CountryCode<"VI"> = {
  value: "VI",
  visit: (visitor) => visitor.vi(),
};
const _Vn: CountryCode<"VN"> = {
  value: "VN",
  visit: (visitor) => visitor.vn(),
};
const _Vu: CountryCode<"VU"> = {
  value: "VU",
  visit: (visitor) => visitor.vu(),
};
const _Wf: CountryCode<"WF"> = {
  value: "WF",
  visit: (visitor) => visitor.wf(),
};
const _Ws: CountryCode<"WS"> = {
  value: "WS",
  visit: (visitor) => visitor.ws(),
};
const _Ye: CountryCode<"YE"> = {
  value: "YE",
  visit: (visitor) => visitor.ye(),
};
const _Za: CountryCode<"ZA"> = {
  value: "ZA",
  visit: (visitor) => visitor.za(),
};
const _Zm: CountryCode<"ZM"> = {
  value: "ZM",
  visit: (visitor) => visitor.zm(),
};
const _Zw: CountryCode<"ZW"> = {
  value: "ZW",
  visit: (visitor) => visitor.zw(),
};
export const CountryCode = {
  Aw: _Aw,
  Af: _Af,
  Ao: _Ao,
  Ai: _Ai,
  Ax: _Ax,
  Al: _Al,
  Ad: _Ad,
  Ae: _Ae,
  Ar: _Ar,
  Am: _Am,
  As: _As,
  Aq: _Aq,
  Tf: _Tf,
  Ag: _Ag,
  Au: _Au,
  At: _At,
  Az: _Az,
  Bi: _Bi,
  Be: _Be,
  Bj: _Bj,
  Bq: _Bq,
  Bf: _Bf,
  Bd: _Bd,
  Bg: _Bg,
  Bh: _Bh,
  Bs: _Bs,
  Ba: _Ba,
  Bl: _Bl,
  By: _By,
  Bz: _Bz,
  Bm: _Bm,
  Bo: _Bo,
  Br: _Br,
  Bb: _Bb,
  Bn: _Bn,
  Bt: _Bt,
  Bv: _Bv,
  Bw: _Bw,
  Cf: _Cf,
  Ca: _Ca,
  Cc: _Cc,
  Ch: _Ch,
  Cl: _Cl,
  Cn: _Cn,
  Ci: _Ci,
  Cm: _Cm,
  Cd: _Cd,
  Cg: _Cg,
  Ck: _Ck,
  Co: _Co,
  Km: _Km,
  Cv: _Cv,
  Cr: _Cr,
  Cu: _Cu,
  Cw: _Cw,
  Cx: _Cx,
  Ky: _Ky,
  Cy: _Cy,
  Cz: _Cz,
  De: _De,
  Dj: _Dj,
  Dm: _Dm,
  Dk: _Dk,
  Do: _Do,
  Dz: _Dz,
  Ec: _Ec,
  Eg: _Eg,
  Er: _Er,
  Eh: _Eh,
  Es: _Es,
  Ee: _Ee,
  Et: _Et,
  Fi: _Fi,
  Fj: _Fj,
  Fk: _Fk,
  Fr: _Fr,
  Fo: _Fo,
  Fm: _Fm,
  Ga: _Ga,
  Gb: _Gb,
  Ge: _Ge,
  Gg: _Gg,
  Gh: _Gh,
  Gi: _Gi,
  Gn: _Gn,
  Gp: _Gp,
  Gm: _Gm,
  Gw: _Gw,
  Gq: _Gq,
  Gr: _Gr,
  Gd: _Gd,
  Gl: _Gl,
  Gt: _Gt,
  Gf: _Gf,
  Gu: _Gu,
  Gy: _Gy,
  Hk: _Hk,
  Hm: _Hm,
  Hn: _Hn,
  Hr: _Hr,
  Ht: _Ht,
  Hu: _Hu,
  Id: _Id,
  Im: _Im,
  In: _In,
  Io: _Io,
  Ie: _Ie,
  Ir: _Ir,
  Iq: _Iq,
  Is: _Is,
  Il: _Il,
  It: _It,
  Jm: _Jm,
  Je: _Je,
  Jo: _Jo,
  Jp: _Jp,
  Kz: _Kz,
  Ke: _Ke,
  Kg: _Kg,
  Kh: _Kh,
  Ki: _Ki,
  Kn: _Kn,
  Kr: _Kr,
  Kw: _Kw,
  La: _La,
  Lb: _Lb,
  Lr: _Lr,
  Ly: _Ly,
  Lc: _Lc,
  Li: _Li,
  Lk: _Lk,
  Ls: _Ls,
  Lt: _Lt,
  Lu: _Lu,
  Lv: _Lv,
  Mo: _Mo,
  Mf: _Mf,
  Ma: _Ma,
  Mc: _Mc,
  Md: _Md,
  Mg: _Mg,
  Mv: _Mv,
  Mx: _Mx,
  Mh: _Mh,
  Mk: _Mk,
  Ml: _Ml,
  Mt: _Mt,
  Mm: _Mm,
  Me: _Me,
  Mn: _Mn,
  Mp: _Mp,
  Mz: _Mz,
  Mr: _Mr,
  Ms: _Ms,
  Mq: _Mq,
  Mu: _Mu,
  Mw: _Mw,
  My: _My,
  Yt: _Yt,
  Na: _Na,
  Nc: _Nc,
  Ne: _Ne,
  Nf: _Nf,
  Ng: _Ng,
  Ni: _Ni,
  Nu: _Nu,
  Nl: _Nl,
  No: _No,
  Np: _Np,
  Nr: _Nr,
  Nz: _Nz,
  Om: _Om,
  Pk: _Pk,
  Pa: _Pa,
  Pn: _Pn,
  Pe: _Pe,
  Ph: _Ph,
  Pw: _Pw,
  Pg: _Pg,
  Pl: _Pl,
  Pr: _Pr,
  Kp: _Kp,
  Pt: _Pt,
  Py: _Py,
  Ps: _Ps,
  Pf: _Pf,
  Qa: _Qa,
  Re: _Re,
  Ro: _Ro,
  Ru: _Ru,
  Rw: _Rw,
  Sa: _Sa,
  Sd: _Sd,
  Sn: _Sn,
  Sg: _Sg,
  Gs: _Gs,
  Sh: _Sh,
  Sj: _Sj,
  Sb: _Sb,
  Sl: _Sl,
  Sv: _Sv,
  Sm: _Sm,
  So: _So,
  Pm: _Pm,
  Rs: _Rs,
  Ss: _Ss,
  St: _St,
  Sr: _Sr,
  Sk: _Sk,
  Si: _Si,
  Se: _Se,
  Sz: _Sz,
  Sx: _Sx,
  Sc: _Sc,
  Sy: _Sy,
  Tc: _Tc,
  Td: _Td,
  Tg: _Tg,
  Th: _Th,
  Tj: _Tj,
  Tk: _Tk,
  Tm: _Tm,
  Tl: _Tl,
  To: _To,
  Tt: _Tt,
  Tn: _Tn,
  Tr: _Tr,
  Tv: _Tv,
  Tw: _Tw,
  Tz: _Tz,
  Ug: _Ug,
  Ua: _Ua,
  Um: _Um,
  Uy: _Uy,
  Us: _Us,
  Uz: _Uz,
  Va: _Va,
  Vc: _Vc,
  Ve: _Ve,
  Vg: _Vg,
  Vi: _Vi,
  Vn: _Vn,
  Vu: _Vu,
  Wf: _Wf,
  Ws: _Ws,
  Ye: _Ye,
  Za: _Za,
  Zm: _Zm,
  Zw: _Zw,
  _parse: (value: string): CountryCode => {
    switch (value) {
      case "AW": {
        return _Aw;
      }
      case "AF": {
        return _Af;
      }
      case "AO": {
        return _Ao;
      }
      case "AI": {
        return _Ai;
      }
      case "AX": {
        return _Ax;
      }
      case "AL": {
        return _Al;
      }
      case "AD": {
        return _Ad;
      }
      case "AE": {
        return _Ae;
      }
      case "AR": {
        return _Ar;
      }
      case "AM": {
        return _Am;
      }
      case "AS": {
        return _As;
      }
      case "AQ": {
        return _Aq;
      }
      case "TF": {
        return _Tf;
      }
      case "AG": {
        return _Ag;
      }
      case "AU": {
        return _Au;
      }
      case "AT": {
        return _At;
      }
      case "AZ": {
        return _Az;
      }
      case "BI": {
        return _Bi;
      }
      case "BE": {
        return _Be;
      }
      case "BJ": {
        return _Bj;
      }
      case "BQ": {
        return _Bq;
      }
      case "BF": {
        return _Bf;
      }
      case "BD": {
        return _Bd;
      }
      case "BG": {
        return _Bg;
      }
      case "BH": {
        return _Bh;
      }
      case "BS": {
        return _Bs;
      }
      case "BA": {
        return _Ba;
      }
      case "BL": {
        return _Bl;
      }
      case "BY": {
        return _By;
      }
      case "BZ": {
        return _Bz;
      }
      case "BM": {
        return _Bm;
      }
      case "BO": {
        return _Bo;
      }
      case "BR": {
        return _Br;
      }
      case "BB": {
        return _Bb;
      }
      case "BN": {
        return _Bn;
      }
      case "BT": {
        return _Bt;
      }
      case "BV": {
        return _Bv;
      }
      case "BW": {
        return _Bw;
      }
      case "CF": {
        return _Cf;
      }
      case "CA": {
        return _Ca;
      }
      case "CC": {
        return _Cc;
      }
      case "CH": {
        return _Ch;
      }
      case "CL": {
        return _Cl;
      }
      case "CN": {
        return _Cn;
      }
      case "CI": {
        return _Ci;
      }
      case "CM": {
        return _Cm;
      }
      case "CD": {
        return _Cd;
      }
      case "CG": {
        return _Cg;
      }
      case "CK": {
        return _Ck;
      }
      case "CO": {
        return _Co;
      }
      case "KM": {
        return _Km;
      }
      case "CV": {
        return _Cv;
      }
      case "CR": {
        return _Cr;
      }
      case "CU": {
        return _Cu;
      }
      case "CW": {
        return _Cw;
      }
      case "CX": {
        return _Cx;
      }
      case "KY": {
        return _Ky;
      }
      case "CY": {
        return _Cy;
      }
      case "CZ": {
        return _Cz;
      }
      case "DE": {
        return _De;
      }
      case "DJ": {
        return _Dj;
      }
      case "DM": {
        return _Dm;
      }
      case "DK": {
        return _Dk;
      }
      case "DO": {
        return _Do;
      }
      case "DZ": {
        return _Dz;
      }
      case "EC": {
        return _Ec;
      }
      case "EG": {
        return _Eg;
      }
      case "ER": {
        return _Er;
      }
      case "EH": {
        return _Eh;
      }
      case "ES": {
        return _Es;
      }
      case "EE": {
        return _Ee;
      }
      case "ET": {
        return _Et;
      }
      case "FI": {
        return _Fi;
      }
      case "FJ": {
        return _Fj;
      }
      case "FK": {
        return _Fk;
      }
      case "FR": {
        return _Fr;
      }
      case "FO": {
        return _Fo;
      }
      case "FM": {
        return _Fm;
      }
      case "GA": {
        return _Ga;
      }
      case "GB": {
        return _Gb;
      }
      case "GE": {
        return _Ge;
      }
      case "GG": {
        return _Gg;
      }
      case "GH": {
        return _Gh;
      }
      case "GI": {
        return _Gi;
      }
      case "GN": {
        return _Gn;
      }
      case "GP": {
        return _Gp;
      }
      case "GM": {
        return _Gm;
      }
      case "GW": {
        return _Gw;
      }
      case "GQ": {
        return _Gq;
      }
      case "GR": {
        return _Gr;
      }
      case "GD": {
        return _Gd;
      }
      case "GL": {
        return _Gl;
      }
      case "GT": {
        return _Gt;
      }
      case "GF": {
        return _Gf;
      }
      case "GU": {
        return _Gu;
      }
      case "GY": {
        return _Gy;
      }
      case "HK": {
        return _Hk;
      }
      case "HM": {
        return _Hm;
      }
      case "HN": {
        return _Hn;
      }
      case "HR": {
        return _Hr;
      }
      case "HT": {
        return _Ht;
      }
      case "HU": {
        return _Hu;
      }
      case "ID": {
        return _Id;
      }
      case "IM": {
        return _Im;
      }
      case "IN": {
        return _In;
      }
      case "IO": {
        return _Io;
      }
      case "IE": {
        return _Ie;
      }
      case "IR": {
        return _Ir;
      }
      case "IQ": {
        return _Iq;
      }
      case "IS": {
        return _Is;
      }
      case "IL": {
        return _Il;
      }
      case "IT": {
        return _It;
      }
      case "JM": {
        return _Jm;
      }
      case "JE": {
        return _Je;
      }
      case "JO": {
        return _Jo;
      }
      case "JP": {
        return _Jp;
      }
      case "KZ": {
        return _Kz;
      }
      case "KE": {
        return _Ke;
      }
      case "KG": {
        return _Kg;
      }
      case "KH": {
        return _Kh;
      }
      case "KI": {
        return _Ki;
      }
      case "KN": {
        return _Kn;
      }
      case "KR": {
        return _Kr;
      }
      case "KW": {
        return _Kw;
      }
      case "LA": {
        return _La;
      }
      case "LB": {
        return _Lb;
      }
      case "LR": {
        return _Lr;
      }
      case "LY": {
        return _Ly;
      }
      case "LC": {
        return _Lc;
      }
      case "LI": {
        return _Li;
      }
      case "LK": {
        return _Lk;
      }
      case "LS": {
        return _Ls;
      }
      case "LT": {
        return _Lt;
      }
      case "LU": {
        return _Lu;
      }
      case "LV": {
        return _Lv;
      }
      case "MO": {
        return _Mo;
      }
      case "MF": {
        return _Mf;
      }
      case "MA": {
        return _Ma;
      }
      case "MC": {
        return _Mc;
      }
      case "MD": {
        return _Md;
      }
      case "MG": {
        return _Mg;
      }
      case "MV": {
        return _Mv;
      }
      case "MX": {
        return _Mx;
      }
      case "MH": {
        return _Mh;
      }
      case "MK": {
        return _Mk;
      }
      case "ML": {
        return _Ml;
      }
      case "MT": {
        return _Mt;
      }
      case "MM": {
        return _Mm;
      }
      case "ME": {
        return _Me;
      }
      case "MN": {
        return _Mn;
      }
      case "MP": {
        return _Mp;
      }
      case "MZ": {
        return _Mz;
      }
      case "MR": {
        return _Mr;
      }
      case "MS": {
        return _Ms;
      }
      case "MQ": {
        return _Mq;
      }
      case "MU": {
        return _Mu;
      }
      case "MW": {
        return _Mw;
      }
      case "MY": {
        return _My;
      }
      case "YT": {
        return _Yt;
      }
      case "NA": {
        return _Na;
      }
      case "NC": {
        return _Nc;
      }
      case "NE": {
        return _Ne;
      }
      case "NF": {
        return _Nf;
      }
      case "NG": {
        return _Ng;
      }
      case "NI": {
        return _Ni;
      }
      case "NU": {
        return _Nu;
      }
      case "NL": {
        return _Nl;
      }
      case "NO": {
        return _No;
      }
      case "NP": {
        return _Np;
      }
      case "NR": {
        return _Nr;
      }
      case "NZ": {
        return _Nz;
      }
      case "OM": {
        return _Om;
      }
      case "PK": {
        return _Pk;
      }
      case "PA": {
        return _Pa;
      }
      case "PN": {
        return _Pn;
      }
      case "PE": {
        return _Pe;
      }
      case "PH": {
        return _Ph;
      }
      case "PW": {
        return _Pw;
      }
      case "PG": {
        return _Pg;
      }
      case "PL": {
        return _Pl;
      }
      case "PR": {
        return _Pr;
      }
      case "KP": {
        return _Kp;
      }
      case "PT": {
        return _Pt;
      }
      case "PY": {
        return _Py;
      }
      case "PS": {
        return _Ps;
      }
      case "PF": {
        return _Pf;
      }
      case "QA": {
        return _Qa;
      }
      case "RE": {
        return _Re;
      }
      case "RO": {
        return _Ro;
      }
      case "RU": {
        return _Ru;
      }
      case "RW": {
        return _Rw;
      }
      case "SA": {
        return _Sa;
      }
      case "SD": {
        return _Sd;
      }
      case "SN": {
        return _Sn;
      }
      case "SG": {
        return _Sg;
      }
      case "GS": {
        return _Gs;
      }
      case "SH": {
        return _Sh;
      }
      case "SJ": {
        return _Sj;
      }
      case "SB": {
        return _Sb;
      }
      case "SL": {
        return _Sl;
      }
      case "SV": {
        return _Sv;
      }
      case "SM": {
        return _Sm;
      }
      case "SO": {
        return _So;
      }
      case "PM": {
        return _Pm;
      }
      case "RS": {
        return _Rs;
      }
      case "SS": {
        return _Ss;
      }
      case "ST": {
        return _St;
      }
      case "SR": {
        return _Sr;
      }
      case "SK": {
        return _Sk;
      }
      case "SI": {
        return _Si;
      }
      case "SE": {
        return _Se;
      }
      case "SZ": {
        return _Sz;
      }
      case "SX": {
        return _Sx;
      }
      case "SC": {
        return _Sc;
      }
      case "SY": {
        return _Sy;
      }
      case "TC": {
        return _Tc;
      }
      case "TD": {
        return _Td;
      }
      case "TG": {
        return _Tg;
      }
      case "TH": {
        return _Th;
      }
      case "TJ": {
        return _Tj;
      }
      case "TK": {
        return _Tk;
      }
      case "TM": {
        return _Tm;
      }
      case "TL": {
        return _Tl;
      }
      case "TO": {
        return _To;
      }
      case "TT": {
        return _Tt;
      }
      case "TN": {
        return _Tn;
      }
      case "TR": {
        return _Tr;
      }
      case "TV": {
        return _Tv;
      }
      case "TW": {
        return _Tw;
      }
      case "TZ": {
        return _Tz;
      }
      case "UG": {
        return _Ug;
      }
      case "UA": {
        return _Ua;
      }
      case "UM": {
        return _Um;
      }
      case "UY": {
        return _Uy;
      }
      case "US": {
        return _Us;
      }
      case "UZ": {
        return _Uz;
      }
      case "VA": {
        return _Va;
      }
      case "VC": {
        return _Vc;
      }
      case "VE": {
        return _Ve;
      }
      case "VG": {
        return _Vg;
      }
      case "VI": {
        return _Vi;
      }
      case "VN": {
        return _Vn;
      }
      case "VU": {
        return _Vu;
      }
      case "WF": {
        return _Wf;
      }
      case "WS": {
        return _Ws;
      }
      case "YE": {
        return _Ye;
      }
      case "ZA": {
        return _Za;
      }
      case "ZM": {
        return _Zm;
      }
      case "ZW": {
        return _Zw;
      }
      default: {
        return {
          value: value as CountryCode.RawValue,
          visit: (visitor) => visitor._other(value),
        };
      }
    }
  },
} as const;

export declare namespace CountryCode {
  type RawValue =
    | "AW"
    | "AF"
    | "AO"
    | "AI"
    | "AX"
    | "AL"
    | "AD"
    | "AE"
    | "AR"
    | "AM"
    | "AS"
    | "AQ"
    | "TF"
    | "AG"
    | "AU"
    | "AT"
    | "AZ"
    | "BI"
    | "BE"
    | "BJ"
    | "BQ"
    | "BF"
    | "BD"
    | "BG"
    | "BH"
    | "BS"
    | "BA"
    | "BL"
    | "BY"
    | "BZ"
    | "BM"
    | "BO"
    | "BR"
    | "BB"
    | "BN"
    | "BT"
    | "BV"
    | "BW"
    | "CF"
    | "CA"
    | "CC"
    | "CH"
    | "CL"
    | "CN"
    | "CI"
    | "CM"
    | "CD"
    | "CG"
    | "CK"
    | "CO"
    | "KM"
    | "CV"
    | "CR"
    | "CU"
    | "CW"
    | "CX"
    | "KY"
    | "CY"
    | "CZ"
    | "DE"
    | "DJ"
    | "DM"
    | "DK"
    | "DO"
    | "DZ"
    | "EC"
    | "EG"
    | "ER"
    | "EH"
    | "ES"
    | "EE"
    | "ET"
    | "FI"
    | "FJ"
    | "FK"
    | "FR"
    | "FO"
    | "FM"
    | "GA"
    | "GB"
    | "GE"
    | "GG"
    | "GH"
    | "GI"
    | "GN"
    | "GP"
    | "GM"
    | "GW"
    | "GQ"
    | "GR"
    | "GD"
    | "GL"
    | "GT"
    | "GF"
    | "GU"
    | "GY"
    | "HK"
    | "HM"
    | "HN"
    | "HR"
    | "HT"
    | "HU"
    | "ID"
    | "IM"
    | "IN"
    | "IO"
    | "IE"
    | "IR"
    | "IQ"
    | "IS"
    | "IL"
    | "IT"
    | "JM"
    | "JE"
    | "JO"
    | "JP"
    | "KZ"
    | "KE"
    | "KG"
    | "KH"
    | "KI"
    | "KN"
    | "KR"
    | "KW"
    | "LA"
    | "LB"
    | "LR"
    | "LY"
    | "LC"
    | "LI"
    | "LK"
    | "LS"
    | "LT"
    | "LU"
    | "LV"
    | "MO"
    | "MF"
    | "MA"
    | "MC"
    | "MD"
    | "MG"
    | "MV"
    | "MX"
    | "MH"
    | "MK"
    | "ML"
    | "MT"
    | "MM"
    | "ME"
    | "MN"
    | "MP"
    | "MZ"
    | "MR"
    | "MS"
    | "MQ"
    | "MU"
    | "MW"
    | "MY"
    | "YT"
    | "NA"
    | "NC"
    | "NE"
    | "NF"
    | "NG"
    | "NI"
    | "NU"
    | "NL"
    | "NO"
    | "NP"
    | "NR"
    | "NZ"
    | "OM"
    | "PK"
    | "PA"
    | "PN"
    | "PE"
    | "PH"
    | "PW"
    | "PG"
    | "PL"
    | "PR"
    | "KP"
    | "PT"
    | "PY"
    | "PS"
    | "PF"
    | "QA"
    | "RE"
    | "RO"
    | "RU"
    | "RW"
    | "SA"
    | "SD"
    | "SN"
    | "SG"
    | "GS"
    | "SH"
    | "SJ"
    | "SB"
    | "SL"
    | "SV"
    | "SM"
    | "SO"
    | "PM"
    | "RS"
    | "SS"
    | "ST"
    | "SR"
    | "SK"
    | "SI"
    | "SE"
    | "SZ"
    | "SX"
    | "SC"
    | "SY"
    | "TC"
    | "TD"
    | "TG"
    | "TH"
    | "TJ"
    | "TK"
    | "TM"
    | "TL"
    | "TO"
    | "TT"
    | "TN"
    | "TR"
    | "TV"
    | "TW"
    | "TZ"
    | "UG"
    | "UA"
    | "UM"
    | "UY"
    | "US"
    | "UZ"
    | "VA"
    | "VC"
    | "VE"
    | "VG"
    | "VI"
    | "VN"
    | "VU"
    | "WF"
    | "WS"
    | "YE"
    | "ZA"
    | "ZM"
    | "ZW";

  interface _Visitor<Result> {
    aw: () => Result;
    af: () => Result;
    ao: () => Result;
    ai: () => Result;
    ax: () => Result;
    al: () => Result;
    ad: () => Result;
    ae: () => Result;
    ar: () => Result;
    am: () => Result;
    as: () => Result;
    aq: () => Result;
    tf: () => Result;
    ag: () => Result;
    au: () => Result;
    at: () => Result;
    az: () => Result;
    bi: () => Result;
    be: () => Result;
    bj: () => Result;
    bq: () => Result;
    bf: () => Result;
    bd: () => Result;
    bg: () => Result;
    bh: () => Result;
    bs: () => Result;
    ba: () => Result;
    bl: () => Result;
    by: () => Result;
    bz: () => Result;
    bm: () => Result;
    bo: () => Result;
    br: () => Result;
    bb: () => Result;
    bn: () => Result;
    bt: () => Result;
    bv: () => Result;
    bw: () => Result;
    cf: () => Result;
    ca: () => Result;
    cc: () => Result;
    ch: () => Result;
    cl: () => Result;
    cn: () => Result;
    ci: () => Result;
    cm: () => Result;
    cd: () => Result;
    cg: () => Result;
    ck: () => Result;
    co: () => Result;
    km: () => Result;
    cv: () => Result;
    cr: () => Result;
    cu: () => Result;
    cw: () => Result;
    cx: () => Result;
    ky: () => Result;
    cy: () => Result;
    cz: () => Result;
    de: () => Result;
    dj: () => Result;
    dm: () => Result;
    dk: () => Result;
    do: () => Result;
    dz: () => Result;
    ec: () => Result;
    eg: () => Result;
    er: () => Result;
    eh: () => Result;
    es: () => Result;
    ee: () => Result;
    et: () => Result;
    fi: () => Result;
    fj: () => Result;
    fk: () => Result;
    fr: () => Result;
    fo: () => Result;
    fm: () => Result;
    ga: () => Result;
    gb: () => Result;
    ge: () => Result;
    gg: () => Result;
    gh: () => Result;
    gi: () => Result;
    gn: () => Result;
    gp: () => Result;
    gm: () => Result;
    gw: () => Result;
    gq: () => Result;
    gr: () => Result;
    gd: () => Result;
    gl: () => Result;
    gt: () => Result;
    gf: () => Result;
    gu: () => Result;
    gy: () => Result;
    hk: () => Result;
    hm: () => Result;
    hn: () => Result;
    hr: () => Result;
    ht: () => Result;
    hu: () => Result;
    id: () => Result;
    im: () => Result;
    in: () => Result;
    io: () => Result;
    ie: () => Result;
    ir: () => Result;
    iq: () => Result;
    is: () => Result;
    il: () => Result;
    it: () => Result;
    jm: () => Result;
    je: () => Result;
    jo: () => Result;
    jp: () => Result;
    kz: () => Result;
    ke: () => Result;
    kg: () => Result;
    kh: () => Result;
    ki: () => Result;
    kn: () => Result;
    kr: () => Result;
    kw: () => Result;
    la: () => Result;
    lb: () => Result;
    lr: () => Result;
    ly: () => Result;
    lc: () => Result;
    li: () => Result;
    lk: () => Result;
    ls: () => Result;
    lt: () => Result;
    lu: () => Result;
    lv: () => Result;
    mo: () => Result;
    mf: () => Result;
    ma: () => Result;
    mc: () => Result;
    md: () => Result;
    mg: () => Result;
    mv: () => Result;
    mx: () => Result;
    mh: () => Result;
    mk: () => Result;
    ml: () => Result;
    mt: () => Result;
    mm: () => Result;
    me: () => Result;
    mn: () => Result;
    mp: () => Result;
    mz: () => Result;
    mr: () => Result;
    ms: () => Result;
    mq: () => Result;
    mu: () => Result;
    mw: () => Result;
    my: () => Result;
    yt: () => Result;
    na: () => Result;
    nc: () => Result;
    ne: () => Result;
    nf: () => Result;
    ng: () => Result;
    ni: () => Result;
    nu: () => Result;
    nl: () => Result;
    no: () => Result;
    np: () => Result;
    nr: () => Result;
    nz: () => Result;
    om: () => Result;
    pk: () => Result;
    pa: () => Result;
    pn: () => Result;
    pe: () => Result;
    ph: () => Result;
    pw: () => Result;
    pg: () => Result;
    pl: () => Result;
    pr: () => Result;
    kp: () => Result;
    pt: () => Result;
    py: () => Result;
    ps: () => Result;
    pf: () => Result;
    qa: () => Result;
    re: () => Result;
    ro: () => Result;
    ru: () => Result;
    rw: () => Result;
    sa: () => Result;
    sd: () => Result;
    sn: () => Result;
    sg: () => Result;
    gs: () => Result;
    sh: () => Result;
    sj: () => Result;
    sb: () => Result;
    sl: () => Result;
    sv: () => Result;
    sm: () => Result;
    so: () => Result;
    pm: () => Result;
    rs: () => Result;
    ss: () => Result;
    st: () => Result;
    sr: () => Result;
    sk: () => Result;
    si: () => Result;
    se: () => Result;
    sz: () => Result;
    sx: () => Result;
    sc: () => Result;
    sy: () => Result;
    tc: () => Result;
    td: () => Result;
    tg: () => Result;
    th: () => Result;
    tj: () => Result;
    tk: () => Result;
    tm: () => Result;
    tl: () => Result;
    to: () => Result;
    tt: () => Result;
    tn: () => Result;
    tr: () => Result;
    tv: () => Result;
    tw: () => Result;
    tz: () => Result;
    ug: () => Result;
    ua: () => Result;
    um: () => Result;
    uy: () => Result;
    us: () => Result;
    uz: () => Result;
    va: () => Result;
    vc: () => Result;
    ve: () => Result;
    vg: () => Result;
    vi: () => Result;
    vn: () => Result;
    vu: () => Result;
    wf: () => Result;
    ws: () => Result;
    ye: () => Result;
    za: () => Result;
    zm: () => Result;
    zw: () => Result;
    _other: (value: string) => Result;
  }
}
