/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const ApayaCustomerTokenApiSchema: core.schemas.ObjectSchema<
  serializers.ApayaCustomerTokenApiSchema.Raw,
  PrimerPrimerApi.ApayaCustomerTokenApiSchema
> = core.schemas.object({
  mx: core.schemas.string(),
  mnc: core.schemas.number().optional(),
  mcc: core.schemas.number().optional(),
});

export declare namespace ApayaCustomerTokenApiSchema {
  interface Raw {
    mx: string;
    mnc?: number | null;
    mcc?: number | null;
  }
}
