/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const CapturePaymentRequest: core.schemas.ObjectSchema<
  CapturePaymentRequest.Raw,
  PrimerApi.payments.CapturePaymentRequest
> = core.schemas.object({
  amount: core.schemas.number().optional(),
  final: core.schemas.boolean().optional(),
});

export declare namespace CapturePaymentRequest {
  interface Raw {
    amount?: number | null;
    final?: boolean | null;
  }
}
