/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const CreatePaymentRequest: core.schemas.ObjectSchema<
  CreatePaymentRequest.Raw,
  PrimerApi.payments.CreatePaymentRequest
> = core.schemas.object({
  orderId: core.schemas.lazy(() => serializers.commons.OrderId).optional(),
  currencyCode: core.schemas.lazy(() => serializers.commons.CurrencyCode).optional(),
  amount: core.schemas.number().optional(),
  order: core.schemas.lazyObject(() => serializers.clientSession.OrderDetails).optional(),
  paymentMethodToken: core.schemas.string(),
  customerId: core.schemas.lazy(() => serializers.commons.CustomerId).optional(),
  customer: core.schemas.lazyObject(() => serializers.clientSession.CustomerDetails).optional(),
  metadata: core.schemas.record(core.schemas.string(), core.schemas.unknown()).optional(),
  paymentMethod: core.schemas.lazyObject(() => serializers.clientSession.ClientPaymentMethod).optional(),
});

export declare namespace CreatePaymentRequest {
  interface Raw {
    orderId?: serializers.commons.OrderId.Raw | null;
    currencyCode?: serializers.commons.CurrencyCode.Raw | null;
    amount?: number | null;
    order?: serializers.clientSession.OrderDetails.Raw | null;
    paymentMethodToken: string;
    customerId?: serializers.commons.CustomerId.Raw | null;
    customer?: serializers.clientSession.CustomerDetails.Raw | null;
    metadata?: Record<string, unknown> | null;
    paymentMethod?: serializers.clientSession.ClientPaymentMethod.Raw | null;
  }
}
