/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const ExternalPayerInfo: core.schemas.ObjectSchema<
  serializers.ExternalPayerInfo.Raw,
  PrimerPrimerApi.ExternalPayerInfo
> = core.schemas.object({
  externalPayerId: core.schemas.string().optional(),
  email: core.schemas.string().optional(),
  firstName: core.schemas.string().optional(),
  lastName: core.schemas.string().optional(),
});

export declare namespace ExternalPayerInfo {
  interface Raw {
    externalPayerId?: string | null;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
  }
}
