/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const GoCardlessMandateSchema: core.schemas.ObjectSchema<
  GoCardlessMandateSchema.Raw,
  PrimerApi.payments.GoCardlessMandateSchema
> = core.schemas.object({
  paymentMethodData: core.schemas.lazyObject(() => serializers.payments.GoCardlessMandateAPISchema),
  descriptor: core.schemas.string().optional(),
  paymentMethodToken: core.schemas.string().optional(),
  isVaulted: core.schemas.boolean().optional(),
  analyticsId: core.schemas.string().optional(),
  threeDSecureAuthentication: core.schemas.lazyObject(() => serializers.payments.ThreeDSecureAuthentication).optional(),
});

export declare namespace GoCardlessMandateSchema {
  interface Raw {
    paymentMethodData: serializers.payments.GoCardlessMandateAPISchema.Raw;
    descriptor?: string | null;
    paymentMethodToken?: string | null;
    isVaulted?: boolean | null;
    analyticsId?: string | null;
    threeDSecureAuthentication?: serializers.payments.ThreeDSecureAuthentication.Raw | null;
  }
}
