/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const GoCardlessMandateApiSchema: core.schemas.ObjectSchema<
  serializers.GoCardlessMandateApiSchema.Raw,
  PrimerPrimerApi.GoCardlessMandateApiSchema
> = core.schemas.object({
  gocardlessMandateId: core.schemas.string(),
});

export declare namespace GoCardlessMandateApiSchema {
  interface Raw {
    gocardlessMandateId: string;
  }
}
