/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const KlarnaPaymentSessionApiSchema: core.schemas.ObjectSchema<
  serializers.KlarnaPaymentSessionApiSchema.Raw,
  PrimerPrimerApi.KlarnaPaymentSessionApiSchema
> = core.schemas.object({
  klarnaAuthorizationToken: core.schemas.string(),
  sessionData: core.schemas.lazyObject(async () => (await import("../..")).KlarnaSessionDetails),
});

export declare namespace KlarnaPaymentSessionApiSchema {
  interface Raw {
    klarnaAuthorizationToken: string;
    sessionData: serializers.KlarnaSessionDetails.Raw;
  }
}
