/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const KlarnaAddress: core.schemas.ObjectSchema<serializers.KlarnaAddress.Raw, PrimerPrimerApi.KlarnaAddress> =
  core.schemas.object({
    title: core.schemas.string().optional(),
    email: core.schemas.string().optional(),
    phoneNumber: core.schemas.string().optional(),
    firstName: core.schemas.string().optional(),
    lastName: core.schemas.string().optional(),
    addressLine1: core.schemas.string().optional(),
    addressLine2: core.schemas.string().optional(),
    addressLine3: core.schemas.string().optional(),
    city: core.schemas.string().optional(),
    state: core.schemas.string().optional(),
    countryCode: core.schemas.lazy(async () => (await import("../..")).CountryCode).optional(),
    postalCode: core.schemas.string().optional(),
  });

export declare namespace KlarnaAddress {
  interface Raw {
    title?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    addressLine3?: string | null;
    city?: string | null;
    state?: string | null;
    countryCode?: serializers.CountryCode.Raw | null;
    postalCode?: string | null;
  }
}
