/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const KlarnaCustomerTokenApiSchema: core.schemas.ObjectSchema<
  serializers.KlarnaCustomerTokenApiSchema.Raw,
  PrimerPrimerApi.KlarnaCustomerTokenApiSchema
> = core.schemas.object({
  klarnaCustomerToken: core.schemas.string(),
  sessionData: core.schemas.lazyObject(async () => (await import("../..")).KlarnaSessionDetails),
});

export declare namespace KlarnaCustomerTokenApiSchema {
  interface Raw {
    klarnaCustomerToken: string;
    sessionData: serializers.KlarnaSessionDetails.Raw;
  }
}
