/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const PaymentStatus: core.schemas.Schema<serializers.PaymentStatus.Raw, PrimerPrimerApi.PaymentStatus> =
  core.schemas.enum_([
    "PENDING",
    "FAILED",
    "AUTHORIZED",
    "SETTLING",
    "PARTIALLY_SETTLED",
    "SETTLED",
    "DECLINED",
    "CANCELLED",
  ]);

export declare namespace PaymentStatus {
  type Raw =
    | "PENDING"
    | "FAILED"
    | "AUTHORIZED"
    | "SETTLING"
    | "PARTIALLY_SETTLED"
    | "SETTLED"
    | "DECLINED"
    | "CANCELLED";
}
