/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const PaymentProcessorError: core.schemas.ObjectSchema<
  PaymentProcessorError.Raw,
  PrimerApi.payments.PaymentProcessorError
> = core.schemas.object({
  type: core.schemas.lazy(() => serializers.payments.StatusReasonType),
  declineType: core.schemas.lazy(() => serializers.payments.StatusReasonDeclineType).optional(),
  code: core.schemas.lazy(() => serializers.payments.StatusReasonCode).optional(),
  message: core.schemas.string().optional(),
});

export declare namespace PaymentProcessorError {
  interface Raw {
    type: serializers.payments.StatusReasonType.Raw;
    declineType?: serializers.payments.StatusReasonDeclineType.Raw | null;
    code?: serializers.payments.StatusReasonCode.Raw | null;
    message?: string | null;
  }
}
