/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const PaymentCardTokenApiSchema: core.schemas.ObjectSchema<
  serializers.PaymentCardTokenApiSchema.Raw,
  PrimerPrimerApi.PaymentCardTokenApiSchema
> = core.schemas.object({
  first6Digits: core.schemas.string().optional(),
  last4Digits: core.schemas.string(),
  expirationMonth: core.schemas.string(),
  expirationYear: core.schemas.string(),
  cardholderName: core.schemas.string().optional(),
  network: core.schemas.string().optional(),
  isNetworkTokenized: core.schemas.boolean().optional(),
  binData: core.schemas.lazyObject(async () => (await import("../..")).BinData).optional(),
});

export declare namespace PaymentCardTokenApiSchema {
  interface Raw {
    first6Digits?: string | null;
    last4Digits: string;
    expirationMonth: string;
    expirationYear: string;
    cardholderName?: string | null;
    network?: string | null;
    isNetworkTokenized?: boolean | null;
    binData?: serializers.BinData.Raw | null;
  }
}
