/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const PayPalOrderTokenApiSchema: core.schemas.ObjectSchema<
  serializers.PayPalOrderTokenApiSchema.Raw,
  PrimerPrimerApi.PayPalOrderTokenApiSchema
> = core.schemas.object({
  paypalOrderId: core.schemas.string(),
  externalPayerInfo: core.schemas.lazyObject(async () => (await import("../..")).ExternalPayerInfo),
  paypalStatus: core.schemas.string().optional(),
});

export declare namespace PayPalOrderTokenApiSchema {
  interface Raw {
    paypalOrderId: string;
    externalPayerInfo: serializers.ExternalPayerInfo.Raw;
    paypalStatus?: string | null;
  }
}
