/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const PrepaidReloadableIndicator: core.schemas.Schema<
  serializers.PrepaidReloadableIndicator.Raw,
  PrimerPrimerApi.PrepaidReloadableIndicator
> = core.schemas.enum_(["RELOADABLE", "NON_RELOADABLE", "NOT_APPLICABLE", "UNKNOWN"]);

export declare namespace PrepaidReloadableIndicator {
  type Raw = "RELOADABLE" | "NON_RELOADABLE" | "NOT_APPLICABLE" | "UNKNOWN";
}
