/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const ProductUsageType: core.schemas.Schema<serializers.ProductUsageType.Raw, PrimerPrimerApi.ProductUsageType> =
  core.schemas.enum_(["CONSUMER", "BUSINESS", "GOVERNMENT", "UNKNOWN"]);

export declare namespace ProductUsageType {
  type Raw = "CONSUMER" | "BUSINESS" | "GOVERNMENT" | "UNKNOWN";
}
