/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const RegionalRestriction: core.schemas.Schema<RegionalRestriction.Raw, PrimerApi.payments.RegionalRestriction> =
  core.schemas.string().transform<PrimerApi.payments.RegionalRestriction>({
    parse: (value) => PrimerApi.payments.RegionalRestriction._parse(value),
    json: ({ value }) => value,
  });

export declare namespace RegionalRestriction {
  type Raw = string;
}
