/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const StatusReasonDeclineType: core.schemas.Schema<
  serializers.StatusReasonDeclineType.Raw,
  PrimerPrimerApi.StatusReasonDeclineType
> = core.schemas.enum_(["SOFT_DECLINE", "HARD_DECLINE"]);

export declare namespace StatusReasonDeclineType {
  type Raw = "SOFT_DECLINE" | "HARD_DECLINE";
}
