/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const StatusReasonCode: core.schemas.Schema<serializers.StatusReasonCode.Raw, PrimerPrimerApi.StatusReasonCode> =
  core.schemas.enum_([
    "ERROR",
    "INVALID_CARD_NUMBER",
    "EXPIRED_CARD",
    "LOST_OR_STOLEN_CARD",
    "SUSPECTED_FRAUD",
    "UNKNOWN_DECLINED",
    "REFER_TO_CARD_ISSUER",
    "DO_NOT_HONOR",
    "INSUFFICIENT_FUNDS",
    "WITHDRAWAL_LIMIT_EXCEEDED",
    "ISSUER_TEMPORARILY_UNAVAILABLE",
    "AUTHENTICATION_REQUIRED",
  ]);

export declare namespace StatusReasonCode {
  type Raw =
    | "ERROR"
    | "INVALID_CARD_NUMBER"
    | "EXPIRED_CARD"
    | "LOST_OR_STOLEN_CARD"
    | "SUSPECTED_FRAUD"
    | "UNKNOWN_DECLINED"
    | "REFER_TO_CARD_ISSUER"
    | "DO_NOT_HONOR"
    | "INSUFFICIENT_FUNDS"
    | "WITHDRAWAL_LIMIT_EXCEEDED"
    | "ISSUER_TEMPORARILY_UNAVAILABLE"
    | "AUTHENTICATION_REQUIRED";
}
