/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const StatusReason: core.schemas.ObjectSchema<serializers.StatusReason.Raw, PrimerPrimerApi.StatusReason> =
  core.schemas.object({
    type: core.schemas.lazy(async () => (await import("../..")).StatusReasonType),
    declineType: core.schemas.lazy(async () => (await import("../..")).StatusReasonDeclineType).optional(),
    code: core.schemas.lazy(async () => (await import("../..")).StatusReasonCode).optional(),
    message: core.schemas.string().optional(),
  });

export declare namespace StatusReason {
  interface Raw {
    type: serializers.StatusReasonType.Raw;
    declineType?: serializers.StatusReasonDeclineType.Raw | null;
    code?: serializers.StatusReasonCode.Raw | null;
    message?: string | null;
  }
}
