/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const StatusReasonType: core.schemas.Schema<serializers.StatusReasonType.Raw, PrimerPrimerApi.StatusReasonType> =
  core.schemas.enum_(["APPLICATION_ERROR", "GATEWAY_REJECTED", "ISSUER_DECLINED"]);

export declare namespace StatusReasonType {
  type Raw = "APPLICATION_ERROR" | "GATEWAY_REJECTED" | "ISSUER_DECLINED";
}
