/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const ThreeDSecureFailedReasonCodeEnum: core.schemas.Schema<
  serializers.ThreeDSecureFailedReasonCodeEnum.Raw,
  PrimerPrimerApi.ThreeDSecureFailedReasonCodeEnum
> = core.schemas.enum_([
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
]);

export declare namespace ThreeDSecureFailedReasonCodeEnum {
  type Raw =
    | "01"
    | "02"
    | "03"
    | "04"
    | "05"
    | "06"
    | "07"
    | "08"
    | "09"
    | "10"
    | "11"
    | "12"
    | "13"
    | "14"
    | "15"
    | "16";
}
