/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const ThreeDSecureAuthentication: core.schemas.ObjectSchema<
  serializers.ThreeDSecureAuthentication.Raw,
  PrimerPrimerApi.ThreeDSecureAuthentication
> = core.schemas.object({
  responseCode: core.schemas.lazy(async () => (await import("../..")).SecureAuthenticationResponseCode),
  reasonCode: core.schemas.lazy(async () => (await import("../..")).ThreeDSecureReasonCode).optional(),
  reasonText: core.schemas.string().optional(),
  protocolVersion: core.schemas.string().optional(),
  challengeIssued: core.schemas.boolean().optional(),
});

export declare namespace ThreeDSecureAuthentication {
  interface Raw {
    responseCode: serializers.SecureAuthenticationResponseCode.Raw;
    reasonCode?: serializers.ThreeDSecureReasonCode.Raw | null;
    reasonText?: string | null;
    protocolVersion?: string | null;
    challengeIssued?: boolean | null;
  }
}
