/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const ThreeDSecureFailedReasonCodeEnum: core.schemas.Schema<
  ThreeDSecureFailedReasonCodeEnum.Raw,
  PrimerApi.payments.ThreeDSecureFailedReasonCodeEnum
> = core.schemas.string().transform<PrimerApi.payments.ThreeDSecureFailedReasonCodeEnum>({
  parse: (value) => PrimerApi.payments.ThreeDSecureFailedReasonCodeEnum._parse(value),
  json: ({ value }) => value,
});

export declare namespace ThreeDSecureFailedReasonCodeEnum {
  type Raw = string;
}
