/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const ThreeDSecureSkippedReasonCodeEnum: core.schemas.Schema<
  ThreeDSecureSkippedReasonCodeEnum.Raw,
  PrimerApi.payments.ThreeDSecureSkippedReasonCodeEnum
> = core.schemas.string().transform<PrimerApi.payments.ThreeDSecureSkippedReasonCodeEnum>({
  parse: (value) => PrimerApi.payments.ThreeDSecureSkippedReasonCodeEnum._parse(value),
  json: ({ value }) => value,
});

export declare namespace ThreeDSecureSkippedReasonCodeEnum {
  type Raw = string;
}
