/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const TransactionType: core.schemas.Schema<TransactionType.Raw, PrimerApi.payments.TransactionType> =
  core.schemas.string().transform<PrimerApi.payments.TransactionType>({
    parse: (value) => PrimerApi.payments.TransactionType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace TransactionType {
  type Raw = string;
}
