/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";

export interface CreatePaymentRequest {
  idempotencyKey?: string;
  orderId?: PrimerPrimerApi.OrderId;
  currencyCode?: PrimerPrimerApi.CurrencyCode;
  amount?: number;
  order?: PrimerPrimerApi.OrderDetails;
  paymentMethodToken: string;
  customerId?: PrimerPrimerApi.CustomerId;
  customer?: PrimerPrimerApi.CustomerDetails;
  metadata?: Record<string, unknown>;
  paymentMethod?: PrimerPrimerApi.ClientPaymentMethod;
}
