/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RefundPaymentRequest {
  idempotencyKey?: string;
  amount?: number;
  orderId?: string;
  reason?: string;
}
