/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface ListPaymentMethodsResponse {
  data: PrimerApi.paymentMethod.PaymentMethodToken[];
}
