/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.payments.get.Response.Raw, PrimerPrimerApi.PaymentResponse> =
  core.schemas.lazyObject(async () => (await import("../..")).PaymentResponse);

export declare namespace Response {
  type Raw = serializers.PaymentResponse.Raw;
}
