/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export interface Request {
  /** ID of the payment to resume. */
  id: PrimerApi.payments.PaymentId;
  idempotencyKey?: string;
  _body: PrimerApi.payments.ResumePaymentRequest;
}

export type Response = core.APIResponse<PrimerApi.payments.PaymentResponse, PrimerApi.payments.resume.Error>;
export type Error = Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <Result>(visitor: Error._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    _other: (value: core.Fetcher.Error) => Result;
  }
}
