/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export type CardNetwork =
  | Record<PrimerApi.commons.CardNetworkType.RawValue, PrimerApi.clientSession.Surcharge>
  | undefined;
