/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface CreateClientSessionRequest {
  /** Your reference for the payment. */
  orderId?: PrimerApi.commons.OrderId;
  /**
   * The 3-letter currency code in ISO 4217 format.
   * e.g. use USD for US dollars.
   *
   */
  currencyCode?: PrimerApi.commons.CurrencyCode;
  /** The amount you would like to charge the customer, in minor units. e.g. for $7, use 700. */
  amount?: number;
  /** More information associated with the order. */
  order?: PrimerApi.clientSession.OrderDetails;
  /**
   * A unique identifier for your customer.
   * Create a client session token with a customerId to enable the client-side SDK to retrieve and manage your customer's saved payment methods. A client session token also enables saving payment methods against this customer id.
   *
   */
  customerId?: PrimerApi.commons.CustomerId;
  /** More information associated with the customer. */
  customer?: PrimerApi.clientSession.CustomerDetails;
  /**
   * Additional data to be used throughout the payment lifecycle.
   * A dictionary of key-value pairs where the values can only be strings or
   * integers.
   * e.g. {"productId": 1001, "merchantId": "a13bsd62s"}
   *
   */
  metadata?: PrimerApi.clientSession.MetadataDetails;
  /** Enable certain options associated with the payment method. */
  paymentMethod?: PrimerApi.clientSession.ClientPaymentMethod;
}
