/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface KlarnaSessionDetails {
  recurringDescription?: string;
  billingAddress: PrimerApi.payments.KlarnaAddress;
  shippingAddress?: PrimerApi.payments.KlarnaAddress;
  purchaseCountry: string;
  purchaseCurrency: string;
  locale: string;
  orderLines: unknown[];
  tokenDetails?: PrimerApi.payments.KlarnaTokenDetails;
}
