/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface PayPalOrderTokenAPISchema {
  paypalOrderId: string;
  externalPayerInfo: PrimerApi.payments.ExternalPayerInfo;
  paypalStatus?: string;
}
