/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface PrepaidReloadableIndicator<
  RawValue extends PrepaidReloadableIndicator.RawValue = PrepaidReloadableIndicator.RawValue
> {
  value: RawValue;
  visit: <Result>(visitor: PrepaidReloadableIndicator._Visitor<Result>) => Result;
}

const _Reloadable: PrepaidReloadableIndicator<"RELOADABLE"> = {
  value: "RELOADABLE",
  visit: (visitor) => visitor.reloadable(),
};
const _NonReloadable: PrepaidReloadableIndicator<"NON_RELOADABLE"> = {
  value: "NON_RELOADABLE",
  visit: (visitor) => visitor.nonReloadable(),
};
const _NotApplicable: PrepaidReloadableIndicator<"NOT_APPLICABLE"> = {
  value: "NOT_APPLICABLE",
  visit: (visitor) => visitor.notApplicable(),
};
const _Unknown: PrepaidReloadableIndicator<"UNKNOWN"> = {
  value: "UNKNOWN",
  visit: (visitor) => visitor.unknown(),
};
export const PrepaidReloadableIndicator = {
  Reloadable: _Reloadable,
  NonReloadable: _NonReloadable,
  NotApplicable: _NotApplicable,
  Unknown: _Unknown,
} as const;

export declare namespace PrepaidReloadableIndicator {
  type RawValue = "RELOADABLE" | "NON_RELOADABLE" | "NOT_APPLICABLE" | "UNKNOWN" | string;

  interface _Visitor<Result> {
    reloadable: () => Result;
    nonReloadable: () => Result;
    notApplicable: () => Result;
    unknown: () => Result;
    _other: (value: string) => Result;
  }
}
