/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface RefundPaymentRequest {
  /** The amount you would like to refund the customer, in minor units. e.g. for $7, use 700. Defaults to remaining non-refunded amount. */
  amount?: number;
  /** Optionally you can pass a specific order ID for the refund. By default this will be set to the original orderId given on payment creation. */
  orderId?: string;
  /** You can optionally specify a reason for the refund. This is for your own records. */
  reason?: string;
}
