/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface ThreeDSecureAuthentication {
  responseCode: PrimerApi.payments.SecureAuthenticationResponseCode;
  reasonCode?: PrimerApi.payments.ThreeDSecureReasonCode;
  reasonText?: string;
  protocolVersion?: string;
  challengeIssued?: boolean;
}
