/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface Transaction {
  /** Date & time of the transaction (UTC) */
  date: string;
  /** Transaction amount in minor units */
  amount: number;
  /** The 3-letter currency code in ISO 4217 format. e.g. use USD for US dollars. */
  currencyCode: PrimerApi.commons.CurrencyCode;
  type?: PrimerApi.payments.TransactionType;
  /** Processor's unique identifier for the transaction */
  processorTransactionId?: string;
  /** An identifier of a processor. */
  processorName?: string;
  /**
   * Processor's main account identifier:
   *   * Adyen: Account code
   *   * Braintree: Merchant ID
   *   * Stripe: Account ID"
   *
   */
  processorMerchantId: string;
  processorStatus?: PrimerApi.payments.PaymentStatus;
  /** If the transaction has a declined or failed status. Only if the status is `DECLINED` or `FAILED`, otherwise null. */
  processorStatusReason?: PrimerApi.payments.PaymentProcessorError;
}
