/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { PrimerApi } from "../../..";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      apiKey?: core.Supplier<string>;
    };
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async create(
    request: PrimerApi.clientSession.CreateClientSessionRequest
  ): Promise<PrimerApi.clientSession.create.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/client-session/"),
      method: "POST",
      headers: {
        "X-API-KEY": await core.Supplier.get(this.options.auth?.apiKey),
      },
      body: serializers.clientSession.CreateClientSessionRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: serializers.clientSession.ClientSession.parse(
          response.body as serializers.clientSession.ClientSession.Raw
        ),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async get(request: PrimerApi.clientSession.get.Request): Promise<PrimerApi.clientSession.get.Response> {
    const queryParameters = new URLSearchParams();
    queryParameters.append("clientToken", request.clientToken);
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/client-session/"),
      method: "GET",
      headers: {
        "X-API-KEY": await core.Supplier.get(this.options.auth?.apiKey),
      },
      queryParameters: queryParameters,
    });
    if (response.ok) {
      return {
        ok: true,
        body: serializers.clientSession.ClientSession.parse(
          response.body as serializers.clientSession.ClientSession.Raw
        ),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async update(
    request: PrimerApi.clientSession.UpdateClientSessionRequest
  ): Promise<PrimerApi.clientSession.update.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/client-session/"),
      method: "PATCH",
      headers: {
        "X-API-KEY": await core.Supplier.get(this.options.auth?.apiKey),
      },
      body: serializers.clientSession.UpdateClientSessionRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: serializers.clientSession.ClientSession.parse(
          response.body as serializers.clientSession.ClientSession.Raw
        ),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
