/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const AccountFundingType: core.schemas.Schema<
  serializers.AccountFundingType.Raw,
  PrimerPrimerApi.AccountFundingType
> = core.schemas.enum_(["CREDIT", "DEBIT", "PREPAID", "CHARGE", "DEFERRED_DEBIT", "UNKNOWN"]);

export declare namespace AccountFundingType {
  type Raw = "CREDIT" | "DEBIT" | "PREPAID" | "CHARGE" | "DEFERRED_DEBIT" | "UNKNOWN";
}
