/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const CardNetworkType: core.schemas.Schema<serializers.CardNetworkType.Raw, PrimerPrimerApi.CardNetworkType> =
  core.schemas.enum_([
    "AMEX",
    "DANKORT",
    "DINERS_CLUB",
    "DISCOVER",
    "ENROUTE",
    "ELO",
    "HIPER",
    "INTERAC",
    "JCB",
    "MAESTRO",
    "MASTERCARD",
    "MIR",
    "PRIVATE_LABEL",
    "UNIONPAY",
    "VISA",
  ]);

export declare namespace CardNetworkType {
  type Raw =
    | "AMEX"
    | "DANKORT"
    | "DINERS_CLUB"
    | "DISCOVER"
    | "ENROUTE"
    | "ELO"
    | "HIPER"
    | "INTERAC"
    | "JCB"
    | "MAESTRO"
    | "MASTERCARD"
    | "MIR"
    | "PRIVATE_LABEL"
    | "UNIONPAY"
    | "VISA";
}
