/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const CustomerId: core.schemas.Schema<serializers.CustomerId.Raw, PrimerPrimerApi.CustomerId> =
  core.schemas.string();

export declare namespace CustomerId {
  type Raw = string;
}
