/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const DiagnosticsId: core.schemas.Schema<serializers.DiagnosticsId.Raw, PrimerPrimerApi.DiagnosticsId> =
  core.schemas.string();

export declare namespace DiagnosticsId {
  type Raw = string;
}
