/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const OrderId: core.schemas.Schema<serializers.OrderId.Raw, PrimerPrimerApi.OrderId> = core.schemas.string();

export declare namespace OrderId {
  type Raw = string;
}
