/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const RequestValidationErrorBody: core.schemas.ObjectSchema<
  serializers.RequestValidationErrorBody.Raw,
  PrimerPrimerApi.RequestValidationErrorBody
> = core.schemas
  .object({
    validationErrors: core.schemas.unknown(),
  })
  .extend(core.schemas.lazyObject(async () => (await import("../..")).BaseErrorBody));

export declare namespace RequestValidationErrorBody {
  interface Raw extends serializers.BaseErrorBody.Raw {
    validationErrors?: unknown;
  }
}
