/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const ShippingAddress: core.schemas.ObjectSchema<
  serializers.ShippingAddress.Raw,
  PrimerPrimerApi.ShippingAddress
> = core.schemas.object({
  firstName: core.schemas.string().optional(),
  lastName: core.schemas.string().optional(),
  addressLine1: core.schemas.string().optional(),
  addressLine2: core.schemas.string().optional(),
  city: core.schemas.string().optional(),
  state: core.schemas.string().optional(),
  countryCode: core.schemas.lazy(async () => (await import("../..")).CountryCode).optional(),
  postalCode: core.schemas.string().optional(),
});

export declare namespace ShippingAddress {
  interface Raw {
    firstName?: string | null;
    lastName?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    countryCode?: serializers.CountryCode.Raw | null;
    postalCode?: string | null;
  }
}
