/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const SupportedPaymentMethods: core.schemas.Schema<
  serializers.SupportedPaymentMethods.Raw,
  PrimerPrimerApi.SupportedPaymentMethods
> = core.schemas.enum_([
  "PAYMENT_CARD",
  "GOOGLE_PAY",
  "APPLE_PAY",
  "PAYPAL",
  "GOCARDLESS",
  "KLARNA",
  "APAYA",
  "HOOLAH",
  "ATOME",
  "PAY_NL_IDEAL",
  "PAY_NL_BANCONTACT",
  "PAY_NL_DIRECT_DEBIT",
  "PAY_NL_SOFORT_BANKING",
  "PAY_NL_PAYPAL",
  "PAY_NL_PAYCONIQ",
  "PAY_NL_GIROPAY",
  "ADYEN_SOFORT",
  "ADYEN_TWINT",
  "ADYEN_GIROPAY",
  "ADYEN_TRUSTLY",
  "ADYEN_ALIPAY",
  "ADYEN_MOBILEPAY",
  "ADYEN_VIPPS",
  "ADYEN_DOTPAY",
  "ADYEN_IDEAL",
  "MOLLIE_IDEAL",
  "MOLLIE_BANCONTACT",
  "BUCKAROO_IDEAL",
  "BUCKAROO_BANCONTACT",
  "BUCKAROO_SOFORT",
  "BUCKAROO_GIROPAY",
  "BUCKAROO_EPS",
  "XFERS_PAYNOW",
]);

export declare namespace SupportedPaymentMethods {
  type Raw =
    | "PAYMENT_CARD"
    | "GOOGLE_PAY"
    | "APPLE_PAY"
    | "PAYPAL"
    | "GOCARDLESS"
    | "KLARNA"
    | "APAYA"
    | "HOOLAH"
    | "ATOME"
    | "PAY_NL_IDEAL"
    | "PAY_NL_BANCONTACT"
    | "PAY_NL_DIRECT_DEBIT"
    | "PAY_NL_SOFORT_BANKING"
    | "PAY_NL_PAYPAL"
    | "PAY_NL_PAYCONIQ"
    | "PAY_NL_GIROPAY"
    | "ADYEN_SOFORT"
    | "ADYEN_TWINT"
    | "ADYEN_GIROPAY"
    | "ADYEN_TRUSTLY"
    | "ADYEN_ALIPAY"
    | "ADYEN_MOBILEPAY"
    | "ADYEN_VIPPS"
    | "ADYEN_DOTPAY"
    | "ADYEN_IDEAL"
    | "MOLLIE_IDEAL"
    | "MOLLIE_BANCONTACT"
    | "BUCKAROO_IDEAL"
    | "BUCKAROO_BANCONTACT"
    | "BUCKAROO_SOFORT"
    | "BUCKAROO_GIROPAY"
    | "BUCKAROO_EPS"
    | "XFERS_PAYNOW";
}
