/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const PaymentCardTokenApiSchemaPaymentMethodsApi: core.schemas.ObjectSchema<
  serializers.PaymentCardTokenApiSchemaPaymentMethodsApi.Raw,
  PrimerPrimerApi.PaymentCardTokenApiSchemaPaymentMethodsApi
> = core.schemas.object({
  last4Digits: core.schemas.string(),
  expirationMonth: core.schemas.string(),
  expirationYear: core.schemas.string(),
  cardholderName: core.schemas.string().optional(),
  network: core.schemas.string().optional(),
  networkTransactionId: core.schemas.string().optional(),
  accountFundingType: core.schemas.lazy(async () => (await import("../..")).AccountFundingType).optional(),
});

export declare namespace PaymentCardTokenApiSchemaPaymentMethodsApi {
  interface Raw {
    last4Digits: string;
    expirationMonth: string;
    expirationYear: string;
    cardholderName?: string | null;
    network?: string | null;
    networkTransactionId?: string | null;
    accountFundingType?: serializers.AccountFundingType.Raw | null;
  }
}
