/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const PaymentCardTokenSchemaPaymentMethodsApi: core.schemas.ObjectSchema<
  serializers.PaymentCardTokenSchemaPaymentMethodsApi.Raw,
  PrimerPrimerApi.PaymentCardTokenSchemaPaymentMethodsApi
> = core.schemas.object({
  paymentMethodData: core.schemas.lazyObject(
    async () => (await import("../..")).PaymentCardTokenApiSchemaPaymentMethodsApi
  ),
  createdAt: core.schemas.date().optional(),
  deletedAt: core.schemas.date().optional(),
  deleted: core.schemas.boolean().optional(),
  token: core.schemas.string().optional(),
  tokenType: core.schemas.string().optional(),
  analyticsId: core.schemas.string().optional(),
  customerId: core.schemas.string().optional(),
  description: core.schemas.string().optional(),
  default: core.schemas.boolean().optional(),
  isVerified: core.schemas.boolean().optional(),
});

export declare namespace PaymentCardTokenSchemaPaymentMethodsApi {
  interface Raw {
    paymentMethodData: serializers.PaymentCardTokenApiSchemaPaymentMethodsApi.Raw;
    createdAt?: string | null;
    deletedAt?: string | null;
    deleted?: boolean | null;
    token?: string | null;
    tokenType?: string | null;
    analyticsId?: string | null;
    customerId?: string | null;
    description?: string | null;
    default?: boolean | null;
    isVerified?: boolean | null;
  }
}
