/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const CardNetwork: core.schemas.Schema<serializers.CardNetwork.Raw, PrimerPrimerApi.CardNetwork> = core.schemas
  .record(
    core.schemas.lazy(async () => (await import("../..")).CardNetworkType),
    core.schemas.lazyObject(async () => (await import("../..")).Surcharge)
  )
  .optional();

export declare namespace CardNetwork {
  type Raw = Record<serializers.CardNetworkType.Raw, serializers.Surcharge.Raw> | null | undefined;
}
