/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const ClientSession: core.schemas.ObjectSchema<serializers.ClientSession.Raw, PrimerPrimerApi.ClientSession> =
  core.schemas.object({
    clientToken: core.schemas.string().optional(),
    clientExpirationDate: core.schemas.date().optional(),
    customerId: core.schemas.lazy(async () => (await import("../..")).CustomerId).optional(),
    orderId: core.schemas.lazy(async () => (await import("../..")).OrderId).optional(),
    currencyCode: core.schemas.lazy(async () => (await import("../..")).CurrencyCode).optional(),
    amount: core.schemas.number().optional(),
    order: core.schemas.lazyObject(async () => (await import("../..")).OrderDetails).optional(),
    customer: core.schemas.lazyObject(async () => (await import("../..")).CustomerDetails).optional(),
    metadata: core.schemas.lazy(async () => (await import("../..")).MetadataDetails).optional(),
    paymentMethod: core.schemas.lazyObject(async () => (await import("../..")).ClientPaymentMethod).optional(),
    warnings: core.schemas.lazyObject(async () => (await import("../..")).Warnings).optional(),
  });

export declare namespace ClientSession {
  interface Raw {
    clientToken?: string | null;
    clientExpirationDate?: string | null;
    customerId?: serializers.CustomerId.Raw | null;
    orderId?: serializers.OrderId.Raw | null;
    currencyCode?: serializers.CurrencyCode.Raw | null;
    amount?: number | null;
    order?: serializers.OrderDetails.Raw | null;
    customer?: serializers.CustomerDetails.Raw | null;
    metadata?: serializers.MetadataDetails.Raw | null;
    paymentMethod?: serializers.ClientPaymentMethod.Raw | null;
    warnings?: serializers.Warnings.Raw | null;
  }
}
