/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const CustomerDetails: core.schemas.ObjectSchema<
  serializers.CustomerDetails.Raw,
  PrimerPrimerApi.CustomerDetails
> = core.schemas.object({
  emailAddress: core.schemas.string().optional(),
  mobileNumber: core.schemas.string().optional(),
  firstName: core.schemas.string().optional(),
  lastName: core.schemas.string().optional(),
  billingAddress: core.schemas.lazyObject(async () => (await import("../..")).BillingAddress).optional(),
  shippingAddress: core.schemas.lazyObject(async () => (await import("../..")).ShippingAddress).optional(),
  taxId: core.schemas.string().optional(),
  nationalDocumentId: core.schemas.string().optional(),
});

export declare namespace CustomerDetails {
  interface Raw {
    emailAddress?: string | null;
    mobileNumber?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    billingAddress?: serializers.BillingAddress.Raw | null;
    shippingAddress?: serializers.ShippingAddress.Raw | null;
    taxId?: string | null;
    nationalDocumentId?: string | null;
  }
}
