/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const Fee: core.schemas.ObjectSchema<serializers.Fee.Raw, PrimerPrimerApi.Fee> = core.schemas.object({
  amount: core.schemas.number(),
  type: core.schemas.string().optional(),
  description: core.schemas.string().optional(),
});

export declare namespace Fee {
  interface Raw {
    amount: number;
    type?: string | null;
    description?: string | null;
  }
}
