/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const NetworkOrSurchargeObject: core.schemas.ObjectSchema<
  serializers.NetworkOrSurchargeObject.Raw,
  PrimerPrimerApi.NetworkOrSurchargeObject
> = core.schemas.object({
  networks: core.schemas
    .record(
      core.schemas.lazy(async () => (await import("../..")).CardNetworkType),
      core.schemas.lazyObject(async () => (await import("../..")).Network)
    )
    .optional(),
  surcharge: core.schemas.lazyObject(async () => (await import("../..")).Surcharge).optional(),
});

export declare namespace NetworkOrSurchargeObject {
  interface Raw {
    networks?: Record<serializers.CardNetworkType.Raw, serializers.Network.Raw> | null;
    surcharge?: serializers.Surcharge.Raw | null;
  }
}
