/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const OrderDetails: core.schemas.ObjectSchema<serializers.OrderDetails.Raw, PrimerPrimerApi.OrderDetails> =
  core.schemas.object({
    lineItems: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).LineItem)).optional(),
    countryCode: core.schemas.lazy(async () => (await import("../..")).CountryCode).optional(),
    fees: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Fee)).optional(),
    shipping: core.schemas.lazyObject(async () => (await import("../..")).ShippingDetails).optional(),
  });

export declare namespace OrderDetails {
  interface Raw {
    lineItems?: serializers.LineItem.Raw[] | null;
    countryCode?: serializers.CountryCode.Raw | null;
    fees?: serializers.Fee.Raw[] | null;
    shipping?: serializers.ShippingDetails.Raw | null;
  }
}
