/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const PaymentType: core.schemas.Schema<serializers.PaymentType.Raw, PrimerPrimerApi.PaymentType> =
  core.schemas.enum_(["FIRST_PAYMENT", "ECOMMERCE", "SUBSCRIPTION", "UNSCHEDULED"]);

export declare namespace PaymentType {
  type Raw = "FIRST_PAYMENT" | "ECOMMERCE" | "SUBSCRIPTION" | "UNSCHEDULED";
}
