/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const UpdateClientSessionRequest: core.schemas.ObjectSchema<
  UpdateClientSessionRequest.Raw,
  PrimerApi.clientSession.UpdateClientSessionRequest
> = core.schemas.object({
  clientToken: core.schemas.string().optional(),
  orderId: core.schemas.lazy(() => serializers.commons.OrderId).optional(),
  currencyCode: core.schemas.lazy(() => serializers.commons.CurrencyCode).optional(),
  amount: core.schemas.number().optional(),
  order: core.schemas.lazyObject(() => serializers.clientSession.OrderDetails).optional(),
  customer: core.schemas.lazyObject(() => serializers.clientSession.CustomerDetails).optional(),
  metadata: core.schemas.lazy(() => serializers.clientSession.MetadataDetails).optional(),
  paymentMethod: core.schemas.lazyObject(() => serializers.clientSession.ClientPaymentMethod).optional(),
});

export declare namespace UpdateClientSessionRequest {
  interface Raw {
    clientToken?: string | null;
    orderId?: serializers.commons.OrderId.Raw | null;
    currencyCode?: serializers.commons.CurrencyCode.Raw | null;
    amount?: number | null;
    order?: serializers.clientSession.OrderDetails.Raw | null;
    customer?: serializers.clientSession.CustomerDetails.Raw | null;
    metadata?: serializers.clientSession.MetadataDetails.Raw | null;
    paymentMethod?: serializers.clientSession.ClientPaymentMethod.Raw | null;
  }
}
