/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const AccountNumberType: core.schemas.Schema<AccountNumberType.Raw, PrimerApi.payments.AccountNumberType> =
  core.schemas.string().transform<PrimerApi.payments.AccountNumberType>({
    parse: (value) => {
      switch (value) {
        case "PRIMARY_ACCOUNT_NUMBER": {
          return PrimerApi.payments.AccountNumberType.PrimaryAccountNumber;
        }
        case "NETWORK_TOKEN": {
          return PrimerApi.payments.AccountNumberType.NetworkToken;
        }
        case "UNKNOWN": {
          return PrimerApi.payments.AccountNumberType.Unknown;
        }
        default: {
          return {
            value: value,
            visit: (visitor) => visitor._other(value),
          };
        }
      }
    },
    json: (value) => value.value,
  });

export declare namespace AccountNumberType {
  type Raw = string;
}
