/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const KlarnaTokenDetails: core.schemas.ObjectSchema<
  KlarnaTokenDetails.Raw,
  PrimerApi.payments.KlarnaTokenDetails
> = core.schemas.object({
  type: core.schemas.string(),
  brand: core.schemas.string().optional(),
  maskedNumber: core.schemas.property("masked_number", core.schemas.string().optional()),
  expiryDate: core.schemas.property("expiry_date", core.schemas.string().optional()),
});

export declare namespace KlarnaTokenDetails {
  interface Raw {
    type: string;
    brand?: string | null;
    masked_number?: string | null;
    expiry_date?: string | null;
  }
}
