/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const KlarnaCustomerTokenAPISchema: core.schemas.ObjectSchema<
  KlarnaCustomerTokenAPISchema.Raw,
  PrimerApi.payments.KlarnaCustomerTokenAPISchema
> = core.schemas.object({
  klarnaCustomerToken: core.schemas.string(),
  sessionData: core.schemas.lazyObject(() => schemas.payments.KlarnaSessionDetails),
});

export declare namespace KlarnaCustomerTokenAPISchema {
  interface Raw {
    klarnaCustomerToken: string;
    sessionData: schemas.payments.KlarnaSessionDetails.Raw;
  }
}
