/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const PaymentStatus: core.schemas.Schema<PaymentStatus.Raw, PrimerApi.payments.PaymentStatus> = core.schemas
  .string()
  .transform<PrimerApi.payments.PaymentStatus>({
    parse: (value) => PrimerApi.payments.PaymentStatus._parse(value),
    json: ({ value }) => value,
  });

export declare namespace PaymentStatus {
  type Raw = string;
}
