/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const PayPalBillingAgreementAPISchema: core.schemas.ObjectSchema<
  PayPalBillingAgreementAPISchema.Raw,
  PrimerApi.payments.PayPalBillingAgreementAPISchema
> = core.schemas.object({
  paypalBillingAgreementId: core.schemas.string(),
  externalPayerInfo: core.schemas.lazyObject(() => schemas.payments.ExternalPayerInfo).optional(),
  shippingAddress: core.schemas.lazyObject(() => schemas.commons.ShippingAddress).optional(),
  paypalStatus: core.schemas.string().optional(),
});

export declare namespace PayPalBillingAgreementAPISchema {
  interface Raw {
    paypalBillingAgreementId: string;
    externalPayerInfo?: schemas.payments.ExternalPayerInfo.Raw | null;
    shippingAddress?: schemas.commons.ShippingAddress.Raw | null;
    paypalStatus?: string | null;
  }
}
