/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const ProductUsageType: core.schemas.Schema<ProductUsageType.Raw, PrimerApi.payments.ProductUsageType> =
  core.schemas.string().transform<PrimerApi.payments.ProductUsageType>({
    parse: (value) => PrimerApi.payments.ProductUsageType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace ProductUsageType {
  type Raw = string;
}
