/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const ResumePaymentRequest: core.schemas.ObjectSchema<
  ResumePaymentRequest.Raw,
  PrimerApi.payments.ResumePaymentRequest
> = core.schemas.object({
  resumeToken: core.schemas.string(),
});

export declare namespace ResumePaymentRequest {
  interface Raw {
    resumeToken: string;
  }
}
