/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const SecureAuthenticationResponseCode: core.schemas.Schema<
  SecureAuthenticationResponseCode.Raw,
  PrimerApi.payments.SecureAuthenticationResponseCode
> = core.schemas.string().transform<PrimerApi.payments.SecureAuthenticationResponseCode>({
  parse: (value) => PrimerApi.payments.SecureAuthenticationResponseCode._parse(value),
  json: ({ value }) => value,
});

export declare namespace SecureAuthenticationResponseCode {
  type Raw = string;
}
