/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const StatusReasonType: core.schemas.Schema<StatusReasonType.Raw, PrimerApi.payments.StatusReasonType> =
  core.schemas.string().transform<PrimerApi.payments.StatusReasonType>({
    parse: (value) => PrimerApi.payments.StatusReasonType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace StatusReasonType {
  type Raw = string;
}
