/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const StatusReasonCode: core.schemas.Schema<StatusReasonCode.Raw, PrimerApi.payments.StatusReasonCode> =
  core.schemas.string().transform<PrimerApi.payments.StatusReasonCode>({
    parse: (value) => PrimerApi.payments.StatusReasonCode._parse(value),
    json: ({ value }) => value,
  });

export declare namespace StatusReasonCode {
  type Raw = string;
}
