/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const ThreeDSecureAuthentication: core.schemas.ObjectSchema<
  ThreeDSecureAuthentication.Raw,
  PrimerApi.payments.ThreeDSecureAuthentication
> = core.schemas.object({
  responseCode: core.schemas.lazy(() => schemas.payments.SecureAuthenticationResponseCode),
  reasonCode: core.schemas.lazy(() => schemas.payments.ThreeDSecureReasonCode).optional(),
  reasonText: core.schemas.string().optional(),
  protocolVersion: core.schemas.string().optional(),
  challengeIssued: core.schemas.boolean().optional(),
});

export declare namespace ThreeDSecureAuthentication {
  interface Raw {
    responseCode: schemas.payments.SecureAuthenticationResponseCode.Raw;
    reasonCode?: schemas.payments.ThreeDSecureReasonCode.Raw | null;
    reasonText?: string | null;
    protocolVersion?: string | null;
    challengeIssued?: boolean | null;
  }
}
