/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AccountNumberType = "PRIMARY_ACCOUNT_NUMBER" | "NETWORK_TOKEN" | "UNKNOWN";

export const AccountNumberType = {
  PrimaryAccountNumber: "PRIMARY_ACCOUNT_NUMBER",
  NetworkToken: "NETWORK_TOKEN",
  Unknown: "UNKNOWN",
} as const;
