/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface BinData {
  network: PrimerApi.commons.CardNetworkType;
  issuerCountryCode?: PrimerApi.commons.CountryCode;
  issuerName?: string;
  issuerCurrencyCode?: PrimerApi.commons.CurrencyCode;
  regionalRestriction: PrimerApi.payments.RegionalRestriction;
  accountNumberType: PrimerApi.payments.AccountNumberType;
  accountFundingType: PrimerApi.commons.AccountFundingType;
  prepaidReloadableIndicator: PrimerApi.payments.PrepaidReloadableIndicator;
  productUsageType: PrimerApi.payments.ProductUsageType;
  productCode: string;
  productName: string;
}
