/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface CancelPaymentRequest {
  /** You can optionally specify a reason for the cancellation. This is for your own records. */
  reason?: string;
}
