/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface CreatePaymentRequest {
  /** Your reference for the payment. */
  orderId?: PrimerApi.commons.OrderId;
  /**
   * The 3-letter currency code in ISO 4217 format.
   * e.g. use USD for US dollars.
   *
   */
  currencyCode?: PrimerApi.commons.CurrencyCode;
  /** The amount you would like to charge the customer, in minor units. e.g. for $7, use 700. Some currencies, such as Japanese Yen, do not have minor units. In this case you should use the value as it is, without any formatting. For example for ¥100, use 100. */
  amount?: number;
  /** More information associated with the order. */
  order?: PrimerApi.clientSession.OrderDetails;
  /** The payment method token used to authorize the payment. */
  paymentMethodToken: string;
  /** A unique identifier for your customer. This attribute is required if `paymentMethod.vaultOnSuccess` is set to True. */
  customerId?: PrimerApi.commons.CustomerId;
  /** More information associated with the customer. */
  customer?: PrimerApi.clientSession.CustomerDetails;
  /**
   * Additional data to be used throughout the payment lifecycle.
   * A dictionary of key-value pairs where the values can only be strings or integers.
   * e.g. {"productId": 1001, "merchantId": "a13bsd62s"}
   *
   */
  metadata?: Record<string, unknown>;
  /** Enable certain options associated with the payment method. */
  paymentMethod?: PrimerApi.clientSession.ClientPaymentMethod;
}
