/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface GoCardlessMandateAPISchema {
  /** Unique identifier of a GoCardless mandate agreement */
  gocardlessMandateId: string;
}
