/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface KlarnaCustomerTokenAPISchema {
  klarnaCustomerToken: string;
  sessionData: PrimerApi.payments.KlarnaSessionDetails;
}
