/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";

export interface KlarnaCustomerTokenApiSchema {
  klarnaCustomerToken: string;
  sessionData: PrimerPrimerApi.KlarnaSessionDetails;
}
