/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";

export interface KlarnaSessionDetails {
  recurringDescription?: string;
  billingAddress: PrimerPrimerApi.KlarnaAddress;
  shippingAddress?: PrimerPrimerApi.KlarnaAddress;
  purchaseCountry: string;
  purchaseCurrency: string;
  locale: string;
  orderLines: unknown[];
  tokenDetails?: PrimerPrimerApi.KlarnaTokenDetails;
}
