/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";

export interface PaymentCardTokenApiSchema {
  first6Digits?: string;
  last4Digits: string;
  expirationMonth: string;
  expirationYear: string;
  cardholderName?: string;
  network?: string;
  isNetworkTokenized?: boolean;
  binData?: PrimerPrimerApi.BinData;
}
