/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";

export interface PaymentResponse {
  /** Use this ID to retrieve the payment details or perform downstream operations. */
  id?: PrimerPrimerApi.PaymentId;
  /** The date and time at which the payment was created in UTC format. */
  date?: Date;
  /** As the payments are created, processed, and finalised, they go through a number of states that you will get as an API response, through webhook notifications, and in the Dashboard. These states are used across all processors, as processor specific states are mapped to these. An additional message, in the field processorMessage, from the processor may also be included that details the reason for the state, primarily on failure states. */
  status?: PrimerPrimerApi.PaymentStatus;
  /** Your reference for the payment. */
  orderId?: PrimerPrimerApi.OrderId;
  /** The unique identifier for your customer. */
  customerId?: string;
  /** The 3-letter currency code in ISO 4217 format. e.g. use USD for US dollars. */
  currencyCode?: PrimerPrimerApi.CurrencyCode;
  /** The payment amount, in minor units. e.g. $7 would show as 700. */
  amount?: number;
  /** More information associated with the order. */
  order?: PrimerPrimerApi.CustomerDetails;
  /** The country in which the order is created */
  countryCode?: PrimerPrimerApi.CountryCode;
  /** The details of fees charged. */
  fees?: PrimerPrimerApi.Fee[];
  /** The details of shipping charged. */
  shipping?: PrimerPrimerApi.ShippingDetails;
  /** The payment method options provided in the request, as well as the token used to process the payment. */
  paymentMethod: PrimerPrimerApi.PaymentMethod;
  /** Required action to perform in order to resume the payment workflow. This can be requiring a 3DS check from the customer for instance. */
  requiredAction?: PrimerPrimerApi.RequiredAction;
  /** Check this field for more information regarding the payment's status. This is especially useful when the status is `DECLINED` or `FAILED`. */
  statusReason?: PrimerPrimerApi.StatusReason;
  /** A list summarizing the transactions that occurred while processing the payment. */
  transactions: PrimerPrimerApi.Transaction[];
  /** More information associated with the payment processor, including the processor name. */
  processor?: PrimerPrimerApi.Processor;
  /** More information associated with the customer. */
  customer?: PrimerPrimerApi.CustomerDetails;
  /** Additional data to be used throughout the payment lifecycle. */
  metadata?: Record<string, unknown>;
}
