/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface PaymentsData {
  data: PrimerApi.payments.SearchPaymentResponse[];
  nextCursor?: string;
  prevCursor?: string;
}
