/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface PaymentProcessorError {
  /** Type of the status. */
  type: PrimerApi.payments.StatusReasonType;
  /** If the error is of type `ISSUER_DECLINED` this will be returned. Declines of type `SOFT_DECLINE` may be retried, whereas declines of type `HARD_DECLINE` should not be retried. */
  declineType?: PrimerApi.payments.StatusReasonDeclineType;
  /** If the error is of type `ISSUER_DECLINED`, this will be returned. */
  code?: PrimerApi.payments.StatusReasonCode;
  /** In case of an error on the processor's part, we will return the message returned by the processor. This is usually a human readable error. */
  message?: string;
}
