/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface PayPalBillingAgreementAPISchema {
  paypalBillingAgreementId: string;
  /** Information about the PayPal customer */
  externalPayerInfo?: PrimerApi.payments.ExternalPayerInfo;
  /** The PayPal customer's shipping address */
  shippingAddress?: PrimerApi.commons.ShippingAddress;
  paypalStatus?: string;
}
