/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RegionalRestriction = "DOMESTIC_USE_ONLY" | "NONE" | "UNKNOWN";

export const RegionalRestriction = {
  DomesticUseOnly: "DOMESTIC_USE_ONLY",
  None: "NONE",
  Unknown: "UNKNOWN",
} as const;
