/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RequiredAction {
  /** Action name. 3DS_AUTHENTICATION USE_PRIMER_SDK */
  name: string;
  /** Human description of the required action to perform. */
  description: string;
  /** If the action requires customer data, instantiate the checkout SDK with this client session token to resume the session. */
  clientToken?: string;
}
