/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SecureAuthenticationResponseCode =
  | "NOT_PERFORMED"
  | "SKIPPED"
  | "AUTH_SUCCESS"
  | "AUTH_FAILED"
  | "CHALLENGE_METHOD";

export const SecureAuthenticationResponseCode = {
  NotPerformed: "NOT_PERFORMED",
  Skipped: "SKIPPED",
  AuthSuccess: "AUTH_SUCCESS",
  AuthFailed: "AUTH_FAILED",
  ChallengeMethod: "CHALLENGE_METHOD",
} as const;
