/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StatusReasonType = "APPLICATION_ERROR" | "GATEWAY_REJECTED" | "ISSUER_DECLINED";

export const StatusReasonType = {
  ApplicationError: "APPLICATION_ERROR",
  GatewayRejected: "GATEWAY_REJECTED",
  IssuerDeclined: "ISSUER_DECLINED",
} as const;
