/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StatusReasonCode =
  | "ERROR"
  | "INVALID_CARD_NUMBER"
  | "EXPIRED_CARD"
  | "LOST_OR_STOLEN_CARD"
  | "SUSPECTED_FRAUD"
  | "UNKNOWN_DECLINED"
  | "REFER_TO_CARD_ISSUER"
  | "DO_NOT_HONOR"
  | "INSUFFICIENT_FUNDS"
  | "WITHDRAWAL_LIMIT_EXCEEDED"
  | "ISSUER_TEMPORARILY_UNAVAILABLE"
  | "AUTHENTICATION_REQUIRED";

export const StatusReasonCode = {
  Error: "ERROR",
  InvalidCardNumber: "INVALID_CARD_NUMBER",
  ExpiredCard: "EXPIRED_CARD",
  LostOrStolenCard: "LOST_OR_STOLEN_CARD",
  SuspectedFraud: "SUSPECTED_FRAUD",
  UnknownDeclined: "UNKNOWN_DECLINED",
  ReferToCardIssuer: "REFER_TO_CARD_ISSUER",
  DoNotHonor: "DO_NOT_HONOR",
  InsufficientFunds: "INSUFFICIENT_FUNDS",
  WithdrawalLimitExceeded: "WITHDRAWAL_LIMIT_EXCEEDED",
  IssuerTemporarilyUnavailable: "ISSUER_TEMPORARILY_UNAVAILABLE",
  AuthenticationRequired: "AUTHENTICATION_REQUIRED",
} as const;
