/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StatusReasonDeclineType = "SOFT_DECLINE" | "HARD_DECLINE";

export const StatusReasonDeclineType = {
  SoftDecline: "SOFT_DECLINE",
  HardDecline: "HARD_DECLINE",
} as const;
