/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export type ThreeDSecureReasonCode =
  | PrimerPrimerApi.ThreeDSecureReasonCode.Skipped
  | PrimerPrimerApi.ThreeDSecureReasonCode.Failed
  | PrimerPrimerApi.ThreeDSecureReasonCode._Unknown;

export declare namespace ThreeDSecureReasonCode {
  interface Skipped extends _Utils {
    type: "Skipped";
    value: PrimerPrimerApi.ThreeDSecureSkippedReasonCodeEnum;
  }

  interface Failed extends _Utils {
    type: "Failed";
    value: PrimerPrimerApi.ThreeDSecureFailedReasonCodeEnum;
  }

  interface _Unknown extends _Utils {
    type: void;
  }

  interface _Utils {
    _visit: <_Result>(visitor: PrimerPrimerApi.ThreeDSecureReasonCode._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    skipped: (value: PrimerPrimerApi.ThreeDSecureSkippedReasonCodeEnum) => _Result;
    failed: (value: PrimerPrimerApi.ThreeDSecureFailedReasonCodeEnum) => _Result;
    _other: (value: { type: string }) => _Result;
  }
}

export const ThreeDSecureReasonCode = {
  skipped: (
    value: PrimerPrimerApi.ThreeDSecureSkippedReasonCodeEnum
  ): PrimerPrimerApi.ThreeDSecureReasonCode.Skipped => {
    const valueWithoutVisit: Omit<PrimerPrimerApi.ThreeDSecureReasonCode.Skipped, "_visit"> = {
      value: value,
      type: "Skipped",
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: PrimerPrimerApi.ThreeDSecureReasonCode.Skipped, visitor: PrimerPrimerApi.ThreeDSecureReasonCode._Visitor<_Result>) {
      return PrimerPrimerApi.ThreeDSecureReasonCode._visit(this, visitor);
    });
  },

  failed: (value: PrimerPrimerApi.ThreeDSecureFailedReasonCodeEnum): PrimerPrimerApi.ThreeDSecureReasonCode.Failed => {
    const valueWithoutVisit: Omit<PrimerPrimerApi.ThreeDSecureReasonCode.Failed, "_visit"> = {
      value: value,
      type: "Failed",
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: PrimerPrimerApi.ThreeDSecureReasonCode.Failed, visitor: PrimerPrimerApi.ThreeDSecureReasonCode._Visitor<_Result>) {
      return PrimerPrimerApi.ThreeDSecureReasonCode._visit(this, visitor);
    });
  },

  _unknown: (value: { type: string }): PrimerPrimerApi.ThreeDSecureReasonCode._Unknown => {
    const valueWithoutVisit = value as unknown as Omit<PrimerPrimerApi.ThreeDSecureReasonCode._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: PrimerPrimerApi.ThreeDSecureReasonCode._Unknown, visitor: PrimerPrimerApi.ThreeDSecureReasonCode._Visitor<_Result>) {
      return PrimerPrimerApi.ThreeDSecureReasonCode._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: PrimerPrimerApi.ThreeDSecureReasonCode,
    visitor: PrimerPrimerApi.ThreeDSecureReasonCode._Visitor<_Result>
  ): _Result => {
    switch (value.type) {
      case "Skipped":
        return visitor.skipped(value.value);
      case "Failed":
        return visitor.failed(value.value);
      default:
        return visitor._other(value as any);
    }
  },
} as const;
