/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface ThreeDSecureFailedReasonCodeEnum<
  RawValue extends ThreeDSecureFailedReasonCodeEnum.RawValue = ThreeDSecureFailedReasonCodeEnum.RawValue
> {
  value: RawValue;
  visit: <Result>(visitor: ThreeDSecureFailedReasonCodeEnum._Visitor<Result>) => Result;
}

const _CardAuthenticationFailed: ThreeDSecureFailedReasonCodeEnum<"01"> = {
  value: "01",
  visit: (visitor) => visitor.cardAuthenticationFailed(),
};
const _UnknownDevice: ThreeDSecureFailedReasonCodeEnum<"02"> = {
  value: "02",
  visit: (visitor) => visitor.unknownDevice(),
};
const _UnsupportedDevice: ThreeDSecureFailedReasonCodeEnum<"03"> = {
  value: "03",
  visit: (visitor) => visitor.unsupportedDevice(),
};
const _ExceedsAuthenticationFrequencyLimit: ThreeDSecureFailedReasonCodeEnum<"04"> = {
  value: "04",
  visit: (visitor) => visitor.exceedsAuthenticationFrequencyLimit(),
};
const _ExpiredCard: ThreeDSecureFailedReasonCodeEnum<"05"> = {
  value: "05",
  visit: (visitor) => visitor.expiredCard(),
};
const _InvalidCardNumber: ThreeDSecureFailedReasonCodeEnum<"06"> = {
  value: "06",
  visit: (visitor) => visitor.invalidCardNumber(),
};
const _InvalidTransaction: ThreeDSecureFailedReasonCodeEnum<"07"> = {
  value: "07",
  visit: (visitor) => visitor.invalidTransaction(),
};
const _NoCardRecord: ThreeDSecureFailedReasonCodeEnum<"08"> = {
  value: "08",
  visit: (visitor) => visitor.noCardRecord(),
};
const _SecurityFailure: ThreeDSecureFailedReasonCodeEnum<"09"> = {
  value: "09",
  visit: (visitor) => visitor.securityFailure(),
};
const _StolenCard: ThreeDSecureFailedReasonCodeEnum<"10"> = {
  value: "10",
  visit: (visitor) => visitor.stolenCard(),
};
const _SuspectedFraud: ThreeDSecureFailedReasonCodeEnum<"11"> = {
  value: "11",
  visit: (visitor) => visitor.suspectedFraud(),
};
const _TransactionNotPermittedToCardholder: ThreeDSecureFailedReasonCodeEnum<"12"> = {
  value: "12",
  visit: (visitor) => visitor.transactionNotPermittedToCardholder(),
};
const _CardholderNotEnrolledInService: ThreeDSecureFailedReasonCodeEnum<"13"> = {
  value: "13",
  visit: (visitor) => visitor.cardholderNotEnrolledInService(),
};
const _TransactionTimedOutAtTheAcs: ThreeDSecureFailedReasonCodeEnum<"14"> = {
  value: "14",
  visit: (visitor) => visitor.transactionTimedOutAtTheAcs(),
};
const _LowConfidence: ThreeDSecureFailedReasonCodeEnum<"15"> = {
  value: "15",
  visit: (visitor) => visitor.lowConfidence(),
};
const _MediumConfidence: ThreeDSecureFailedReasonCodeEnum<"16"> = {
  value: "16",
  visit: (visitor) => visitor.mediumConfidence(),
};
export const ThreeDSecureFailedReasonCodeEnum = {
  CardAuthenticationFailed: _CardAuthenticationFailed,
  UnknownDevice: _UnknownDevice,
  UnsupportedDevice: _UnsupportedDevice,
  ExceedsAuthenticationFrequencyLimit: _ExceedsAuthenticationFrequencyLimit,
  ExpiredCard: _ExpiredCard,
  InvalidCardNumber: _InvalidCardNumber,
  InvalidTransaction: _InvalidTransaction,
  NoCardRecord: _NoCardRecord,
  SecurityFailure: _SecurityFailure,
  StolenCard: _StolenCard,
  SuspectedFraud: _SuspectedFraud,
  TransactionNotPermittedToCardholder: _TransactionNotPermittedToCardholder,
  CardholderNotEnrolledInService: _CardholderNotEnrolledInService,
  TransactionTimedOutAtTheAcs: _TransactionTimedOutAtTheAcs,
  LowConfidence: _LowConfidence,
  MediumConfidence: _MediumConfidence,
  _parse: (value: string): ThreeDSecureFailedReasonCodeEnum => {
    switch (value) {
      case "01": {
        return _CardAuthenticationFailed;
      }
      case "02": {
        return _UnknownDevice;
      }
      case "03": {
        return _UnsupportedDevice;
      }
      case "04": {
        return _ExceedsAuthenticationFrequencyLimit;
      }
      case "05": {
        return _ExpiredCard;
      }
      case "06": {
        return _InvalidCardNumber;
      }
      case "07": {
        return _InvalidTransaction;
      }
      case "08": {
        return _NoCardRecord;
      }
      case "09": {
        return _SecurityFailure;
      }
      case "10": {
        return _StolenCard;
      }
      case "11": {
        return _SuspectedFraud;
      }
      case "12": {
        return _TransactionNotPermittedToCardholder;
      }
      case "13": {
        return _CardholderNotEnrolledInService;
      }
      case "14": {
        return _TransactionTimedOutAtTheAcs;
      }
      case "15": {
        return _LowConfidence;
      }
      case "16": {
        return _MediumConfidence;
      }
      default: {
        return {
          value: value as ThreeDSecureFailedReasonCodeEnum.RawValue,
          visit: (visitor) => visitor._other(value),
        };
      }
    }
  },
} as const;

export declare namespace ThreeDSecureFailedReasonCodeEnum {
  type RawValue =
    | "01"
    | "02"
    | "03"
    | "04"
    | "05"
    | "06"
    | "07"
    | "08"
    | "09"
    | "10"
    | "11"
    | "12"
    | "13"
    | "14"
    | "15"
    | "16";

  interface _Visitor<Result> {
    cardAuthenticationFailed: () => Result;
    unknownDevice: () => Result;
    unsupportedDevice: () => Result;
    exceedsAuthenticationFrequencyLimit: () => Result;
    expiredCard: () => Result;
    invalidCardNumber: () => Result;
    invalidTransaction: () => Result;
    noCardRecord: () => Result;
    securityFailure: () => Result;
    stolenCard: () => Result;
    suspectedFraud: () => Result;
    transactionNotPermittedToCardholder: () => Result;
    cardholderNotEnrolledInService: () => Result;
    transactionTimedOutAtTheAcs: () => Result;
    lowConfidence: () => Result;
    mediumConfidence: () => Result;
    _other: (value: string) => Result;
  }
}
