/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const PaymentCardTokenAPISchemaPaymentMethodsAPI: core.schemas.ObjectSchema<
  PaymentCardTokenAPISchemaPaymentMethodsAPI.Raw,
  PrimerApi.paymentMethod.PaymentCardTokenAPISchemaPaymentMethodsAPI
> = core.schemas.object({
  last4Digits: core.schemas.string(),
  expirationMonth: core.schemas.string(),
  expirationYear: core.schemas.string(),
  cardholderName: core.schemas.string().optional(),
  network: core.schemas.string().optional(),
  networkTransactionId: core.schemas.string().optional(),
  accountFundingType: core.schemas.lazy(() => schemas.commons.AccountFundingType).optional(),
});

export declare namespace PaymentCardTokenAPISchemaPaymentMethodsAPI {
  interface Raw {
    last4Digits: string;
    expirationMonth: string;
    expirationYear: string;
    cardholderName?: string | null;
    network?: string | null;
    networkTransactionId?: string | null;
    accountFundingType?: schemas.commons.AccountFundingType.Raw | null;
  }
}
