/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";

export interface SavePaymentMethodTokenRequest {
  /** The ID representing the customer */
  customerId: PrimerApi.commons.CustomerId;
  /** Whether the payment method should be verified before vaulting or not */
  verify?: boolean;
}
