/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const Response: core.schemas.Schema<
  serializers.paymentMethod.list.Response.Raw,
  PrimerPrimerApi.ListPaymentMethodsResponse
> = core.schemas.lazyObject(async () => (await import("../..")).ListPaymentMethodsResponse);

export declare namespace Response {
  type Raw = serializers.ListPaymentMethodsResponse.Raw;
}
