/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const Request: core.schemas.Schema<
  serializers.paymentMethod.saveToken.Request.Raw,
  PrimerPrimerApi.SavePaymentMethodTokenRequest
> = core.schemas.object({
  customerId: core.schemas.lazy(async () => (await import("../..")).CustomerId),
  verify: core.schemas.boolean().optional(),
});

export declare namespace Request {
  interface Raw {
    customerId: serializers.CustomerId.Raw;
    verify?: boolean | null;
  }
}

export const Response: core.schemas.Schema<
  serializers.paymentMethod.saveToken.Response.Raw,
  PrimerPrimerApi.PaymentMethodToken
> = core.schemas.lazy(async () => (await import("../..")).PaymentMethodToken);

export declare namespace Response {
  type Raw = serializers.PaymentMethodToken.Raw;
}
