/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const ClientSessionValidationError: core.schemas.Schema<
  serializers.ClientSessionValidationError.Raw,
  PrimerPrimerApi.ClientSessionValidationError
> = core.schemas.lazyObject(async () => (await import("../..")).ClientSessionValidationErrorBody);

export declare namespace ClientSessionValidationError {
  type Raw = serializers.ClientSessionValidationErrorBody.Raw;
}
