/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const PaymentsRequestValidationError: core.schemas.Schema<
  serializers.PaymentsRequestValidationError.Raw,
  PrimerPrimerApi.PaymentsRequestValidationError
> = core.schemas.lazyObject(async () => (await import("../..")).PaymentsRequestValidationBody);

export declare namespace PaymentsRequestValidationError {
  type Raw = serializers.PaymentsRequestValidationBody.Raw;
}
