/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const RequestValidationError: core.schemas.Schema<
  serializers.RequestValidationError.Raw,
  PrimerPrimerApi.RequestValidationError
> = core.schemas.lazyObject(async () => (await import("../..")).RequestValidationErrorBody);

export declare namespace RequestValidationError {
  type Raw = serializers.RequestValidationErrorBody.Raw;
}
