/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export type Response = core.APIResponse<PrimerPrimerApi.ClientSession, PrimerPrimerApi.clientSession.create.Error>;
export type Error =
  | PrimerPrimerApi.clientSession.create.Error.ClientSessionValidationError
  | PrimerPrimerApi.clientSession.create.Error.RequestValidationError
  | PrimerPrimerApi.clientSession.create.Error._Unknown;

export declare namespace Error {
  interface ClientSessionValidationError extends _Utils {
    statusCode: 400;
    content: PrimerPrimerApi.ClientSessionValidationError;
  }

  interface RequestValidationError extends _Utils {
    statusCode: 422;
    content: PrimerPrimerApi.RequestValidationError;
  }

  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: PrimerPrimerApi.clientSession.create.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    clientSessionValidationError: (value: PrimerPrimerApi.ClientSessionValidationError) => _Result;
    requestValidationError: (value: PrimerPrimerApi.RequestValidationError) => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  clientSessionValidationError: (
    value: PrimerPrimerApi.ClientSessionValidationError
  ): PrimerPrimerApi.clientSession.create.Error.ClientSessionValidationError => {
    const valueWithoutVisit: Omit<PrimerPrimerApi.clientSession.create.Error.ClientSessionValidationError, "_visit"> = {
      content: value,
      statusCode: 400,
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: PrimerPrimerApi.clientSession.create.Error.ClientSessionValidationError, visitor: PrimerPrimerApi.clientSession.create.Error._Visitor<_Result>) {
      return PrimerPrimerApi.clientSession.create.Error._visit(this, visitor);
    });
  },

  requestValidationError: (
    value: PrimerPrimerApi.RequestValidationError
  ): PrimerPrimerApi.clientSession.create.Error.RequestValidationError => {
    const valueWithoutVisit: Omit<PrimerPrimerApi.clientSession.create.Error.RequestValidationError, "_visit"> = {
      content: value,
      statusCode: 422,
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: PrimerPrimerApi.clientSession.create.Error.RequestValidationError, visitor: PrimerPrimerApi.clientSession.create.Error._Visitor<_Result>) {
      return PrimerPrimerApi.clientSession.create.Error._visit(this, visitor);
    });
  },

  _unknown: (fetcherError: core.Fetcher.Error): PrimerPrimerApi.clientSession.create.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<
      PrimerPrimerApi.clientSession.create.Error._Unknown,
      "_visit"
    >;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: PrimerPrimerApi.clientSession.create.Error._Unknown, visitor: PrimerPrimerApi.clientSession.create.Error._Visitor<_Result>) {
      return PrimerPrimerApi.clientSession.create.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: PrimerPrimerApi.clientSession.create.Error,
    visitor: PrimerPrimerApi.clientSession.create.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      case 400:
        return visitor.clientSessionValidationError(value.content);
      case 422:
        return visitor.requestValidationError(value.content);
      default:
        return visitor._other(value as any);
    }
  },
} as const;
