/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Sandbox: "https://api.sandbox.primer.io",
  Production: "https://api.primer.io",
} as const;

export type Environment = typeof Environment.Sandbox | typeof Environment.Production;
