/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PrimerPrimerApi } from "@fern-api/primer";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.clientSession.get.Response.Raw, PrimerPrimerApi.ClientSession> =
  core.schemas.lazyObject(async () => (await import("../..")).ClientSession);

export declare namespace Response {
  type Raw = serializers.ClientSession.Raw;
}
