/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";

export interface CustomerDetails {
  /** Customer email address */
  emailAddress?: string;
  /** The customer's mobile number */
  mobileNumber?: string;
  /** The customer's first name */
  firstName?: string;
  /** The customer's last name */
  lastName?: string;
  /** Customer billing address */
  billingAddress?: PrimerPrimerApi.BillingAddress;
  /** Customer shipping address */
  shippingAddress?: PrimerPrimerApi.ShippingAddress;
  /** The customer's tax id number for tax exemptions */
  taxId?: string;
  /** The customer's national identification number */
  nationalDocumentId?: string;
}
