/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PrimerPrimerApi } from "@fern-api/primer";

export interface LineItem {
  /** A unique identifier for the line item. */
  itemId?: string;
  /** A name of the item. */
  name?: string;
  /** A description of the item. */
  description?: string;
  /** The amount charged to the customer, in minor units. */
  amount: number;
  /** The number of the particular line item that is being ordered. */
  quantity?: number;
  /** Any discount applicable to this item, in minor units. This discount is applied for the entire line item, and not per quantity. */
  discountAmount?: number;
  /** The tax charged on this item, in minor units. This tax amount is applied for the entire line item, and not per quantity. */
  taxAmount?: number;
  /** The tax code associated with this item, in minor units. This is required for Primer-initiated tax calculations. */
  taxCode?: string;
  /** An identifier for the product type. */
  productType?: string;
  /** Details related to the product */
  productData?: PrimerPrimerApi.ProductData;
}
