/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A dictionary of key-value pairs where the values can only be strings or integers.
 */
export type MetadataDetails = Record<string, unknown>;
