/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProductData {
  /** The product SKU */
  sku?: string;
  /** The product brand */
  brand?: string;
  /** The product color */
  color?: string;
  /** The product Global Trade Item Number (e.g. ISBN) */
  globalTradeItemNumber?: string;
  /** The product Manufacturer Part Number */
  manufacturerPartNumber?: string;
  /** The product weight */
  weight?: number;
  /** The product weight unit (e.g. kg, g) */
  weightUnit?: string;
}
