/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ShippingDetails {
  /** The shipping amount charged to the customer, in minor units. e.g. for $7, use 700. */
  amount?: number;
}
