/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Warnings {
  /** The type of the connection involved */
  type?: string;
  /** A unique code describing the particular issue */
  code?: string;
  /** More information as to the reason for the warning */
  message?: string;
}
