/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../core";
import { Client as ClientSessionServiceClient } from "./client-session/client/Client";
import { Client as PaymentMethodsServiceClient } from "./payment-method/client/Client";
import { Client as PaymentsServiceClient } from "./payments/client/Client";

export namespace Client {
  export interface Options {
    _origin: string;
    apiKey?: core.Supplier<string>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  #clientSession: ClientSessionServiceClient | undefined;

  public get clientSession(): ClientSessionServiceClient {
    return (this.#clientSession ??= new ClientSessionServiceClient({
      _origin: this.options._origin,
      apiKey: this.options.apiKey,
    }));
  }

  #paymentMethod: PaymentMethodsServiceClient | undefined;

  public get paymentMethod(): PaymentMethodsServiceClient {
    return (this.#paymentMethod ??= new PaymentMethodsServiceClient({
      _origin: this.options._origin,
      apiKey: this.options.apiKey,
    }));
  }

  #payments: PaymentsServiceClient | undefined;

  public get payments(): PaymentsServiceClient {
    return (this.#payments ??= new PaymentsServiceClient({
      _origin: this.options._origin,
      apiKey: this.options.apiKey,
    }));
  }
}
