/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const ClientPaymentMethod: core.schemas.ObjectSchema<
  ClientPaymentMethod.Raw,
  PrimerApi.clientSession.ClientPaymentMethod
> = core.schemas.object({
  vaultOnSuccess: core.schemas.boolean().optional(),
  descriptor: core.schemas.string().optional(),
  paymentType: core.schemas.lazy(() => schemas.clientSession.PaymentType).optional(),
  options: core.schemas
    .record(
      core.schemas.string(),
      core.schemas.lazyObject(() => schemas.clientSession.NetworkOrSurchargeObject)
    )
    .optional(),
});

export declare namespace ClientPaymentMethod {
  interface Raw {
    vaultOnSuccess?: boolean | null;
    descriptor?: string | null;
    paymentType?: schemas.clientSession.PaymentType.Raw | null;
    options?: Record<
      schemas.commons.SupportedPaymentMethods.Raw,
      schemas.clientSession.NetworkOrSurchargeObject.Raw
    > | null;
  }
}
