/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const ClientSession: core.schemas.ObjectSchema<ClientSession.Raw, PrimerApi.clientSession.ClientSession> =
  core.schemas.object({
    clientToken: core.schemas.string().optional(),
    clientExpirationDate: core.schemas.date().optional(),
    customerId: core.schemas.lazy(() => schemas.commons.CustomerId).optional(),
    orderId: core.schemas.lazy(() => schemas.commons.OrderId).optional(),
    currencyCode: core.schemas.lazy(() => schemas.commons.CurrencyCode).optional(),
    amount: core.schemas.number().optional(),
    order: core.schemas.lazyObject(() => schemas.clientSession.OrderDetails).optional(),
    customer: core.schemas.lazyObject(() => schemas.clientSession.CustomerDetails).optional(),
    metadata: core.schemas.lazy(() => schemas.clientSession.MetadataDetails).optional(),
    paymentMethod: core.schemas.lazyObject(() => schemas.clientSession.ClientPaymentMethod).optional(),
    warnings: core.schemas.lazyObject(() => schemas.clientSession.Warnings).optional(),
  });

export declare namespace ClientSession {
  interface Raw {
    clientToken?: string | null;
    clientExpirationDate?: string | null;
    customerId?: schemas.commons.CustomerId.Raw | null;
    orderId?: schemas.commons.OrderId.Raw | null;
    currencyCode?: schemas.commons.CurrencyCode.Raw | null;
    amount?: number | null;
    order?: schemas.clientSession.OrderDetails.Raw | null;
    customer?: schemas.clientSession.CustomerDetails.Raw | null;
    metadata?: schemas.clientSession.MetadataDetails.Raw | null;
    paymentMethod?: schemas.clientSession.ClientPaymentMethod.Raw | null;
    warnings?: schemas.clientSession.Warnings.Raw | null;
  }
}
