/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const CustomerDetails: core.schemas.ObjectSchema<CustomerDetails.Raw, PrimerApi.clientSession.CustomerDetails> =
  core.schemas.object({
    emailAddress: core.schemas.string().optional(),
    mobileNumber: core.schemas.string().optional(),
    firstName: core.schemas.string().optional(),
    lastName: core.schemas.string().optional(),
    billingAddress: core.schemas.lazyObject(() => schemas.commons.BillingAddress).optional(),
    shippingAddress: core.schemas.lazyObject(() => schemas.commons.ShippingAddress).optional(),
    taxId: core.schemas.string().optional(),
    nationalDocumentId: core.schemas.string().optional(),
  });

export declare namespace CustomerDetails {
  interface Raw {
    emailAddress?: string | null;
    mobileNumber?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    billingAddress?: schemas.commons.BillingAddress.Raw | null;
    shippingAddress?: schemas.commons.ShippingAddress.Raw | null;
    taxId?: string | null;
    nationalDocumentId?: string | null;
  }
}
