/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const LineItem: core.schemas.ObjectSchema<LineItem.Raw, PrimerApi.clientSession.LineItem> = core.schemas.object({
  itemId: core.schemas.string().optional(),
  name: core.schemas.string().optional(),
  description: core.schemas.string().optional(),
  amount: core.schemas.number(),
  quantity: core.schemas.number().optional(),
  discountAmount: core.schemas.number().optional(),
  taxAmount: core.schemas.number().optional(),
  taxCode: core.schemas.string().optional(),
  productType: core.schemas.string().optional(),
  productData: core.schemas.lazyObject(() => schemas.clientSession.ProductData).optional(),
});

export declare namespace LineItem {
  interface Raw {
    itemId?: string | null;
    name?: string | null;
    description?: string | null;
    amount: number;
    quantity?: number | null;
    discountAmount?: number | null;
    taxAmount?: number | null;
    taxCode?: string | null;
    productType?: string | null;
    productData?: schemas.clientSession.ProductData.Raw | null;
  }
}
