/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const PaymentType: core.schemas.Schema<PaymentType.Raw, PrimerApi.clientSession.PaymentType> = core.schemas
  .string()
  .transform<PrimerApi.clientSession.PaymentType>({
    parse: (value) => PrimerApi.clientSession.PaymentType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace PaymentType {
  type Raw = string;
}
