/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const ProductData: core.schemas.ObjectSchema<ProductData.Raw, PrimerApi.clientSession.ProductData> =
  core.schemas.object({
    sku: core.schemas.string().optional(),
    brand: core.schemas.string().optional(),
    color: core.schemas.string().optional(),
    globalTradeItemNumber: core.schemas.string().optional(),
    manufacturerPartNumber: core.schemas.string().optional(),
    weight: core.schemas.number().optional(),
    weightUnit: core.schemas.string().optional(),
  });

export declare namespace ProductData {
  interface Raw {
    sku?: string | null;
    brand?: string | null;
    color?: string | null;
    globalTradeItemNumber?: string | null;
    manufacturerPartNumber?: string | null;
    weight?: number | null;
    weightUnit?: string | null;
  }
}
