/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PrimerApi } from "../../..";
import * as core from "../../../core";

export const Warnings: core.schemas.ObjectSchema<Warnings.Raw, PrimerApi.clientSession.Warnings> = core.schemas.object({
  type: core.schemas.string().optional(),
  code: core.schemas.string().optional(),
  message: core.schemas.string().optional(),
});

export declare namespace Warnings {
  interface Raw {
    type?: string | null;
    code?: string | null;
    message?: string | null;
  }
}
